syl20bnr/spacemacs

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-org/packages.el
Currently org mode tables are not well aligned when they contain non-ascii characters, like this:
With package [valign](https://github.com/casouri/valign), we can make things better.
> Use valign to align tables in spacemacs-org layer

- CHANGELOG.develop
- layers/+readers/epub/README.org
- layers/+readers/epub/packages.el
Similar to the keybindings added to the info layer in PR #14188, I here propose to add the same
keybindings to the epub layer. These J/K keybindings are currently undefined in the epub
layer. These keybindings are used in the Zathura document reader, they are very
convenient and I guess they feel very natural and are preferred over d/u by most people.
> Add convenient scroll keybindings to epub layer

- CHANGELOG.develop
- layers/+readers/pdf/README.org
- layers/+readers/pdf/packages.el
The `C-o` and `C-i` are free in the pdf-view mode, and these keybindings are probably more intuitive to evil users for jumping the history.
The current keybindings for jumping the history, `[` and `]`, were also added by me. I thought back then that `C-o` and `C-i` were not available (don't know how I got that idea). Those keybindings can be removed, but I chose to keep them here.
Although this PR binds `C-i` and even though I have set `dotspacemacs-distinguish-gui-tab t` in my dotfile, pressing `C-i` tells me that the keybinding is undefined while `TAB` does work. Anyway, I think the definitions in this PR are consistent with evil.
> Add evil consistent navigate history keybindings to pdf-layer

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-org/config.el
- layers/+spacemacs/spacemacs-org/packages.el
valign-mode is nice, but it could affect the performance when scaling in a big org buffer.
Add an opt-out for people who want to toggle valign-mode manually.
> Make valign-mode opt-out in org-mode-hook

- core/core-keybindings.el
Looks like we don't need all of this code anymore. Besides it should have better performance.  Except `long-name` aren't supported, but we don't use them much anyway.
> Use keymap based replacement for prefixes.

- layers/+tools/lsp/README.org
This fixes two errors in the lsp docs:
* `lsp-headerline-bredcrumb-enable` was recently defaulted to `t` upstream (in https://github.com/emacs-lsp/lsp-mode/pull/2416)
* The example for `lsp-lens-enable` says it shows how to enable code lens, but it actually shows how to disable it
> Fix some errors in lsp/README.org

- layers/+spacemacs/spacemacs-org/config.el
- layers/+spacemacs/spacemacs-org/packages.el
Due to laggy working with tables containing more than 100 lines, `valign-mode` should be disabled in default.
Fix: https://github.com/syl20bnr/spacemacs/issues/14223
> Disable valign in default

- layers/+tools/ipython-notebook/README.org
- layers/+tools/ipython-notebook/config.el
- layers/+tools/ipython-notebook/funcs.el
- layers/+tools/ipython-notebook/packages.el
By using the Jupyter notebook api, the ipython-notebook layer can be auto-completed by using the company-mode
> Make ipython notebook work with company-mode

- layers/+filetree/treemacs/config.el
problem:
The Treemacs layer is unable to find python 3 in Windows.
cause:
The Treemacs layer looks for "python3", but the executable is called
"python.exe" in Windows.
solution:
Let Treemacs check for python 3 upstream, it has a better method for finding the
python 3 executable in Windows.
> [treemacs] Check for git and python 3 upstream

- layers/+spacemacs/spacemacs-defaults/config.el
problem:
Reloading the configuration: SPC f e R
after changing the variable: dotspacemacs-fullscreen-at-startup
to: t
changes Emacs into fullscreen mode.
solution:
Only check the variable and change to fullscreen mode on startup,
before Spacemacs has been initialized.
Fixes: Reloading config with fullscreen-at-startup t (in macOS) toggles fullscreen mode #13073
Additional change:
`if` was changed to `when`, because there is no else statement.
> [defaults] Prevent fullscreen on config reload

- CHANGELOG.develop
- layers/+distributions/spacemacs-bootstrap/packages.el
problem:
Pressing: u
in the spacemacs-base distribution, shows:
evil-undo: Symbol’s function definition is void: undo-tree-undo
cause:
The evil undo system is setup as: undo-tree
but undo-tree is loaded in the spacemacs-editing layer,
and the layer isn't used by default in the spacemacs-base distribution.
solution:
Set the evil undo system to undo-tree when the undo-tree package is used.
Now if undo-tree isn't setup, then:
- u   uses the default Emacs undo command.
- C-r says: Customize ‘evil-undo-system’ for redo functionality.
> [base] Fix evil undo

- CHANGELOG.develop
- layers/+source-control/git/packages.el
problem:
The Magit w (apply patches) arguments are not remembered between sessions.
cause:
Magit reads the transient files:
history.el, levels.el, and values.el
before Spacemacs has redirected them to the .cache directory.
solution:
Redirect the files before magit reads them.
> [git] Restore magit transient args between sessions

- layers/+completion/helm/packages.el
problem:
The spacemacs-completion layer defines the variable:
helm-use-fuzzy
But the spacemacs-base distribution doesn't use the
spacemacs-completion layer by default.
helm-use-fuzzy is used in the helm layer.
When a helm buffer is opened, for example: `SPC SPC`
Then a warnings buffer opens:
>Error (use-package): helm/:config: Symbol’s value as variable is void: helm-use-fuzzy
solution:
Make sure that helm-use-fuzzy is bound and true.
> [base] Fix void helm-use-fuzzy

- layers/+emacs/org/packages.el
Set up autoload for a few org-roam commands via use-package.
I also replaced a number of obsolete functions (org-roam-dailies-...).
> Configure org-roam to lazy load

- layers/+email/mu4e/README.org
- layers/+email/mu4e/config.el
- layers/+email/mu4e/packages.el
This pull request addresses issue #13913.
Changes:
1. Added two configuration variables for the mu4e layer to control mu4e-org integration.
2. Optionally configures mu4e compose mode to support Org-mode syntax.
3. Improves lazy-loading of relevant features. E.g. loading org-mode does not automatically trigger loading of mu4e.
> Improving org-mu4e integration

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
I do not see any reason why the keybinding to enter transient-state in
org-agenda-mode should not be on `, .`. Therefore I propose here to
make that keybinding consistent with the keybindings for entering
transient states in most/all other modes.
> Add consistent org-agenda transient-state keybinding

- CHANGELOG.develop
- layers/+lang/ruby/README.org
- layers/+lang/ruby/config.el
- layers/+lang/ruby/funcs.el
- layers/+lang/ruby/layers.el
- layers/+lang/ruby/packages.el
This PR adds support for [prettier/plugin-ruby](https://github.com/prettier/plugin-ruby) in spacemacs' Ruby layer. Prettier can be configured to run on buffer save, or run ad-hoc via a keybinding. I tried to follow the implementation used by other layers for autoformatters, e.g. the javascript layer & typescript layer.
> Support prettier formatter for Ruby layer

- CHANGELOG.develop
- core/core-dotspacemacs.el
- core/core-spacemacs-buffer.el
- core/templates/.spacemacs.template
`dotspacemacs-startup-lists` by default shows a number of recent files and projects as two separate lists. If I've been working with a lot of files in one project, then all the recent files are from one project, even if I set `recents` to a large amount like 24. This change allows me to see the recent files by project. Suppose, for example, I have a `vegetables` project and a `fruit` project, and set `dotspacemacs-startup-lists` to `(recents-by-file . (2 . 3))`. In the home buffer I will see something like:
~/vegetables
lettuce.el
squash.el
tomatoes.el
~/fruit
apple.py
orange.py
banana.py
Even though only a subpath is displayed for each file, the click functionality still works---i.e. the link still has the full path under the covers.
I originally asked a …
> [core] support recents-by-project in dotspacemacs-startup-lists

- CHANGELOG.develop
- layers/+lang/emacs-lisp/config.el
- layers/+lang/emacs-lisp/packages.el
Like in other Emacs Lisp modes.
> [emacs-lisp] make `SPC m h h` and jump handlers work in `ielm`

- core/libs/page-break-lines.el
This definition requires 3 arguments. Having only two can cause Emacs a
wrong-number-of-arguments error (was reported on gitter). So this PR just
adds the date when the orginal functions were removed and the alias was
created. Just a minor fix.
> fix page-break-lines-mode alias definition

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
This is such an elementary org-journal command that it should have a
keybinding.
> Add org-journal-open-current-journal-file keybinding

- .ci/built_in_manifest
- core/libs/mocker.el
- tests/core/core-configuration-layer-ftest.el
We used an alias that seems to be declared in the one of the old mocker dependencies.
> fix latest mocker.el compat

- layers/+email/mu4e/packages.el
https://github.com/syl20bnr/spacemacs/issues/14275. Properly adding backwards compatibility changes for  mu4e < v 1.3.6.
> edited mu4e-org-link-support, add compatibility to mu4e < v.1.3.6

- layers/+emacs/org/packages.el
Unshadows 'K' in agenda-mode-map such that 'K' still maps to `org-habit-toggle-display-in-agenda`
> Fix issue #14250 by unshadowing 'K'

- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
Adds keybinding for `org-agenda-capture` `org-agenda-clock-goto` and `org-agenda-ctrl-c-ctrl-c`.
These are the same keybindings as in standard `org-mode`.
> Add some missing key bindings for org-agenda

- CHANGELOG.develop
- doc/DOCUMENTATION.org
- layers/+distributions/spacemacs-bootstrap/packages.el
Sometimes it is handy to show keymaps persistently with which-key. For example,
to show navigation keys in Info-mode, gnus, eww etc. This PR implements
handy toggles and documentation for that.
Of course this is just a quick way to implement some kind of alternative hydra transient states.
Also I am always happy about feedback/improvements/discussions, my PR's are merely proposals.
> Add toggles for specific persistent which-key keymaps

- CHANGELOG.develop
- layers/+lang/markdown/packages.el
I realized this is on by default in Spacemacs for Org. Arguably Spacemacs should have a somewhat consistent default experience between Org and Markdown.
If anyone disagrees, it's no big deal to me. I wasn't even going to suggest upstreaming it until I saw this in `layers/+emacs/org/packages.el`:
```emacs-lisp
(defun org/init-org ()
(use-package org
:defer ...
:commands ...
:init
(progn
...
(setq ...
org-src-fontify-natively t
...
```
Though it would be nice for look & feel of Spacemacs out of the box.
> [markdown] fontify code blocks natively: on by default

- layers/+emacs/helpful/README.org
- layers/+emacs/helpful/packages.el
- In addition to the spacemacs leader keys, also replace the default emacs
keybindings under `C-h`
- Fix a documentation copy-paste mistake for `SPC h d v`
> [helpful] Add missing global key bindings

- CHANGELOG.develop
- layers/+lang/scala/README.org
- layers/+lang/scala/config.el
- layers/+lang/scala/funcs.el
- layers/+lang/scala/packages.el
This feels like the natural place to put the SBT buffer, though we could also extend this with other values in the future. I defaulted this behavior to off in order to not impact folks' current setup.
The window needs to be dedicated because of its strange shape. Most other buffers (e.g. the Magit status buffer) will not look pleasant in it.
> [scala] provide an easy way to a small SBT buffer at frame bottom

- layers/+emacs/org/README.org
- layers/+emacs/org/config.el
- layers/+emacs/org/packages.el
Added two variables 
`org-persp-startup-org-file` and `org-persp-startup-with-agenda` initialized to `nil` with no changes to the current behavior.
These variables can be set by the user to initialize the @Org perspective with a specified file and/or a (custom) agenda view.
Docs will be updated, once the PR is accepted.
> Add variables for configuration of startup of the @Org perspective.

- core/core-spacemacs.el
Compiling core libs should based on `spacemacs-start-directory` instead of `user-emacs-directory`.
> [Core] *core-spacemacs.el: fix default-path for compiling built-in libs

- CHANGELOG.develop
- layers/+lang/emacs-lisp/funcs.el
This one annoyed me for quite some time. Finally, I got too tired of it.
Basically, right after edebug session Spacemacs gets stuck in evil-evilified-state. 
To reproduce:
- instrument any function `M-x spacemacs/edebug-instrument-defun-on`
- run the function, edebug session starts
- quit the session, or step through the function, whatever (it doesn't matter)
- after edebug session keys are in evilified state (where not all normal evil keys work as expected)
- e.g. you press `<escape>` - cursor turns yellow (should be orange)
> emacs-lisp: resets to evil-normal after edebug session

- CHANGELOG.develop
- core/core-dotspacemacs.el
- core/templates/.spacemacs.template
- layers/+spacemacs/spacemacs-defaults/funcs.el
- layers/+spacemacs/spacemacs-defaults/packages.el
Moved the function definitions for:
spacemacs//trailing-whitespace
spacemacs//set-whitespace-style-for-diff
from: spacemacs-default/packages.el
to:   spacemacs-default/funcs.el
Requested in: How to deactivate highlighting of trailing whitespace by default? https://github.com/syl20bnr/spacemacs/issues/13729#issuecomment-751231218
> [dotfile] new var: dotspacemacs-show-trailing-whitespace

- core/core-configuration-layer.el
problem:
When the Emacs frame has the default window width (80 characters).
Then the current restart to update message:
Emacs has to be restarted to actually install the new version of the packages (SPC q r)
is cut off at the Emacs frames right edge:
Emacs has to be restarted to actually install the new version of the packages (S
solution:
Shortening the message:
Restart Emacs to install the updated packages. (SPC q r)
says the same thing, and keeps it within 80 characters.
> [core] Shorten package update restart message

- layers/+distributions/spacemacs-bootstrap/packages.el
- layers/+source-control/git/packages.el
- layers/+spacemacs/spacemacs-evil/README.org
- layers/+spacemacs/spacemacs-evil/config.el
- layers/+spacemacs/spacemacs-evil/packages.el
- layers/+tools/shell/packages.el
It is impossible to ignore `evil-collection` anymore. `evil-magit` has been
deprecated recently and moved to `evil-collection`.
It will save time and effort for both Spacemacs and Evil to share and contribute
to `evil-collection` imo.
However I strongly prefer Spacemacs binding scheme over evil-collection's one.
We should only pick what we need from `evil-collection`.
This PR add mechanism to embrace `evil-collection` and apply it to shell layer (`vterm`)
and git layer.
Note: I still have a bug with git rebase binding. `C-j` and `C-k` are note bound to move commits. Must use `C-n` and C-p` instead. Not sure if it is our bug or `evil-collection's
> [spacemacs-evil] add evil-collection

- core/core-compilation.el
- core/core-dotspacemacs.el
- core/core-load-paths.el
- core/core-release-management.el
- core/core-spacemacs.el
- core/templates/.spacemacs.template
- dump-init.el
- early-init.el
- init.el
Hopefully those are the last shenanigans needed to make byte compilation of the core libs  bullet proof :thinking: 
Also  now byte-compilation is off by default (controlled by `dotspacemacs-byte-compile` variable in .spacemacs)
*I don't expect noticeable gains from  `byte-compilation` of core files/libs (even if we annotate everything we can with `pure`/`side-effect-free`) but hopefully it will make us prepared for native compilation thingy.*
> bytecomp stuff

- core/core-compilation.el
Fix for #14335
Apparently on some platforms/with some configs `(delete-file "foo/bar")` will report an error if the  file doesn't exist.
> Do not delete non existent files

- layers/+tools/lsp/README.org
Prompt to run `all-the-icons-install-fonts` in `layers/+tools/lsp/README.org` if both `all-the-icons` and `lsp-headerline` are enabled.
Fix: #14314
> Document: prompt to run `all-the-icons-install-fonts`

- CHANGELOG.develop
- doc/DOCUMENTATION.org
- layers/+completion/helm/packages.el
Equivalent to PR #14287 for ivy-layer
> Implement C(-S)-tab buffer switch in Helm layer

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
There are org-roam "daily" keybindings for yesterday/today/tomorrow, but the (useful) `org-roam-dailies-find-date` function doesn't have a keybinding in the org layer. This pull adds these keybindings under `[prefix] r d d` (final `d` for "date"), and notes the new keybinding in `README.org`
> [org] add keybinding for org-roam-dailies-find-date

- layers/+lang/c-c++/README.org
- layers/+lang/c-c++/config.el
- layers/+lang/c-c++/funcs.el
Require the `dap-mode` adapter to the official LLDB DAP backend (`lldb-vscode`)
by default.
> [c-c++] Add layer variable for DAP adapter selection

- CHANGELOG.develop
- layers/+lang/markdown/README.org
- layers/+lang/markdown/config.el
- layers/+lang/markdown/packages.el
Hi,
I had try the markdown live preview by following README.org in markdown layer folder, failed with no-error-message, after check the code, found the `markdown-command` is required but no hints in markdown layer documents.
So I add the documentation into README.org in markdown layer folder for configing the live-preview.
Thanks.
> [markdown] more document for using markdown-command

- layers/+filetree/treemacs/packages.el
Icons in `dired-mode` buffer are inconsistent with `treemacs-use-all-the-icons-theme` implied. Currently we can only see expected icons in `dired-mode` buffer ***after running command `treemacs` explicitly***.
Better if we can see corrent icon style in `dired-mode`, no matter whether `treemacs-mode` buffer is initialized. It should just depend on the variable `treemacs-use-all-the-icons-theme`.
> Also run `treemacs-load-theme` on `dired-mode-hook`

- layers/+completion/ivy/packages.el
which improves performance when many buffers opened.
Ref:
https://github.com/Yevgnen/ivy-rich#project-performance
https://github.com/syl20bnr/spacemacs/issues/10101
> [ivy-rich] enable ivy-rich-project-root-cache-mode

- layers/+intl/keyboard-layout/packages.el
Fixes: Broken Colemak bindings for Magit status buffer #14366
> [keyboard-layout] Fix colemak-hneio next/prev line in magit

- layers/+spacemacs/spacemacs-navigation/funcs.el
Pressing o `(spacemacs/ace-buffer-links)`
on the Spacemacs home buffer `SPC b h`.
Adds an ace link (one or more highlighted letters),
at the menu buttons, and the startup list entries.
The text: `[S P A C E M A C S]` gets an ace link,
but it isn't a button.
When the [?] button has been pressed, and the Quick Help
is open, then ace links appear on the open square brackets
for each key binding, but they aren't buttons.
In the lists: recent files, projects, etc.
The ace links appear before the first / (slash).
This means that in windows they appear after `c:`.
Add the ace links at the beginning of each widget-button.
> Fix home buffer ace links

- layers/+lang/emacs-lisp/funcs.el
- layers/+lang/emacs-lisp/packages.el
Clojure layer has similar function. I miss it in Elisp sometimes. Is it usefull?   That's basically `eval-print-last-sexp` but that also adds `;;`  which is cool since it doesn't break evaluation of the buffer :thinking:
> Add eval-to-comment elisp-mode function

- layers/+lang/fsharp/packages.el
eglot-fsharp is now distributed as a separate MELPA package from
fsharp-mode, so it needs to be listed in `fsharp-packages`.
Also, refactor some conditions to read more clearly.
> [fsharp] Declare package eglot-fsharp

- layers/+emacs/better-defaults/README.org
Just some small clarification due to some confusion on Gitter about the `C-e` behavior
> Improve better-dafault docs about possible bindings shadowed

- CHANGELOG.develop
- layers/+emacs/tabs/README.org
- layers/+emacs/tabs/config.el
- layers/+emacs/tabs/funcs.el
- layers/+emacs/tabs/packages.el
Ideally it would be great to implement tabs switch with C-tab (or C-}) that
shows the tabs as long as C is pressed. However Emacs does not support key
release events so this function uses a timer as a workaround.
To me Emacs looks better when tabs are hidden, and also packages like
pdf-continuous-scroll-mode break when tabs are shown.
> Add auto hide tabs feature to tabs layer

- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
- layers/+lang/emacs-lisp/funcs.el
Exiting `edebug-mode`, leaves the `evil-visual-state-map`
with only the two key bindings that are defined in:
`evilified-state--setup-visual-state-keymap`
```
y       evil-yank
escape  evil-exit-visual-state
```
Restore the `evil-visual-state-map` when exiting `edebug-mode`.
Added an alias for the new exit function:
`evilified-state--evilified-state-on-exit`
called: `evil-evilified-state-exit`
the opposite of: `evil-evilified-state`
> Restore evil-visual-state-map on edebug exit

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-editing/README.org
- layers/+spacemacs/spacemacs-editing/packages.el
Adds support for cycling between multi line block styles via [multi-line](https://github.com/IvanMalison/multi-line).
See also #11309 - thank you @Miciah for the suggestion all those years ago.
Demo:
> [editing] add binding for multi-line

- layers/+completion/helm/packages.el
- having font-lock enabled for swoop buffers is really slow
> Revert to default value of helm-swoop-speed-or-color

- layers/+spacemacs/spacemacs-evil/packages.el
I have a PR for that https://github.com/luxbock/evil-cleverparens/pull/71 but it
is not reviewed for a long time. Without this change when you do `ci"` the
cursor won't go in the "".
> [evil-cleverparens] `evil-cp-change' should move the point

- layers/+lang/markdown/README.org
- layers/+lang/markdown/config.el
- layers/+lang/markdown/packages.el
Removing the duplicating code introduced in https://github.com/syl20bnr/spacemacs/pull/14312, as upstream change https://github.com/jrblevin/markdown-mode/pull/602 can cover it.
> [markdown] remove duplicating code which already exists in "markdown-mode"

- core/core-env.el
As discussed in #14348, the env "DISPLAY" should not be stored in `.spacemacs.env`.
> [core-env] #14348 ignore env "DISPLAY" for .spacemacs.env

- CHANGELOG.develop
- layers/+source-control/git/packages.el
I believe `SPC g f d`  should be more "contextual", allowing user to perform operations
associated with the current file. 
For example, if you need to open the diff buffer related  to the exact line at point, there's currently no "Spacemacsy" key to do it quickly. One has to do: `C-c M-g d`.
Current `SPC g f d` keybinding opens "general" magit-diff dialog, not specifically aimed to help with operations related to the current file.
This tiny PR remaps `SPC g f d` to `magit-file-dispatch`, which feels to be exact mnemonic for this thing.
> Change SPC gfd to magit-file-dispatch

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-editing/README.org
- layers/+spacemacs/spacemacs-editing/packages.el
The `dired-quick-sort` hydra was bound to: `S`
But the introduction of `evil-collection-dired`
[[evil-collection] support for dired #14333](https://github.com/syl20bnr/spacemacs/pull/14333)
Now binds `S` to: `dired-do-symlink`
https://github.com/emacs-evil/evil-collection/blob/334670e29d964c5f591f75ccbf52b7b5faf4daba/modes/dired/evil-collection-dired.el#L66
It also restored the default evil behavior of: `s`
to: `evil-substitute`
But it isn't useful in the dired buffer since it is: read-only
> Bind s to the dired-quick-sort hydra

- layers/+completion/ivy/packages.el
To have this in standard spacemacs theme:
> [ivy] extend highlight for selection in emacs 27

- CHANGELOG.develop
- layers/+source-control/git/README.org
- layers/+source-control/git/packages.el
Fixes https://github.com/syl20bnr/spacemacs/issues/14434.
Builds upon https://github.com/syl20bnr/spacemacs/pull/14408.
> Restore SPC gfd for magit-diff, set SPC gfm for magit-file-dispatch

- layers/+email/mu4e/packages.el
it looks like it still would throw a message:
"mu4e-org-store-link: Please load mu4e before mu4e-org" if attempted to use
`org-store-link` before loading mu4e (for any kind of link, not just mu4e) 
I'm just going to bump the version number until
someone offers a better solution
> mu4e: require mu4e for mu4e-org-link-support

- CHANGELOG.develop
- layers/+emacs/org/packages.el
Fixes: org-brain doesn't have SPC menu https://github.com/syl20bnr/spacemacs/issues/13548
> [org][org-brain] Add SPC menu (vim or hybrid style)

- core/core-env.el
A minor change allowing environment variables to be stored when running Cygwin version of Emacs.
> Support system-type 'cygwin

- layers/+spacemacs/spacemacs-defaults/keybindings.el
This names the `SPC F` which-key entry.
before: `+prefix`
after: `Frames`
And adds "`...`" to the end of the descriptions,
for the keys that require additional user interactions.
> Bind frame keys using spacemacs|spacebind

- layers/+distributions/spacemacs-bootstrap/packages.el
Fixes: There is no keybinding to toggle vim/evil mode #13511
The toggle editing style prefix: `SPC t E`
always shows the same names:
```
e -> emacs (holy-mode)
h -> hybrid (hybrid-mode)
```
This causes some confusion about how to
switch to the vim (evil-mode) editing style,
from emacs or hybrid state.
Show which editing styles one will switch to:
In evil-mode:
```
e -> emacs (holy-mode)
h -> hybrid (hybrid-mode)
```
In holy-mode:
```
e -> vim (evil-mode)
h -> hybrid (hybrid-mode)
```
In hybrid-mode:
```
e -> emacs (holy-mode)
h -> vim (evil-mode)
```
> Improve editing-style toggles

- CHANGELOG.develop
- layers/+lang/python/funcs.el
ipython versions are usually in the form `X.X.X` but a dev version is installed it is printed as `X.X.X.dev` this makes an error in the python layer initialization.
This is useful as it has been months since `ipython` is not yet released as version 8 while `jedi` moved to version 0.18. The completion API used by `ipython` version 7 is deprecated for more than a year (for `jedi` version 0.17.2 it is still working with deprecation warnings).
Since `jedi` 0.18 the deprecation warning is removed and while spacemacs will correctly complete with `jedi` 0.18 ipython will be broken (crash).
The best course of action is to clone the master branch of https://github.com/ipython/ipython and install it (just `pip install -e .` from the cloned folder). So both ipython command and spacemacs can work.
> Fixes error if parsing ipython dev version

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
Add bindings for org-roam-alias-add as `SPC a o r a` and `SPC m r a`, to make it more convenient to add aliases to org-roam files.
> Add keybindings for org-roam-alias-add

- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
Enable `evil-surround-mode` when exiting evilified state.
If `evil-surround-mode` was enabled.
Currently it only disables `evil-surround-mode`.
This was discovered while exiting `edebug-mode`.
This also removes the unused variable:
`evilified-state--evil-surround`
It might have been intended for this purpose.
Otherwise it can be added back when
a use case for it is introduced.
> [evilified] Restore evil-surround

- CHANGELOG.develop
- layers/+lang/ess/README.org
- layers/+lang/ess/funcs.el
Add a keybinding (alongside all the other `SPC m s` ones) to quit the current inferior process REPL.
> [ess] add keybinding for ess-quit

- layers/+lang/groovy/README.org
The build system for https://github.com/prominic/groovy-language-server generates two different jars, this commit adds a note on which jar to use.
> Add note on which jar to use for groovy

- doc/FAQ.org
This expands the entry on including underscores and dashes in word motions to discuss `*` and `#` searches. There is a new solution for them is different, and simpler, than the solution for the other motions (but it is difficult to find).
For me, personally, this obviates the necessity of messing with the syntax definitions.
Some related issues: https://github.com/syl20bnr/spacemacs/issues/9740, 
https://github.com/syl20bnr/spacemacs/pull/1248, 
https://github.com/syl20bnr/spacemacs/issues/1261.
Many thanks to lyro@ for fixing https://github.com/emacs-evil/evil/issues/360.
> FAQ on including _ in words for `*` searches

- README.md
This is a simple update to the documentation:
Recent versions of homebrew use the syntax
```brew install --cask emacs```
instead of
```brew cask install emacs```
> update cask install instructions in README

- CHANGELOG.develop
- layers/+source-control/git/packages.el
Do we need the `:toggle` here as well, as it's [done for](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bsource-control/git/packages.el#L18) `forge` or this is good?
> git: adds orgit-forge so org links can be stored from forge topics

- CHANGELOG.develop
- layers/+tools/lsp/funcs.el
IMHO this should be global binding, the alternative was `SPC e e` because it can
be used everywhere, e. g. from compilation buffer to find the error causing the
build breakage.
> [lsp] Bind `SPC p E` to `helm-lsp-diagnostics`

- layers/+lang/haskell/README.org
- layers/+lang/haskell/packages.el
Using the correct target for the Haskell session is required when working on a
project with more than one target defined in the Cabal file.
> [haskell] Add a binding to change the target for the session

- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
In evilified visual state.
- Add the inner: `i` and outer `a` text objects.
- Add `o` to exchange the point and mark
(jump between the start and end of the region)
> [evilified] Visual state text objects, exchange point/mark

- .ci/built_in_manifest
- CHANGELOG.develop
- core/core-compilation.el
- core/core-configuration-layer.el
- core/core-customization.el
- core/core-dotspacemacs.el
- core/core-spacemacs.el
- core/libs/validate.el
- layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
- layers/+tools/shell/config.el
@smile13241324 ,  @duianto and  @sdwolfz  discussed if it makes sense to use defcustom for layer variables to solve issues like #14343 
This is a demo.
To test the validation You can try replacing something like:
``` elips
(shell :variables
shell-default-height 30
shell-default-position 'bottom)
``` 
in  Your .spacemacs file with a bad value:
``` elisp
(shell :variables
shell-default-height "foobar"
shell-default-position 'bottom)
```
> Validate layer variables if they are defcustoms

- layers/+emacs/org/packages.el
Since org-appear is [on melpa](https://melpa.org/#/org-appear), it should be preferred.
> Prefer downloading org-appear from melpa

- core/core-configuration-layer.el
This prints out an expression in valid Lisp syntax, so that, e.g.,
strings in the expression are quoted.
For example, I had the following in `dotspacemacs-additional-packages`:
```
(direnv :toggle (executable-find "direnv"))
```
Without this patch, the `:toggle` expression is printed as `(executable-find direnv)`, which looks like it is reading a variable called `direnv`.
> In SPC h d P, print :toggle expression using Elisp syntax

- CHANGELOG.develop
- layers/+lang/rust/README.org
- layers/+lang/rust/funcs.el
Currently, when `lsp` backend is used for `rust` layer, `SPC m s s` is bound to
`lsp-rust-switch-server`, which temporarily changes the preferred LSP server
for `rust-mode`, but it DOES NOT switch the running LSP server. Users need to
call `lsp-workspace-restart` to finish the switching.
This PR introduced a new function `spacemacs//lsp-rust-switch-server`, which is
a wrapper for the two aforementioned functions
>  rust: Improved LSP Rust server switch functionality

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
Used `y` as a mnemonic for yank (in the Vim, not the Emacs, sense).
> [org] add keybinding for org-copy-tree as with org-cut-tree

- doc/DOCUMENTATION.org
- doc/FAQ.org
When contributing to packages it is often handy to replace a package, already
installed and configured by some layer with a local version of the package (i.e.
a git repo). This commit adds instructions for how to achieve that.
> Add to docs, replacing a layer package with a local version

- CHANGELOG.develop
- layers/+email/mu4e/packages.el
Fixed, the following error, void variable `mu4e-view-mode-map`.
`Error (use-package): mu4e/:config: Symbol’s value as variable is void: mu4e-view-mode-map`
> Fix void variable `mu4e-view-mode-map`

- core/core-dotspacemacs.el
- core/templates/.spacemacs.template
Add choices for variables that are allowed to be nil
> Fix .spacemacs validation choices

- layers/+spacemacs/spacemacs-defaults/keybindings.el
Currently `C-n` `C-p` are bound to `next-line` and `previous-line` in `minibuffer-local-map`. This PR binds them to `next-line-or-history-element` and `previous-line-or-history-element`. This may be handy when using `M-:` to call `eval-expression`.
> Minibuffer bind C-n C-p to <next>/<previous>-line-or-history-element

- layers/+lang/factor/funcs.el
Without this, fuel mode is reloaded needlessly on every Factor REPL restart.
Now we only do that if the Factor about to be invoked is a different one than
before.
> [factor] Only reload fuel mode if factor root path has changed.

- layers/+email/mu4e/config.el
- layers/+email/mu4e/packages.el
Currently `mu4e` does not run automatically at startup. Users will not get email notification until they run `mu4e` command explicitly. This PR provide a switch to make `mu4e` auto run in background at emacs startup.
> Provide a switch to auto run mu4e at emacs startup

- core/core-dotspacemacs.el
This PR simple makes the type of `dotspacemacs-additional-packages` same as `dotspacemacs-configuration-layers`'s.
fixes #14535 #14537 #14529 https://github.com/syl20bnr/spacemacs/issues/10638#issuecomment-803247326
> fixup! Validate .spacemacs variables.

- layers/+themes/colors/funcs.el
Removes a function that already exists in [packages.el](https://github.com/syl20bnr/spacemacs/blob/bc51b6a5eab58883ad51fcdd12c8cdfbdb74170d/layers/%2Bthemes/colors/packages.el#L121-L125)
> [colors] Remove duplicate function

- layers/+lang/c-c++/funcs.el
Fix #14579. The variable `c-c++-enable-rtags-completion` is for enable/disable the rtags completion.
> [+layer/c-c++] fix #14579, respect the `c-c++-enable-rtags-completion` setting

- README.md
I was following the instructions of the README.md for macOS, then while following the [Install Source Code Pro font](https://github.com/syl20bnr/spacemacs/blob/develop/README.md#install-source-code-pro-font) step, I noticed that it was not with the new syntax for cask.
This PR changes the [Install Source Code Pro font](https://github.com/syl20bnr/spacemacs/blob/develop/README.md#install-source-code-pro-font) section with the same disclaimer used in [Emacs installation section](https://github.com/syl20bnr/spacemacs/blob/develop/README.md#using-cask).
> Update README.md with new Cask syntax

- layers/+spacemacs/spacemacs-defaults/packages.el
problem
The evil-collection is loaded in the spacemacs-evil layer.
The spacemacs-evil layer isn't enabled by default
on the spacemacs-base distribution.
solution
Add buff-menu to the list: spacemacs-evil-collection-allowed-list
after the evil-collection has loaded.
> [base] Fix evil collection buff menu

- layers/+tools/lsp/README.org
Some parts of the README.org file for the lsp layer use Markdown syntax,
this commit fixes this. In one instance, tildes need to be used instead
of equal signs due to the fact it is at the beginning of the cell; org
thinks it is a formula and displays an error instead of the original
text.
Also the value of lsp-navigation is shown unquoted, this commit quotes
the possible values.
> [lsp] Fix org markup

- doc/DOCUMENTATION.org
- layers/+frameworks/vue/funcs.el
- layers/+lang/clojure/funcs.el
- layers/+lang/latex/config.el
- layers/+spacemacs/spacemacs-misc/packages.el
- Add `dumb-jump-xref-activate` hook to `xref-backend-functions`, which
add a fallback option, i.e. `dumb-jump`, when no better alternatives
is available
- Removed the obsolete interface `dumb-jump-go` from the following layers:
- clojure
- latex
- vue
- The global binding `SPC j q` requires the obsolete function
`dumb-jump-quick-look` and is therefore removed
> dumb-jump: Replace obsolete interface with xref-backend

- layers/+frameworks/react/funcs.el
This amended commit 58243c67f88ca8b54f2891b05046a119292f6b13
There is an unnecessary `when-let*` form, and it's replaced by `when`.
> react: minor change

- layers/+lang/python/funcs.el
Added the missing branch `'pyls`, so it won't evaluates to `(require nil)` and causes error.
Also added a catch all branch to report the error.
> fixup! python: refactor

- CHANGELOG.develop
- layers/+lang/php/packages.el
Fetch packages, which can't be found in Melpa anymore, from their GitHub repos:
- [phpcbf](https://github.com/nishimaki10/emacs-phpcbf)
- [php-auto-yasnippet](https://github.com/emacs-php/php-auto-yasnippets)
Fixes #14381
> [+layer/php] Fix missed packages

- layers/+lang/elm/funcs.el
`spacemacs|add-company-backends` is a macro, so arguments are taken as-is, instead of being evaluated.
The arguments to `:backends` must take the form of:
> fixup! elm: refactor

- layers/+lang/latex/funcs.el
> fixup! latex: refactor

- layers/+lang/lua/funcs.el
> fixup! lua: refactor

- layers/+lang/nim/funcs.el
> fixup! nim: refactor

- layers/+lang/perl5/funcs.el
> fixup! fixup! perl5: refactor

- layers/+tools/cmake/funcs.el
> fixup! cmake: refactor

- layers/+tools/terraform/funcs.el
> fixup! terraform: refactor

- layers/+lang/purescript/funcs.el
> fixup! purescript: refactor

- CHANGELOG.develop
- layers/+email/notmuch/funcs.el
- layers/+email/notmuch/packages.el
The bindings `d`/`D` were not working in `notmuch-tree-mode`.
The cause is that `spacemacs/notmuch-message-delete` calls `notmuch-search-tag` and this function does not work in tree-mode. 
The solution is to duplicate `spacemacs/notmuch-message-delete` into `spacemacs/notmuch-search-message-delete` and `spacemacs/notmuch-tree-message-delete`, adapting the inner calls to the corresponding functions of each mode.
>  Fixed a bug in notmuch-tree which was preventing d/D bindings to work

- CHANGELOG.develop
- core/core-dotspacemacs.el
- core/core-spacemacs-buffer.el
- core/templates/.spacemacs.template
It sets the minimum delay in seconds between number key presses.
On the Spacemacs home buffer.
> [dotfile] New var: dotspacemacs-startup-buffer-multi-digit-delay

- layers/+lang/python/funcs.el
The PR splits the single `when` into two so that `python-poetry-activate` is actually checked. In the current implementation `(spacemacs//poetry-activate)` is called regardless of the value of `python-poetry-activate`.
> Fix bug in `spacemacs//python-setup-backend ()`

- core/core-configuration-layer.el
**problem:**
`SPC f e U` checks if packages have updates.
But if the current buffer isn't the Spacemacs home buffer,
then the minibuffer just shows:
>Do you want to update 1 package(s)? (y or n)
There's no information about which packages have updates.
Canceling the prompt with: `n`
and switching to the messages buffer `SPC b m`, does list them.
>(Spacemacs) --> Found 1 package(s) to update:
>
>(Spacemacs) dap-mode
But it doesn't work to switch to the home buffer,
because that information was erased when the home buffer was refreshed.
**solution:**
Switch to the home buffer before checking for updates.
> Check package updates from Spacemacs home buffer

- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
The Emacs documentation is not very clear about the best way to use org-agenda,
especially regarding integration of the diary into org. This PR adds most
sensible configuration recommendations. More info in the commit messages.
> Add docs agenda usage recommendations

- layers/+lang/rust/README.org
- layers/+lang/rust/config.el
- layers/+lang/rust/funcs.el
- layers/+lang/rust/packages.el
- layers/+tools/lsp/funcs.el
- Introduced a new command cargo-process-outdated
- Certain commands are known to change Cargo.toml and needs to reload workspace,
wrapper functions that automatically reload workspace are added.
- spacemacs/cargo-process-add
- spacemacs/cargo-process-rm
- spacemacs/cargo-process-outdated
- Added a layer variable for rust layer, cargo-process-reload-on-modify,
which toggle the aforementioned behaviour.
- Added a new utility function in LSP layer, which returns server ID associated
with current project.
- spacemacs//lsp-client-server-id
- Rearranged keybindings for rust layers (see table below for details)
Commands wrapped with auto-reload functionality:
|Command                  |Binding      |
|-------------------------|-------------|
|`cargo-process-repeat`   |`SPC m c .`  | …
> rust and lsp: better integration of lsp-rust-analyzer-reload-workspace

- core/core-dotspacemacs.el
After new custom `dotspacemacs-*` variables being introduced in `core/core-dotspacemacs.el`, if one has an old `.spacemacs` without these variables set, `SPC f e R` will complain error messages like
```
Variable: "dotspacemacs-emacs-dumper-dump-file" has value: "nil" that doesn't match its type: "string"...
```
even if these variables have already had initial values.
This is because `dotspacemacs||let-init-test` macro only locally declares these variables without setting them with their current values.
This pull request fixes this issue by expanding `(dotspacemacs/get-variable-list)` into `'((var1 value1) (var2 value2) ...)` list instead of `(var1 var2 ...)`.
> [Fix] `dotspacemacs/test-dotfile` complains error on new custom vars

- layers/+lang/c-c++/config.el
Closes https://github.com/syl20bnr/spacemacs/issues/14631
Since Spacemacs doesn't really have versions I figure `nil` is the best we can do?
> [c-c++] Fix "Wrong number of arguments" on Emacs 28

- layers/+lang/latex/packages.el
It's reported that
https://github.com/syl20bnr/spacemacs/commit/f136f465abf599f6869b178e9338c72053444aec
caused this issue.
But I'm not convinced..
> Fix #14641

- layers/+tags/gtags/funcs.el
- layers/+tags/gtags/packages.el
make bindings stick to minor modes of helm/counsel-gtags-mode not major mode. so
the bindings will only be in force when ggtags-mode is enabled.
deprecate functions spacemacs/counsel-gtags-define-keys-for-mode and
spacemacs/helm-gtags-define-keys-for-mode that add ggtags bindings to major
mode. Next step is to remove these function calls from client layers.
> [gtags] improve

- layers/+lang/latex/config.el
In commit f136f46 spacemacs//init-jump-handlers-MODE was removed,
which is used by the latex layer. Change to call to add-to-list instead.
> Fix call to deleted method in latex layer

- layers/+lang/scheme/README.org
- layers/+lang/scheme/config.el
- layers/+lang/scheme/packages.el
The configuration for various scheme implementations has been split out of the
[geiser package](https://gitlab.com/emacs-geiser), breaking the current layer support for the implementations.
This PR adds a simple fix for the scheme implementations support.
Anybody is free to improve the code, but at least the layer will be fixed
> Fix scheme layer support for scheme implementations

- CHANGELOG.develop
- core/core-debug.el
- doc/DOCUMENTATION.org
- doc/QUICK_START.org
- layers/+completion/helm/packages.el
- layers/+completion/ivy/packages.el
For introspection purposes it can be nice to have this functionality. Also this
function can be used to get an overview of which ex-commands are available.
> Add describe evil ex-command functionality

- layers/+source-control/git/packages.el
problem
In the `spacemacs-base` distribution.
When the `git-enable-magit-todos-plugin`
layer variable is enabled.
Then the following message appears on startup:
>An error occurred while pre-configuring magit-todos in layer git (error: (void-variable spacemacs-evil-collection-allowed-list))
cause
The `spacemacs-evil-collection-allowed-list` variable
is assigned in the `git` layer.
But it's defined in the `spacemacs-evil` layer.
The `spacemacs-evil` layer isn't used by default
in the `spacemacs-base` distribution.
solution
Check that the `spacemacs-evil` layer is used
before adding to the variable.
> [base] Fix void spacemacs-evil-collection-allowed-list

- layers/+distributions/spacemacs-bootstrap/packages.el
- layers/+spacemacs/spacemacs-evil/packages.el
Fixes: vim layer key binding of "J" in dired mode #14614
problem
The evil collection binds "J" to `dired-go-to-file`
It overrides the Spacemacs `helm` and `ivy` equivalent commands.
`spacemacs/helm-find-files' has fuzzy matching and other features
`spacemacs/counsel-find-file' has more `M-o' actions
And the `ivy` layer uses the `spacemacs/helm-find-files` command.
solution
Move the Spacemacs definitions of "J",
after the evil collection dired keys have been setup
from: `spacemacs-bootstrap/packages.el`
to: `spacemacs-evil/init-evil-collection`
And use `spacemacs/counsel-find-file` in the `ivy` layer.
> [dired] Add ivy command and replace evil collection key

- CHANGELOG.develop
- layers/+web-services/search-engine/README.org
- layers/+web-services/search-engine/config.el
- layers/+web-services/search-engine/packages.el
Amazon search engine is of limited use if you live overseas :)
> Search Engine layer: Allow customization of Amazon site TLD.

- layers/+lang/windows-scripts/funcs.el
- layers/+lang/windows-scripts/packages.el
Fixes #14626 
Now the two convenient bindings are only set when the user explicitly invoke `windows-scripts/bat-outline`
> fixup! windows-scripts: replaced dos.el with bat-mode, added bmx-mode

- layers/+lang/python/config.el
- layers/+lang/python/packages.el
This is a regression we have in multiple languages. We need to add the backend setup function to `<major-mode>-local-vars-hook` so that people can override a language backend in a given project. See the Emacs documentation on this wonderfully named variable [hack-local-variables](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html).
For instance with the following `.dir-locals.el` at the root of a git repository I can choose to use `anaconda` instead of `lsp` (useful for legacy python projects):
```.emacs
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")
((python-mode . ((python-test-runner . pytest)
(python-backend . anaconda))))
```
This feature is explained in the README.org files of all the languages …
> [python] Fix directory specific python-backend

- layers/+frameworks/react/funcs.el
commit 58243c67f cleans up the React layer nicely but introduces
a regression where files are not auto detected correctly.
This commit simply restores the previous code where needed to make it
work again.
> react: fix file auto detection

- core/core-customization.el
- layers/+lang/go/config.el
- layers/+lang/groovy/config.el
- SAFE can either be a function or t.
- When it's t, use a default validation function
`(lambda (val) (validate-value val TYPE t))`
- When it's a function, use the supplied function.
-------
Take `groovy-backend` as example, notice the `SAFE` argument is `t`.
```elisp
(spacemacs|defc groovy-backend (if (configuration-layer/layer-used-p 'lsp) 'lsp 'company-groovy)
"The backend to use for IDE features.
Possible values are `lsp' and `company-groovy'.
If not set then 'company-groovy` is the default backend unless `lsp' layer is used"
'(choice (const lsp) (const company-groovy)) nil t)
```
Check the safety validator function
```elisp
ELISP> (get 'groovy-backend 'safe-local-variable)
#f(compiled-function
(&rest args2)
#<bytecode 0x15901b8b29c9>)
ELISP> (aref (get 'groovy-backend …
```
> core-customization: improved SAFE variable handling

- layers/+tools/eaf/README.org
- layers/+tools/eaf/packages.el
The layer got broken due to some minor changes in the eaf package by the eaf
developers. This PR fixes the layer to a working state.
> Fix: update eaf layer

- layers/+lang/racket/packages.el
`racket-describe-mode` is a read-only mode that comes with its own keybinding (i.e. `q` for quit).
To make those keybindings available, this PR makes the mode open in evilified state.
Additionally, it contains links, so this PR binds `o` to `link-hint-open-link`
(`ace-link` does not support this mode)
> configure racket-describe-mode keybindings

- layers/+lang/typescript/packages.el
The bug is that when using the following typescript layer configuration, flycheck doesn't have any checker available in typescript-tsx-mode.
```emacs-lisp
(typescript :variables
typescript-backend 'lsp
typescript-linter 'eslint
typescript-lsp-linter nil)
```
The root cause is that the `(pcase ...)` code, in typescript/packages.el, never got executed . Removing the surrounding `(with-eval-after-load 'lsp` fixes it. 
Given  `(pcase ..)` never executed, typescript-mode still have some flycheck checkers available because flycheck has eslint configured for typescript-mode by default, see flycheck.el line [9773](https://github.com/flycheck/flycheck/blob/f8c679fff349850c80541a31de50009c3c15d4c9/flycheck.el#L9773) and line [12254](https://github.com/flycheck/flycheck/blob/f8c679fff349850c80541a31d …
> Fix eslint not available for typescript-tsx-mode

- layers/+emacs/org/README.org
- layers/+emacs/org/config.el
- layers/+emacs/org/packages.el
You can now export org files as AsciiDoc documents.
Use org-export-dispatch (`C-c C-e` or `SPC e e`) to see options for exporting to AsciiDoc.
```emacs-lisp
(setq-default dotspacemacs-configuration-layers '(
(org :variables
org-enable-asciidoc-support t)))
```
Also I don't want credit, so I didn't update the changelog.
> Added asciidoc support.

- layers/+lang/ocaml/packages.el
merlin-company and merlin-iedit were split out of the main merlin
package.  Add them to the ocaml-packages list.
> [ocaml] Fix for merlin package split

- CHANGELOG.org
- layers/+emacs/org/README.org
- layers/+emacs/org/config.el
- layers/+emacs/org/packages.el
Org-Roam provides org-roam-protocol, a feature that allows the graphs generated by `org-roam-graph` and org-roam-server to contain cilckable links, which open the corresponding  org-roam file.
> Add support for org-roam-protocol

- layers/+window-management/exwm/funcs.el
- layers/+window-management/exwm/packages.el
`first` and `list-length` are aliases for `car` and `cl-list-length`
respectively. Using these aliases causes emacs to error with a `symbol's function
definition is void` error, but using their real names causes no error.
> Replace function aliases with their real names

- layers/+lang/dart/config.el
- Labelled `dart-backend` as safe local variable.
All setup functions are already added to local variable hook.
See: https://github.com/syl20bnr/spacemacs/issues/14653
> dart: Fix local vars

- layers/+lang/elixir/config.el
- layers/+lang/elixir/packages.el
- Labelled `elixir-backend` as safe local variable.
- Added local variable hooks of elixir mode:
- `spacemacs//elixir-setup-backend`
All other setup functions are already added to local variable hook.
See: https://github.com/syl20bnr/spacemacs/issues/14653
> elixir: Fix file local vars

- layers/+lang/erlang/config.el
- layers/+lang/erlang/packages.el
- Labelled `erlang-backend` as safe local variable.
- Added local variable hooks of erlang modes:
- `spacemacs//erlang-setup-backend`
- `spacemacs//erlang-setup-company`
See: https://github.com/syl20bnr/spacemacs/issues/14653
> erlang: Fix local vars

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-defaults/keybindings.el
Currently, if a user tries to use the 'ttm' key combination and their
emacs version is >24.3, timeclock-mode complains that
timeclock-modeline-display is deprecated. Spacemacs itself has
deprecated support for Emacs < 25.1 per CHANGELOG.develop. This commit
thus calls the new function without checking emacs-version for versions
for which the old function should be called.
> Use timeclock-mode-line-display in default bindings

- CHANGELOG.develop
- layers/+emacs/org/packages.el
Fixed ox-asciidoc as per issue #14695
I just deleted one line, tested it, and it works again.
> fixed asciidoc export

- core/core-transient-state.el
See comment: https://github.com/syl20bnr/spacemacs/commit/bfec25422108952598010a50babb87565f9ba935#r49828503
> [core] Fix 'append nesting in transient-state-format-hint macro

- layers/+lang/erlang/packages.el
Fixing a typo when calling `spacemacs/run-prog-mode-hooks`
> [erlang] fix run-prog-mode-hooks function call

- core/core-load-paths.el
- core/core-versions.el
- Conform to standard ELISP file practice.
- Rearranged the top-level forms s.t. Variables and constants are declared at top.
- Added section markers and documentations.
- Use three or more `;` as a section header. They work well with built-in outline-mode. `M-j` and `M-k` is the binding to quickly navigate between them.
- Optionally use `^L` (form-feed) as a divider for the ELISP file. It's rendered as a horizontal divider. And it works with `backward-page` (`C-x [`) and `forward-page` (`C-x ]`)
> [documentation]: Improved core-load-paths and core-versions

- layers/+window-management/exwm/README.org
- layers/+window-management/exwm/config.el
- layers/+window-management/exwm/funcs.el
- layers/+window-management/exwm/packages.el
I'm not sure how best to start doing this, but the branch over at
timor:spacemacsOS has moved ahead a bit.  I've grown used to a lot of these
changes, and would like to see them moved to the main develop branch.  But, the
pull request (formed by merging in CestDiego:spacemacs/SpacemacsOS in #3321)
started diverging.
Again, I'm not sure how to approach moving together these two changes.  Maybe
@timor can help somehow??
This at the least moves in some little things from Timor's branch:
- Can enable exwm-systemtray with `exwm-enable-systray`
- Can enable running XDG autostart applications (only in XDG_USER_HOME/autostart
for now) with `exwm-autostart-xdg-applications`
- Support for reading `.desktop` files and XDG autostart.
- Can specify additional code appended to exwm-init hook with …
> SpacemacsOS: provide new layer variables for systray and autostart

- doc/QUICK_START.org
Although the commit message below is only my opinion, I have written it in a style more suitable for a commit message. Anyway, this PR is only a proposal and if you agree with it then you could merge it (or provide feedback first).
The [quick-start](https://www.spacemacs.org/doc/QUICK_START.html) starts with
explaining that users can build their own layers. Instead, it should start by
showing how easy and straightforward it is to use one of the existing layer,
then continue about the possibility of creating personal layers. It is only a
small detail, but it can make a substantial difference for people who peek into
the quick-start guide and decide if it is worth the trouble to switch to
Spacemacs (Many newcomers think that even only trying another editor, is
probably not worth it because …
> Improve quick-start guide

- CHANGELOG.develop
- layers/+lang/ocaml/packages.el
According to https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/ocaml/packages.el#L160, the documentation could not be followed to make `ocamlformat` properly work when saving a file.
> [ocaml] Fixed variable name to make ocamlformat properly working on save

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/config.el
- layers/+emacs/org/funcs.el
- layers/+emacs/org/packages.el
Part of the excellence of Spacemacs is that it helps beginners to ease into the ELisp (or even mostly stay out of it). When I was first using Org, I was surprised that there was no existing one-and-done way to turn on dependency enforcement. After reading up on it and experimenting, I got a configuration represented by `'naive-auto` in this PR. I used that for a long time, but after beginning to use more complex Org workflows, it didn't work well for me anymore. By then I was much more comfortable in ELisp, and the result of much experimentation is represented by`'semiauto` here, which is slightly more intrusive to the user's workflow but surprisingly unopinionated. I envision that if someone what it to get really fancy with it, a `dwim-auto` or `smart-auto` would also be possible, that …
> [org] sane default strategies for enforcing `TODO` dependencies

- layers/+lang/ocaml/config.el
The variable was renamed in #14728 to match the documentation, but the
defvar was not updated.
> [ocaml] Fix name of layer variable in defvar

- CHANGELOG.develop
- layers/+lang/python/README.org
This commit reflects pip's own documentation. Quotes are required
around 'python-language-server[all]' to install it correctly.
> Update pyls install command to use quotes

- core/core-transient-state.el
This adds a :timeout keyword for spacemacs|define-transient-state, it
make use of :timeout keyword defhydra according to
https://github.com/abo-abo/hydra/wiki/internals.
"The :timeout key starts a timer for the corresponding amount of seconds that disables the hydra. Calling any head will refresh the timer."
> [core] Add :timeout/:idle for spacemacs|define-transient-state

- .gitignore
- CHANGELOG.develop
-------
Dired's image cache dir shows as untracked in git.
Add to `.gitignore`.
> Add 'image-dired' directory to .gitignore.

- CHANGELOG.develop
- core/core-dotspacemacs.el
- core/core-spacemacs-buffer.el
- core/templates/.spacemacs.template
This also defines the Spacemacs home buffer key bindings,
in the `emacs-startup-hook`.
Because the keys were being defined to early,
before the new value of: `dotspacemacs-show-startup-list-numbers`
was set in `.spacemacs`.
> [home] New var dotspacemacs-show-startup-list-numbers

- core/core-spacemacs-buffer.el
problem
It might not be clear how the note can be closed.
solution
Add a button: Close note
to the bottom right of the notes:
Quick Help and Release Notes
---
Quick Help
Release Notes
> [home] Add button: Close note

- layers/+tools/eaf/README.org
- layers/+tools/eaf/packages.el
This PR reimplements the refactor changes by @lebensterben but with his fix as
he suggested [here](https://github.com/syl20bnr/spacemacs/pull/14681#discussion_r616060958)
> Small fix to eaf-layer refactor

- layers/+vim/evil-better-jumper/README.org
https://github.com/syl20bnr/spacemacs/issues/5471 helps point out the non obvious default binding of `dotspacemacs-distinguish-gui-tab` to nil, this README update makes it explicit, hopefully saving future users of this new layer some troubleshooting of the `C-i` keybinding.
> [evil-better-jumper] Update layer documentation

- core/core-spacemacs-buffer.el
problem
The number keys searches for a line starting with a number,
from the beginning to the end of the buffer,
even if they are above or below the window.
solution
Only search for the visible number lines.
> [home] Only jump to visible nr lines

- core/core-jump.el
we don't need it and it doesn't work
refs:
https://github.com/syl20bnr/spacemacs/issues/14577
https://github.com/syl20bnr/spacemacs/commit/c825035e48c047f907968813a4bf57cace05ac21
> [core] remove jump-to-reference from core-jump

- layers/+tools/eaf/packages.el
Counsel is specific to Ivy, the universal M-x command is
`execute-extended-command`.
> Replace counsel-M-x command in eaf-layer

- CHANGELOG.develop
- core/core-keybindings.el
- layers/+lang/csv/packages.el
I tried to add a sort of general way to inherit key bindings.  I would have automatically computed the parent mode but it is not known until the package is loaded, so I would have had to move the bindings to `:config`, which would have been worse (key bindings no longer autoload the package).
This is an alternative solution to #14759.
> [csv] Make tsv-mode inherit csv-mode's leader key bindings

- CHANGELOG.develop
- layers/+lang/python/README.org
- layers/+lang/python/config.el
- layers/+lang/python/funcs.el
LSP warns that pyls is unmaintained and the user should install pylsp. This PR updates the python correspondingly.
If still pyls is installed instead of pylsp, then lsp shows a warning that the
user should install/update to the new fork i.e. pylsp.
> Update python layer to use pylsp (new maintained fork of pyls)

- CHANGELOG.develop
- layers/+completion/auto-completion/funcs.el
At present, if using vim style (or hybrid with
`hybrid-style-enable-hjkl-bindings` set to t), then the `auto-completion` layer
will map `C-j` and `C-k` to `company-select-next` and `company-select-previous`,
respectively on the `company-active-map` keymap. However, if one filters the
results (for example using `C-M-/` or by searching with `C-s`), then `C-j` and
`C-k` cause the filtering to stop and returns the completion list to what it was
pre-filtering. This seems undesirable as presumably one would want to use `C-j`
and `C-k` to navigate the filtered list rather than having to switch to arrow
keys or `C-n` and `C-p`.
When searching (or having filtered), a new keymap called `company-search-map` is
active, which does not have `C-j` or `C-k` bound on it explicitly, and has a
default key …
> auto-complete: Ensure hjkl bindings are respected during company search/filter

- layers/+window-management/exwm/README.org
- layers/+window-management/exwm/packages.el
Recently, #14714 added `desktop-environment-mode`.  This means that we don't
need to separately define bindings like `<XF86MonBrightnessUp>`, but can instead
lean on the user to enable `desktop-environment-mode` in `init.el`.
`desktop-environment-mode` should not be loaded by default since it is
linux/unix-centric.
Looking at my previous PR, I added `desktop-environment-mode`, then never used
it.  Oops.
> [exwm] Remove manual XF86 keybindings

- layers/+spacemacs/spacemacs-defaults/packages.el
When using `spacemacs/jump-to-definition` (`g d`) in e.g. guile source code, Spacemacs opens a xref buffer, which is a read only buffer. Generally read-only buffers should open in evilified state, and indeed here it "unshadows" many of the xref-buffer-mode's convenient default keybindings.
> Evilify xref--xref-buffer-mode

- layers/+lang/clojure/funcs.el
`xref-find-definitions` is an interactive function that requires one argument `identifier`. It either needs to be called with `call-interactively`, or better yet, by being forwarded the `sym-name` as the `identifier`.
> Not using "call-interactively" result in error

- layers/+completion/helm/README.org
- layers/+completion/helm/packages.el
Remove `C-o` keybinding from helm-bookmarks.
Add `S-RET` keybinding to open file/buffer/bookmark in other window for
helm-files helm-buffers and helm-bookmarks.
Advantage: Consistent behavior. It is pretty cumbersome to use the persistent
action provided by helm to open files/buffers/bookmarks in the other window.
I renamed the branch, so the other PR https://github.com/syl20bnr/spacemacs/pull/14781 was closed.
> [helm] Add `S-RET` keybinding for helm modes to open in other window

- core/core-spacemacs-buffer.el
problem
Opening the full release note, leaves the cursor at the
beginning of the second line after the preview.
solution
Leave the cursor at the beginning of the first line after the preview.
> [home] Fix full release note cursor position

- layers/+source-control/version-control/keybindings.el
In the VCS Transient State (`SPC g .`)
The key: `d` is bound to: `magit-ediff`
But `d` isn't shown in the VCS TS.
> [version-control] Show bound but unlisted VCS TS key: d

- layers/+intl/chinese/packages.el
Fix the warning message:
`layers/+intl/chinese/packages.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'`
> [+intl/chinese] fix warning for quote lambda function

- layers/+lang/scheme/README.org
- layers/+lang/scheme/packages.el
In the scheme REPL, RET is bound to `geiser-repl--maybe-send` which most times
sends the input instead of inserting a newline. Therefore this separate
keybinding for that will always insert the newline is required.
Also the `geiser-doc-mode` is read-only and should get evilified to not shadow its default keybindings.
> Evilify geiser-doc-mode-map and add keybindings in scheme layer

- CHANGELOG.develop
- doc/DOCUMENTATION.org
There's quite a lot of them. Grouping them makes them easier to parse for humans.
I also extended the descriptions of some bindings/functions.
> Group lisp state key bindings

- layers/+tools/eaf/packages.el
EAF recently added a system monitor. Add `SPC a a s` to open it.
Also add `SPC a a M` to open the eaf music player.
> Add bindings for opening eaf applications

- CHANGELOG.develop
- layers/+source-control/perforce/README.org
- layers/+source-control/perforce/packages.el
Shelving and unshelving changelists are operations commonly used when
choosing Perforce as a VCS solution. Package consumed by the "perforce"
layer already provides "p4-shelve" and "p4-unshelve" commands that can
be exposed by the layer. Provide keybindings for these two commands as
well.
> [perforce] Add p4-shelve and p4-unshelve commands with keybindings

- layers/+distributions/spacemacs-bootstrap/funcs.el
The code changed here wants to distinguish the cases of whether `arg` is a list
with one set of args to `spacemacs|diminish` or a list of a list of such args.
It used to look at the second element of `args` to make that distinction.
Consequently, if you want to specify a list of a list of args for
`:spacediminish`, you'd have to have at least two such lists of args in the list.
However in
https://github.com/syl20bnr/spacemacs/commit/38f582d785627fe996141d15aa54cdba2c3167a4
a usage with a list of just one list of args was introduced.
This fixes changes the detection so that it looks at the first element of `arg`.
If that's a list, `arg` is assumed to be a list of lists of args to
`spacemacs|diminish`. If it's not, it's assumed to be just a list of args to
`spacemacs|diminish`. That works …
> Fix one diminish pattern in a list in :spacediminish

- layers/+tools/transmission/README.org
The key binding hints in the README do not reflect the correct actions.
> Fix key binding in README in layers/tools/transmission

- layers/+lang/racket/packages.el
At least in Emacs >= 28.0.50 a warning occurs at startup when enabling racket
mode:
`.emacs.d/profiles/spacemacs/layers/+lang/racket/packages.el: Warning: (lambda nil \.\.\.) quoted with ' rather than with #'`
In 27.2 the warning does not appear.
In any case, the warning is fair and the change does not really affect anything
apart from the anonymous function being compiled potentially.
> racket: Function-quote company-mode-hook function

- layers/+spacemacs/spacemacs-misc/local/devdocs/devdocs.el
- layers/+spacemacs/spacemacs-misc/packages.el
The new devdocs https://elpa.gnu.org/packages/devdocs.html requires emacs 27.1.
Spacemacs is still content with emacs 26.3. The old devdocs package
https://github.com/xuchunyang/DevDo is compatible with emacs 26.3.
> Use local copy of old devdocs for emacs < 27.1

- core/core-configuration-layer.el
I had the problem described in https://github.com/syl20bnr/spacemacs/issues/14820
During a package update on an emacs 26, the devdocs package failed to install an updated version because it now requires emacs 27.1. This prompted me to do a package rollback.
Upon package rollback, spacemacs tried to uninstall the current devdocs package in preparation for restoring the old devdocs package. Since the new package devdocs isn't installed at all, the deletion failed, and with it the whole rollback.
The changes in this PR allow the rollback to continue by having package-delete not fail hard, but instead just output a message.
> Lenient pkg delete

- CHANGELOG.develop
- layers/+source-control/git/funcs.el
- layers/+source-control/git/packages.el
As described in #9169, when using the emacs editing style the comment inserted at the bottom of a git rebase shows the incorrect key bindings. This is apparently due to `evil-collection` [changing the `git-rebase-mode-hook`](https://github.com/emacs-evil/evil-collection/blob/3ed92cadda7ff1c2d9bc43ec2352e5b02d9e6477/modes/magit/evil-collection-magit.el#L523-L524).
We can fix the issue by only loading `evil-collection` if we're using an evil-style editing mode.
> [git] Only load evil-collection in vim or hybrid mode

- layers/+source-control/git/packages.el
funcs.el is loaded after packages.el so `spacemacs//support-evilified-buffer-p` is undefined at this point.
moved it inside the `defun` block and it should work.
> fixup fixup fixup #14715

- doc/DOCUMENTATION.org
The link that this commit fixes does not exist in the master branch FAQ
documentation.
> [doc] Fix broken link

- layers/+os/nixos/packages.el
Add key binding `, = =` (nix-format-buffer) in nix-mode buffers.
> [nix] Add key binding for nix-format-buffer

- doc/BEGINNERS_TUTORIAL.org
- doc/DOCUMENTATION.org
Fix some small typos found in the documentation.
Do note, I am not a native English speaker so apologies for possible
obvious mistakes.
> Fix some typos

- CHANGELOG.develop
- layers/+tools/transmission/README.org
- layers/+tools/transmission/packages.el
This commit adds 3 sets of keybindings and organises the keybindings so that it can be read easier.
1. Marking and labelling
=SPC m t m= marks a torrent and =SPC m s l= sets the labels for marked torrents. The old command bound to =SPC m s l=, =transmission-set-ratio=, is bound to =SPC m s r= instead.
2. Queueing
Keybindings under a new prefix are added to ~transmission-mode~ to manipulate how the torrents are queued. A keybinding to sort logically by columns is also added.
3. Turtle mode
A new keybinding while in =transmission-mode= toggles the =transmission-turtle-mode= minor mode. When it is active, a new set of 3 keybindings will be active to change the settings of the minor mode. The bindings used are uppercase letters since there are already defined bindings using the lowercases. …
> [transmission] Add new keybindings

- layers/+lang/python/README.org
Fix the keybindings used for `pyvenv` in the README file. The corresponding
lines in `packages.el` are lines [323](https://github.com/syl20bnr/spacemacs/blob/2fd3eb3edbc7c09b825892ce53721120bb999504/layers/%2Blang/python/packages.el#L322)--[325](https://github.com/syl20bnr/spacemacs/blob/2fd3eb3edbc7c09b825892ce53721120bb999504/layers/%2Blang/python/packages.el#L325).
> [python] Fix keybinding in README

- layers/+emacs/org/packages.el
Adding `org-habit` to `org-modules` under `(with-eval-after-load 'org-agenda)` in `init-org`
will not properly load it as a module unless `org-agenda` is started before `org`.
Below are some photos of how the issue happens. I have managed to reproduce it on an Arch and Ubuntu distribution with a stock Spacemacs setup.
Starting `org-agenda` right when Emacs is launched, the `org-habit` graph is displayed just fine. `org-habit` is also seen to be added as a module just fine.
However, starting an Org file first, the `org-habit` graph no longer appears in the agenda tab even though it appears to be added as a module.
The fix that I have made in this commit is to move the appending of `org-habit` to `org-modules` from right after initialising `org` to after initialising `org-agenda`. The …
> [org] Fix org-habit

- layers/+source-control/git/packages.el
- layers/+spacemacs/spacemacs-defaults/funcs.el
- layers/+spacemacs/spacemacs-defaults/packages.el
Fixes: Error at init time after updating which-key package #14865
This reverts commit ec57b21a924d88fa0f7e1d747f091c349cca0170.
A which-key change caused issues with this fix.
And the fix doesn't seem to be needed anymore.
The correct which-key entries appear without the fix.
> Revert "Fix which-key entries: gr and gs in dired and magit"

- layers/+spacemacs/spacemacs-navigation/packages.el
problem:
The symbol highlight exit function is never called,
after the keyword: `:before-exit`
in the definition of the symbol-highlight transient state (TS).
cause:
The TS definition gets the exit function with the keyword: `:on-exit`
Then it assigns that exit function to the hydra with the keyword: `:before-exit`
That's where the confusion came from.
> Fix exit keyword in symbol-highlight TS

- CHANGELOG.develop
- layers/+tools/shell/README.org
- layers/+tools/shell/funcs.el
- layers/+tools/shell/packages.el
Hi there! Here's a patch to add a new function, `spacemacs/projectile-shell`, which creates a buffer with the default shell and switches to it. It behaves similarly to `projectile-multi-term-in-root` which was previously bound to `SPC p $ t`, and this function is more general, so I gave it leader keys `SPC p $`.
> Adds function to run default shell in project root, with leader keys `SPC p $`

- .circleci/apply_patch
- .circleci/built_in/maybe_pr
- .circleci/org/maybe_pr
- .circleci/push
Seems like white spaces can trip patching process. Lets see if this fixes the problem.
Also add a couple of `cd` instructions to make sure that the expected directory won't change.
> [ci] fix ws in patches and use git apply

- layers/+spacemacs/spacemacs-navigation/funcs.el
- layers/+spacemacs/spacemacs-navigation/packages.el
Fixes: How to disable auto highlighting of all matching words #14880
Recent updates to the `auto-highlight-symbol` package,
broke the Spacemacs configurations for the package.
Problems:
- The symbols under the cursor gets highlighted on startup.
- The highlight isn't cleared when the Symbol Highlight Transient State is closed.
- The `SPC t h a` symbol highlighting toggle, shows the same message every time:
`automatic-symbol-highlight disabled.`
but the symbols are still being highlighted.
This PR fixes these issues above, but there are some issues with the toggling (see below).
There might be more issues, according to this upstream comment:
https://github.com/jcs-elpa/auto-highlight-symbol/issues/7#issuecomment-873092710
>iedit, isearch, and symbol-overlay is no longer working as expected …
> Fix symbol highlighting

- layers/+spacemacs/spacemacs-navigation/funcs.el
problem
navigating to the next/prev symbol,
in the symbol highlight transient state: `SPC s h`
with: `n`, `N` or `p`
soft freezes Emacs (the freeze can be canceled with `C-g` twice)
cause
the upstream variable: `ahs-current-overlay` has been removed
solution
it was replaced with a function called: `ahs-current-overlay-window`
> Fix symbol highlight ts, infinite loop

- layers/+spacemacs/spacemacs-navigation/funcs.el
- layers/+spacemacs/spacemacs-navigation/packages.el
problem
The Symbol Highlight Transient State (`SPC s h`) counter
ex: [2/7]
Shows: [0/0]
when opening the TS, either with `SPC s h`, `SPC s H`
or when navigating between symbols with: `#` or `*`
cause
The symbols haven't been counted yet, when the TS is opened.
And the counter is reset when `auto-highlight-symbol-mode` is disabled,
this happens when the TS is restarted, which happens when navigating to the
next/previous symbol with `#` and `*`.
solution
Highlight the symbol before opening the TS.
And only disable `auto-highlight-symbol-mode` when the TS is closed.
(when the TS buffer `" *LV*"` doesn't exist)
notes
This also shows the "No previously searched for symbol found" message,
when the variable `spacemacs-last-ahs-highlight-p` is void on startup.
> Fix symbol highlight ts counter

- layers/+emacs/org/README.org
- layers/+emacs/org/config.el
- layers/+emacs/org/packages.el
Make org-brain optional using `org-enable-org-brain-support` flag
This is similar to what we have for other packages. 
Reason for this change:
- Give a choice for users who don't use `org-brain`
> [org-mode]/[org-brain] Add flag to enable org-brain support making it optional

- layers/+lang/html/packages.el
problem
With the cursor on a parenthesis in js code in a .html document,
pressing:
```
%                      ;; evilmi-jump-items
```
jumps to the buffers last line.
solution from upstream issue
Jump to end when current line has a "if" keyword in web-mode and html-mode
https://github.com/redguardtoo/evil-matchit/issues/119
> Fix evil-matchit % jump in web mode

- CHANGELOG.develop
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
Fixes #14929
The main org-roam command "org-roam-find-file" was replaced with "org-roam-node-find". I decided to leave 
the old key sequence "a o r f" as an alternative for the new command alongside "a o r n" so that people who don't care about the internal naming of org-roam objects could keep using their muscle memory.
> Rename commands for org-roam v2 compatibility

- core/templates/.spacemacs.template
Fix some typos and also change the few instances of "non nil" to
"non-nil", so as to be consistent with the rest of the file.
> Fix typos in .spacemacs.template

- core/core-env.el
Currently, when running the env shell-command, Emacs does so using its current
`process-environment`. Instead, we should run the command with the
`initial-environment`, which seems to fix issue #14919 (at least on GNU/linux).
> fix issue #14919 (force-init-spacemacs-env fails)

- layers/+spacemacs/spacemacs-defaults/funcs.el
When providing only the new directory path (i.e. without new filename) while
moving a file to a new directory with `spacemacs/rename-current-buffer-file`,
Spacemacs currently opens the file in a new buffer with the directory name.
Additionally, the `file-renamed-p` gets set to the wrong value. To fix both
issues (with minimal work), it is easiest to just fix the `new-name`
value (alternatively fixing the `rename-buffer` and `set-visited-file-name`
forms later would not fix the wrong `file-renamed-p` value issue).
Finally when called with a universal-argument, then that argument unintended gets 
'passed' in the interactive call to `projectile-invalidate-cache`. So this PR fixes that by changing
the interactive call to a `funcall`.
> Fix wrong buffer name after file rename

- CHANGELOG.develop
- doc/DOCUMENTATION.org
- layers/+spacemacs/spacemacs-defaults/funcs.el
- layers/+spacemacs/spacemacs-defaults/packages.el
Toggles are great and all, but the trouble with the various toggles for line
numbers is that they force you to remember and think about the fact that there
are variant forms of line numbers. To beginners or forgetful people the various
combinations of behavior can be unintuitive here (e.g. toggling off relative
line numbers does nothing if you are actual in visual line numbers mode). Though
it doesn't fit exactly into the normal stuff we have for toggles, due to the
complexity of this situation I think it is good to just have a way to say "line
numbers be gone!"
Wasn't sure what keybinding to use, so used a double-tap mnemonic.
If this PR gets rejected, there are a couple minor fixes that should probably be
pulled out and submitted separately.
> [defaults] Disable line numbers with `SPC t n n`

- layers/+tools/shell/funcs.el
Add instruction for controlling automatic change to working directory ('fixes' #14947)
> Improve spacemacs/default-pop-shell docstring

- layers/+spacemacs/spacemacs-language/packages.el
This bug exists already since I started using Spacemacs about 1.5 year ago.
Because it was already reported upstreaim in
[this issue](https://github.com/atykhonov/google-translate/issues/52), I
implemented this fix only locally.
> Fix google-translate functionality (',tkk' search fails)

- layers/+lang/python/README.org
- layers/+lang/python/funcs.el
- layers/+lang/python/packages.el
Currently when using any python-send-shell command (using either the python or ipython shell),
the output of the evaluation is not shown in the comint shell (see Emacs bug#49822).
This commit adds a simple function to send input and get the output printed in the comint process buffer.
> Add python-send-shell-with-output command

- CHANGELOG.develop
- layers/+email/notmuch/README.org
- layers/+email/notmuch/packages.el
In standard notmuch-emacs, one can scroll back and forth the message
pane using `SPC`/`BKSPC`. Obviously, this is not the case in Spacemacs,
where `SPC` is reserved. There was no way to scroll the message pane in
this layer, so I added `M-d` and `M-u` wired to
`notmuch-tree-scroll-message-window` and
`notmuch-tree-scroll-message-window-back`.
> Add bindings for scrolling the message pane in tree-view

- layers/+spacemacs/spacemacs-navigation/funcs.el
problem
opening a prompt, ex: `M-x`
while the Symbol Highlight Transient State (`SPC s h`) is open,
leaves `auto-highlight-symbol-mode` enabled
cause
when the idle timer runs,
it tries to disable ahs mode in the prompt window
> Fix ahs ts, open prompt

- layers/+tools/lsp/README.org
Fixes #14985 
I'm not sure why the described manipulations were necessary before. However, the blacklisting mechanism in LSP was since overhauled, and the user is now prompted for consent when first importing a project, with an option to effectively blacklist it. No variable customization is necessary, so I've deleted the whole paragraph.
> Remove obsolete paragraph from the LSP layer documentation

- layers/+readers/pdf/README.org
- layers/+readers/pdf/packages.el
Currently there is no keybinding to fold the outline of a pdf. So let's replace
show-all because it is easier to remember a single keybinding for folding and
unfolding then having separate bindings for those (and consistent with
org-mode's global cycle keybinding)
> Change show-all keybinding to outline-cycle-buffer in pdf layer

- layers/+lang/major-modes/packages.el
If `evil-matchit` is available, configure it for use in `matlab-mode`.
Note: A [PR was recently accepted](https://github.com/redguardtoo/evil-matchit/pull/134) for `evil-matchit` to add support for `matlab-mode`
> [major-modes] add evil-matchit support for matlab

- CHANGELOG.develop
- layers/+lang/erlang/README.org
- layers/+lang/erlang/funcs.el
- layers/+lang/erlang/packages.el
Adding support to erlang to debug using DAP.
It requires you to add `dap` layer to your `dotspacemacs-configuration-layers` (which will requires you to also add `lsp` layer).
Regarding the project, you will need to add a `launch.json` configuration to the project's root directory as explained in this [debugger-tutorial](https://erlang-ls.github.io/articles/tutorial-debugger/)
> [erlang] add DAP support through erlang_ls-dap

- layers/+spacemacs/spacemacs-navigation/funcs.el
problem
`SPC f J` (`spacemacs/open-junk-file`) shows:
cond: Cannot open load file: No such file or directory, helm
cause
`spacemacs/open-junk-file`
expects the completion layer to be either: `helm` or `ivy`
notes
The junk file function searches through the junk files,
when the ARG parameter is non-nil
(when it's called with a prefix argument: `SPC u SPC f J`)
The helm and ivy search functions might be choosing the search tool,
based on the first search tool it finds in the variable:
`dotspacemacs-search-tools`
`("rg" "ag" "pt" "ack" "grep")`
The consult package has these two search functions:
`consult-grep`
`consult-ripgrep`
This fix only uses those two for searching.
It checks for the executable: `rg` before `grep`
> [compleseus] Fix junk file function

- layers/+completion/compleseus/funcs.el
- layers/+completion/compleseus/packages.el
problem
- `SPC h d a` is undefined
- `SPC ?` shows: SPC ?-  which-key: There are no keys to show
- `SPC f b` calls: `bookmark-jump`. Setting a bookmark, requires typing the
bookmark name and calling an embark action:
M-o                    ;; embark-act
s                      ;; bookmark-set
- `SPC f f` is bound to `find-file` but it calls `ido-find-file`
solution
- `SPC h d a` `consult-apropos`
- `SPC ?` `embark-bindings`
- `SPC f b` `consult-bookmark`, it allows for jumping to a bookmark
(just like `bookmark-jump`), but a bookmark can be set by just typing a new
name. If there is a bookmark with a similar name, then the selection can be
moved up to the prompt. (the embark action method also works here)
- `SPC f f` `spacemacs/compleseus-find-file` (it calls `find-file`)
> [compleseus] Fix keys

- layers/+distributions/spacemacs-bootstrap/funcs.el
- layers/+distributions/spacemacs-bootstrap/packages.el
problem
Evil search bug breaks Spacemacs #10410
https://github.com/syl20bnr/spacemacs/issues/10410
Multiple evil bindings break:
when a evil search prompt is active: / or ?
and a window is selected with the mouse.
notes
This fix can be removed when/if the pending upstream PR is merged:
Exit search prompt on mouse leave minibuffer
https://github.com/emacs-evil/evil/pull/1330
> Fix evil search prompt on mouse leave

- layers/+spacemacs/spacemacs-defaults/funcs.el
When the buffer's name is uniquified (because multiple buffers have
the same short name), it is no longer equal to the basename of the
buffer's file name, so it is incorrect to use the buffer name in the
rename operation.
> Fix file rename target path when buffer name is uniquified

- layers/+distributions/spacemacs-bootstrap/packages.el
Due to the `org-roam v2` warning buffer, I realized that special modes do not get `evilified` by default.
As I am not aware of any case where this is not desired, I created this PR as a suggestion.
It change should probably get documented also (before getting accepted), but I would be happy to fix that.
As special-mode is a read-only mode, it could be evilified by default.
I am not aware of any case where this is not desired.
Closes #14988
> Evilify special-mode by default

- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
This matches the org-agenda key, and is doubly important since we need to
refresh regularly to workaround the page-break-lines bug, as described here
https://github.com/syl20bnr/spacemacs/issues/14969#issuecomment-894624932
> [org-roam] Add "r" key to refresh org-roam links list buffer

- layers/+lang/latex/README.org
- Corrects typos, mainly extra apostrophes.
- Adds a clarifying paragraph on `TeX-engine` and  `TeX-command-master`.
Closes #14978
> [latex] Doc. TeX engine. Corrects typos, adds on TeX-command-master.

- layers/+spacemacs/spacemacs-navigation/README.org
- layers/+spacemacs/spacemacs-navigation/packages.el
This PR is just a suggestion, because I personally frequently like to use this functionality (have it under `SPC h M`).
Of course, you are free to dismiss it...
This keybinding could also go under `SPC h M`, but that is currently taken by
`helm-switch-major-mode` (which seems a quite redundant command to me, as you
can switch major-modes directly using `M-x`/`SPC SPC`).
> Add jump to specific manual keybinding (SPC h j)

- README.md
problem:
The clone command doesn't work in Windows:
`git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`
It creates a `~` directory in: `C:\Users\username`
that contains: `.emacs.d`
But Emacs looks for `.emacs.d` in: `C:\Users\username\AppData\Roaming`
solution:
Add instructions for cloning to the Roaming directory.
In a Command Prompt:
`git clone -b develop https://github.com/syl20bnr/spacemacs %appdata%/.emacs.d`
In a Windows PowerShell prompt:
`git clone -b develop https://github.com/syl20bnr/spacemacs $env:appdata/.emacs.d`
> [docs] Update readme, Windows clone path

- CHANGELOG.develop
- layers/+completion/ivy/README.org
- layers/+completion/ivy/config.el
- layers/+completion/ivy/packages.el
This PR adds an option to configure =all-the-icons-ivy-rich=.
I am not sure if I should add extra logic to make sure that the various required modes get activated in the right order as instructed in [these notes](https://github.com/seagle0128/all-the-icons-ivy-rich#use-package).
Currently, the `all-the-icons-ivy-rich-mode` seems to get activated before `ivy-rich-mode` as instructed in the third point of the notes.
It all seems to work fine (also, I think it will not break anything if activated in the wrong order, just it will not work correctly).
> Add option to enable all-the-icons-ivy-rich to ivy layer

- layers/+emacs/org/packages.el
When we're adding links, without this they get smooshed together under the
curser. Tested to work; resolves https://github.com/syl20bnr/spacemacs/issues/14137
> [org-roam] Fix evil org-roam-node-insert spacing

- layers/+lang/clojure/packages.el
Cider provides the possibility to search the REPL history, for which it opens
the history in a read-only buffer (which as usual is initialized in evilified
state).
This commit evilifies the cider-repl-history-mode buffer and defines some common
sense cider-repl-history-mode keybindings.
> Evilify and add cider-repl-history-mode keybindings

- layers/+lang/shell-scripts/README.org
- layers/+lang/shell-scripts/packages.el
#14966 added format-on-save for shell scripts but I forgot to add a key binding for manually triggering reformatting.
> [shell-scripts] Add key binding for shfmt-buffer

- CHANGELOG.develop
- layers/+tools/lsp/README.org
- layers/+tools/lsp/funcs.el
This has been in `lsp-mode` for ages, we just need to expose the keybinding.
I also removed a misleading readme segment that seemed to imply there was a group of bindings relating to call/method hierarchies, which there isn't.
> lsp: add call hierarchy binding

- CHANGELOG.develop
- layers/+lang/ocaml/funcs.el
As of OPAM v2.1, `opam config var share` is no longer supported. Instead, the syntax is `opam var share`. To allow both, this checks first with the new syntax, then if that doesn't work, the old is tried. If neither produce any output, it fails as normal.
This should resolve syl20bnr/spacemacs#14392 .
P.S. I'm pretty new to Elisp so criticism, constructive or otherwise is appreciated!
> ocaml: Allow new OPAM command-line syntax

- layers/+lang/c-c++/packages.el
A renaming from `c++-organize-includes` to `c-c++-organize-includes` was done a while ago: https://github.com/syl20bnr/spacemacs/commit/a4eadc97fecaa4f7c5776d24c8ec55379fbc876e
But one keybinding still binds to the old function name. This PR fixes it.
> [c-c++]: Fix keybinding for organizing includes

- layers/+distributions/spacemacs-bootstrap/funcs.el
- layers/+distributions/spacemacs-bootstrap/packages.el
Reverts syl20bnr/spacemacs#15002
reverting since it's fixed upstream https://github.com/emacs-evil/evil/pull/1330
> Revert "Fix evil search prompt on mouse leave"

- layers/+lang/c-c++/packages.el
The package `cpp-auto-include` is now [in Melpa](https://melpa.org/#/cpp-auto-include) so it doesn't need to be fetched from GitHub (and the github repo it points to redirects now anyway).
> c-c++: Package cpp-auto-include can be fetched from Melpa

- README.md
The --with-default-names option seems to no longer exist. A directory have to be added to PATH instead.
> README: fix macOS prerequisites regarding grep

- layers/+lang/bibtex/packages.el
See https://github.com/joostkremers/ebib/issues/213
By remapping `spacemacs/kill-buffer` to `ebib-quit` ebib is generally exited 'correctly' (if users really want to kill the buffer and mess up things, they can still do that in plenty of other ways).
> Add simple workaround to ebib kill buffer issue

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-defaults/funcs.el
This PR implements an alternative for PR #8974.
> Extend spacemacs/copy-file command with extra actions

- layers/+fun/emoji/README.org
- layers/+fun/emoji/funcs.el
- layers/+fun/emoji/packages.el
Currently company-emoji does not get activated by the emoji layer.
Also when it is activated, then the emoji short-name does not get completed to
unicode if `company-emoji-insert-unicode` is `t`.
This PR fixes both issues, by activating company-emoji for text-mode and
advising the emoji insert function to optionally do company-emoji completion
(try e.g. in magit-commit buffers).
> Fix (activate) company-emoji completion

- layers/+lang/python/README.org
- layers/+lang/python/packages.el
Currently the python layer (without anaconda backend) provides only helm-pydoc
or pylookup-lookup-at-point functionality. Both these functions are cumbersome.
`pydoc-at-point-no-jedi` adds simpler doc functionality, therefore this commit
adds this command as a third option. It places it under `SPC m h p` because `SPC
m h h` is already taken by the anaconda doc functionality (it could be placed on
`h h` if anaconda is not available, but I did not bother to implement it)
EXAMPLE:
see [question at stack-overflow](https://emacs.stackexchange.com/questions/66803/how-can-i-access-the-python-documentation-for-the-thing-at-cursor/68707#68707)
Now try to answer it. You will probably agree that this provides the simplest/best solution.
Although both `helm-pydoc` and `pylookup-lookup-at-point` are …
> Add pydoc to python layer for better python doc functionality

- CHANGELOG.develop
- core/core-configuration-layer.el
- tests/core/core-configuration-layer-utest.el
Hi,
This PR is try to fix the errors when `*.el` file is compiled to `*.elc` and compressed to `*.el.gz` for distributing Spacemacs (like vallina Emacs, with `*.elc` and `*.el.gz`).
You can byte-compile the `layers/+distributions/spacemacs-base/` folder to get the `*.elc` files and compress the `*.el` to `*.el.gz`, then restarting Spacemacs to get issues.
> [core] fix errors for packing elisp to *.elc and *.el.gz files

- CHANGELOG.develop
- layers/+source-control/github/README.org
- layers/+source-control/github/packages.el
This doesn't remove but comments out gist.el  and associated README.org docs in the hopes it gets picked up again.
Fixes #15093
> Remove gist.el since it's unmaintained

- layers/+lang/latex/README.org
There was a sneaky `200b` character (zero width space), which breaks the display on the website:
The character is not visible in Github diff but can be seen by using an editor that displays those (e.g. Vim):
> LaTeX: Fix broken key binding

- doc/VIMUSERS.org
I was going through the documentation and noticed the keybinding listed to 'Kill all buffers except the buffer' actually opens the message buffer. This changes that to the correct binding as well as correcting the keybinding listed for 'Kill buffers using a regular expression'
> [doc] fix incorrect key bindings for buffer functions

- layers/+source-control/git/packages.el
fixes https://github.com/syl20bnr/spacemacs/issues/15111
> git: migrate git{attributes,config,ignore}-mode to git-modes

- layers/+source-control/git/README.org
- layers/+source-control/git/packages.el
- layers/LAYERS.org
Related to #15117, this removes the helm-gitignore from the git layer because it
hasn't been updated to use the new git-modes package. The helm-gitignore
functionality isn't particularly useful anyway, it's just a utility to help
generate .gitignore files.
This change can be reverted if the upstream helm-gitignore package is fixed and
people find the functionality it provides to be useful.
> [git] Remove helm-gitignore from git layer

- layers/+completion/helm/funcs.el
Calling spacemacs/helm-find-files with prefix would cause an error
instead of popping helm-find-files-history before helm-find-files
> helm-find-files-history requires prefix argument

- CHANGELOG.develop
- doc/CONVENTIONS.org
- doc/DOCUMENTATION.org
- layers/+distributions/spacemacs-bootstrap/packages.el
Special mode and its derived mode(s) buffers were made evilified in PRs #14995
and #15050. However, special-mode is too aggressive (as 'warned' for already in
#14995); it makes it hard to overwrite its keybindings (e.g. `evil-local-set-key`,
or using `evil-evilified-state-map` on a derived map have no effect).
Therefore it makes more sense to open the buffers in motion-state instead. This
state also does not hijack the `q` keybindings as defined by special-mode (see
https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html),
although it does still hijack its `g` keybinding, but evil navigation is
considered to have higher priority than revert-buffer anyway.
> Open special-mode buffer in motion-state (not evilified)

- layers/+lang/python/README.org
It turns out that we've already migrated to pylsp from pyls a while ago, except that README.org is not updated.
closes https://github.com/syl20bnr/spacemacs/issues/15036
> python: Update README.org

- layers/+themes/themes-megapack/packages.el
The documentation of the `themes-megapack` layer states that the layer provides
all themes included in the [theme gallery](https://themegallery.robdor.com/) by
Rob Merrell. However, this theme currently is missing from the layer.
> Add zonokai themes to themes-megapack layer

- layers/+completion/compleseus/README.org
- layers/+completion/compleseus/funcs.el
- layers/+completion/compleseus/packages.el
- layers/+tools/fasd/packages.el
This PR adds two (default) keybindings to compleseus layer, i.e. consult-locate on `SPC f L` and consult-yasnippet on `SPC i s`.
Furthermore, it adds an embark action to start a grep search from a candidate its path's directory.
@thanhvg Please review/approve if you agree. The PR is just a proposal.
> Add commands to compleseus layer (locate, yasnippet, search from)

- .lock
- core/core-configuration-layer.el
- core/info/release-notes/0.300.txt
- doc/FAQ.org
- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
- tests/core/core-configuration-layer-utest.el
From org version 9.5 org will not be distributed from Org ELPA but from
ELPA (see https://list.orgmode.org/87lfa7tc9v.fsf@gnu.org/t/). This commit makes
Spacemacs use/install org from ELPA.
Besides that, this commit removes some 'hack' that seemed to have no effect. As
org comes with Emacs `package-installed-p 'org` will always return t. Also
activating org via `configuration-layer//activate-package` seems to have no
effect.
Finally, the package is declared including a :min-version because appending only
`:location melpa` seems to have no effect (this can probably be considered a
bug).
I am almost certain that the information that was added when making org install
from Org ELPA is still relevant also for installing org from ELPA so I have just
adapted the version number from 0.104 to …
> Install org from ELPA instead of Org ELPA

- core/core-keybindings.el
- layers/+distributions/spacemacs-bootstrap/packages.el
Fixes #15075
I know *new* stuff is supposed to go to develop, but this is more of a release-branch hot-fix type of thing?
> Use non-deprecated which-key equivalents

- layers/+completion/compleseus/packages.el
- set completion-styles '(basic partial-completion orderless) currently it is '(orderless) which is ridiculous in how it suggests company results. 
- enable consult for doing tab in `M-:`
> [compleseus] tuned completion-style and added support for M-:

- CHANGELOG.develop
- core/core-configuration-layer.el
Due to a question by @pataquets just now on gitter, I have added an option to select packages for installation.
I've tested it, and it seems to work perfectly fine, incl. the rollback(s). I prefer the `read-answer` solution, but of course
we could make it a `completing-read` also.
The diff looks a little strange b.t.w., because it shows many 'removed/red' hunks, that I did not remove at all (so those parts appear in 'green' further below).
BELOW IS THE COMMIT MESSAGE
This commit changes the yes-or-no-p to a read-answer with three options y, s and
n (for yes, some and no. This of course could be a, s, c for 'all',
'some/select' and 'cancel', but I decided to keep yes no as users are already
familiar with the y and n).
Finally the user can select packages by answer for each package in the …
> Add option to select packages for update

- layers/+emacs/org/README.org
Hopefully this help beginners to know what to do (as this [example on reddit](https://www.reddit.com/r/spacemacs/comments/qsj8uw/org_agenda_and_notifications/)).
I also made a small accessibility change to a "here" hyperlink with a more descriptive one in the same paragraph. (Read [more information about what's wrong with click "here" links](https://webaccess.berkeley.edu/ask-pecan/click-here).)
> Don't forget to update CHANGELOG.develop if you want to be mentioned in the release file!
I don't believe this small change requires a changelog entry.
> [doc] org: adds example on how to set an alert style for org notifications

- .circleci/web/htmlize
- core/core-documentation.el
Apparently this directory must be present before the export function is called :thinking:
> [ci] pre-create the missing dir

- core/core-documentation.el
This way if the div changes we'll get more informative error message, at least :shipit:
> [ci] better error handling in html export

- CHANGELOG.develop
- layers/+lang/scala/README.org
- layers/+lang/scala/funcs.el
- layers/+lang/scala/packages.el
It's nice to have a way to use common SBT commands without having to enter a
Hydra, and without having to type them out or select from a history list. The
following should be standard and quite common:
+ `scalafmtAll`
+ `compile`
+ `test`
Added mnemonic keybindings that I think match Spacemacs conventions. They
behaviors also give better parity with the build capabilities of other major
modes, which frequently support compile, format and test functionality.
> [scala] Shortcut keys for common/standard SBT commands

- CHANGELOG.develop
- layers/+tools/lsp/README.org
- layers/+tools/lsp/funcs.el
Straightforward change: Add a keybinding for lsp-treemacs-type-hierarchy: `SPC m g T`.
> Add a keybinding for lsp-treemacs-type-hierarchy

- layers/+completion/auto-completion/packages.el
The auto-completion layer seems not to have been designed/configured correctly.
So that, e.g., when using the julia layer, the `auto-completion/init-yasnippet`
function is called after the `yasnippet-snippets` package has been loaded.
Despite the `yasnippet-snippets` package containing an `eval-after-load
'yasnippet`, the form within that block is, for some reason, evaluated already
before `auto-completion/init-yasnippet` has been called.
Anyway, what happens currently is that first `(yasnippet-snippets-initialize)`
is evaluated, adding `yasnippet-snippets-dir` to the `yas-snippet-dirs` list.
Then `auto-completion/init-yasnippet` is called which contains the line `(setq
yas-snippet-dirs nil)`, setting the list to nil again.
As there is quite some logic involved (e.g. the order of …
> Fix #15169, snippets not loading correctly

- layers/+spacemacs/spacemacs-layouts/funcs.el
Fixed small typos!
`accross` -> `across`
`perp` -> `persp`
I've checked to make sure there are no other same typos.
> Fix small typos

- layers/+emacs/org/README.org
Some primary commands in org-mode are for sure `org-meta-return` and
`org-metaleft/right`. However, documentation for their shortcuts is lacking.
Additionally, using org-babel without `yasnippets` is self-torture, therefore
when using org-babel the keybinding for inserting yasnippets is highly relevant.
This commits adds documentation for these shortcuts.
> Add documentation for most important org shortcuts

- layers/+lang/coq/README.org
Due to some question on gitter.
Currently, it is not clear that the auto-completion layer is required for
company-coq to work. This commit fixes that.
> Coq layer README add optional requirement (auto-completion layer)

- layers/+spacemacs/spacemacs-evil/funcs.el
The fix introduced in 23367d08f890873e77fd9a434c9332cf53d5f9df NOPs evil-redirect-digit-argument. As a result, pressing 0 while in iedit movement state does not jump to the beginning of the match or beginning of line.
This change redefines the functions currently needed by evil-iedit-state while keeping the expected functionality
> Improve temporary fix for evil-redirect-digit-argument

- core/core-configuration-layer.el
I guess this commit should fix issue #15186.
I have quickly tested all interactive options
- option `s`, installing a selection of packages
- option `n`, canceling installation of packages
- option `y`, installing all packages
then tested
- the rollback functionality
and finally tested the non-interactive option
- using `(configuration-layer/update-packages t)`
and all these functionalities seem to work fine now (but I have not tested thoroughly, maybe you could try the different options also after merging the PR, probably best in the same order as listed above). Anyway, I guess this PR can be merged safely...
> Fix #15186, broken package update due to commit cac0105

- layers/+readers/pdf/README.org
- layers/+readers/pdf/packages.el
Follow mode in the pdf-occur buffer is very handy, and deserves a specific
Spacemacs keybinding (mainly for discoverability/documentation, as its name
`next-error-follow-minor-mode`, putting it mildly, is not very intuitive).
> Add pdf occur follow mode spacemacs binding

- layers/+spacemacs/spacemacs-visual/funcs.el
Hi,
This change should enable applying ANSI colors to `dap-java` output buffers, and in general to the output buffer of any mode that derives from `compilation-mode`. 
Cheers,
> Fix #15198: Apply ansi-colors to compilation-mode derived modes

- layers/+spacemacs/spacemacs-visual/funcs.el
The function `parent-mode-list` is not defined by Spacemacs or any of its
dependencies.
#15198 
Signed-off-by: Chris <cwjnkins@gmail.com>
> Replace use of `parent-mode-list` in `spacemacs-visual/funcs.el`

- core/core-configuration-layer.el
See #15212
The selective update functionality uses the function `read-answer` which is not available in Emacs version < 26.2.
Therefore, this PR restores the initial update functionality for Emacs versions < 26.2.
> Fix package update for emacs versions < 26.2 (issue #15212)

- layers/+completion/auto-completion/packages.el
- layers/+lang/julia/packages.el
This reverts commit f2755533deef68cb2fb2a2d40e6a5ab6ede13204.
This adds fix for julia layer breaking yasnippet setup.
Commit f2755533deef68cb2fb2a2d40e6a5ab6ede13204 fixed a specific bug in julia
layer but it loads yasnippet and friends on start up which adds 1 sec to my
startup time even though I don't use julia.
Julia layer loads lsp-julia early on startup, which loads lsp which then loads
yasnippet behind the scene unknown to spacemacs and use-package. That's why our
nice and ordered setup for yasnippet and yasnippet-snippets failed as discussed
in https://github.com/syl20bnr/spacemacs/pull/15171. We now tell use-package to
defer its load.
Note: I didn't do a full test with a julia lsp server. If someone who actually does julia with lsp can verity it that would be great.
> [auto-completion][julia] Revert #15171, Proper fix for #15169

- layers/+completion/compleseus/funcs.el
- layers/+completion/compleseus/packages.el
https://github.com/oantolin/embark/wiki/Additional-Configuration#use-which-key-like-a-key-menu-prompt
embark-act `M-o` menu will be handled by which-key
> [compleseus] integration with which-key

- layers/+lang/latex/packages.el
Remove the call to `spacemacs//latex-setup-pdf-tools` in `latex/init-lsp-latex`
since it is already called in `init-auctex` which is the main package
> [lsp-latex] Fix warning void variable TeX-view-program-selection

- layers/+source-control/version-control/packages.el
The config for git-gutter currently sets custom fringe bitmaps which
are optimized for half-width fringes.
I think that's an arbitrary choice. There's no spacemacs option which
enables half-width fringes and as far as I can tell, we don't optimize
for half-width fringes anywhere else. So we should optimize the
package defaults for the spacemacs default of full-size fringes.
If users set half-width fringes manually, they can customize the
bitmaps manually. Even if they don't, the bitmaps are still visible,
they just don't look as nice.
> git-gutter: Remove custom fringe bitmaps

- layers/+lang/python/funcs.el
Closes #14162 
I fix the problem:
"spacemacs/python-execute-file" can't find the correct python compile path when using virtualenv or pyenv.
> Fix #14162, python-execute-file not using in virtual environment

- layers/+completion/compleseus/funcs.el
- layers/+tools/lsp/config.el
- layers/+tools/lsp/funcs.el
- layers/+tools/lsp/packages.el
lsp-use-upstream-bindings is t so by default spacemacs will use lsp-mode's own binding scheme. 
We should consider to phase our the current manual binding scheme for lsp-mode in future.
Close https://github.com/syl20bnr/spacemacs/issues/15197
> [lsp] add consult-lsp and set lsp-use-upstream-bindings to t

- CHANGELOG.develop
- layers/+misc/tree-sitter/README.org
- layers/+misc/tree-sitter/config.el
- layers/+misc/tree-sitter/packages.el
Closes https://github.com/syl20bnr/spacemacs/issues/14246
In the process of opening this PR I realized there's prior art: https://github.com/syl20bnr/spacemacs/pull/15064. ~But from what I can tell it's a different approach which wouldn't make sense to incorporate here.~
EDIT: On closer inspection I realize #15064 is basically the same approach as this; the main difference is that #15064 would allow the user to turn on `tree-sitter-hl-mode` for specified major modes or globally, whereas this PR only provides the global switch.
> Add basic tree-sitter layer

- core/core-configuration-layer.el
As reported in #15230, upstream has removed `eieio-compat.el`. This means that `defmethod` is removed upstream, which means that Spacemacs is broken when using the latest commit in the upstream Emacs master branch.
I'm not really an expert in `cl` or `eieio` but this seems to fix the issue for me (would love some better code review from someone more knowledgeable though). Changing `defmethod` to `cl-defmethod` in `core-configuration-layer.el` just worked for all lines except one, the specialization of `cfgl-layer-owned-packages` for a `nil` argument on line 217 had to be changed to `null`.
There are a few other people who left thumbs up on #15230 so if anyone else who builds Emacs from upstream master can test this change please let me know if it works for you.
> Change core-configuration-layer.el to not use obsolete defmethod

- layers/+emacs/org/packages.el
Reverts syl20bnr/spacemacs#15008
See https://github.com/syl20bnr/spacemacs/issues/15234
> Revert "[org-roam] Fix evil org-roam-node-insert spacing"

- CHANGELOG.develop
- doc/CONVENTIONS.org
- doc/DOCUMENTATION.org
- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
- layers/+readers/pdf/README.org
- layers/+readers/pdf/packages.el
See motivation in commit messages. I for clarity I have kept the two commits separate. If you agree with these improvements, and you would like me to squash the commits, then just let me know.
So I think `C-o` and `C-i` should consistently be used for jumping 'global' history (or at least using evil-jump functions, I don't think that means 'global' per se) and any other keybindings for jumping 'local' history.
I forgot to provide an example. But just open some pdf in pdf-view, then go to a separate buffer and start jumping to previous locations using `C-o`. I guess you will agree that at least that behavior is quite annoying (I have added those bindings myself, because it was better then the bindings before that, but now I think these are even more logical bindings. In pdf-tools, jumping …
> Add C-o and C-i keybindings to evil-evilified-state-map (and remove from pdf-view-mode-map) 

- layers/+completion/ivy/packages.el
Ivy occur grep mode is a read-only mode that is very similar to ivy-occur mode,
and has one extra keybinding under `w` to change to `wgrep-mode`.
Therefore, instead of starting it normal mode, it should start with the
`overriding-map` similar as how it is done for ivy-occur-mode.
Theoretically (this currently does not work here), this should make the `w` call
`spacemacs/ivy-wgrep-change-to-wgrep-mode` which is perfectly fine.
For some reason, after setting this, my Spacemacs opens ` ivy-occur-grep-mode`
in motion-state (despite it is not derived from `special-mode`, see  #15104`). But
anyway, this fix should work fine, and it is even working fine here with special-mode
(I have no time to debug this irrelevant behavior on my system now).
> Fix keybindings in ivy-occur-grep-mode

- layers/+emacs/helpful/packages.el
- layers/+spacemacs/spacemacs-defaults/packages.el
Currently we set default tab-width to 2, but in Emacs's Elisp source code,
tab-width defaults to 8.
This discrepancy results in bad alignment of Elisp source code in help-mode
and helpful-mode (when helpful layer is enabled).
This commit fixes this problem by setting tab-width to 8 in those buffers.
In addition, when both helpful and ivy are in use, this commit improved
their integration according to helpful's documentation.
> help/helpful: Set tab-width to 8, better integration w/ Ivy

- layers/+lang/markdown/README.org
- layers/+lang/markdown/packages.el
Entirely removed orgtbl from markdown layer since it causes problems.
Users may still manually enable it if they know what they are doing.
fixes #15256
> markdown: remove orgtbl

- layers/+completion/helm/packages.el
- `SPC` needs to be translated with `kbd`, or otherwise its treated as three keys `S P C`.
- Use `dotspacemacs-leader-key` instead of the default `SPC` to allow customization.
> fix messed up keybindings in helm-ag-map

- CHANGELOG.develop
- layers/+lang/clojure/README.org
- layers/+lang/clojure/config.el
- layers/+lang/clojure/packages.el
Add kaocha-runner.el to the Clojure layer to enable running the kaocha test
runner from Emacs Cider
Kaocha runner added to the layer via the `clojure-enable-kaocha-runner` variable
Add key bindings to call Kaocha runner
Resolve  #15267
> [clojure] add kaocha-runner as optional package

- core/core-keybindings.el
- layers/+spacemacs/spacemacs-defaults/keybindings.el
- layers/+spacemacs/spacemacs-evil/packages.el
- make sure `evil-lisp-state` related prefix keys are displayed correctly.
- `which-key-add-keymap-based-replacements` accepts multiple key-def pairs
thus this commit allow `spacemacs/declare-prefix` to accept multiple inputs
too.
> fix evil-lisp-state prefixes & improve related functions

- layers/+intl/keyboard-layout/packages.el
Replaced d and h in evil-org-mode
fixes #15249
> keyboard-layout: Fixes #15249

- layers/+emacs/org/README.org
- layers/+emacs/org/packages.el
There are already bindings for org-cut-subtree and org-copy-subtree; add a
binding for org-paste-subtree so that the user can make use of their freshly cut
or copied subtrees (and automatically paste them in a level-adjusted manner)
> org: add binding for org-paste-subtree

- core/core-spacemacs-buffer.el
If `dotspacemacs-startup-lists` contains `recents`, it shows recently opened
files.
This commit will hide any file if it's in `org-directory` or if it is one of
`org-agenda-files`.
fixes #15305
> core-spacemacs-buffer: remoe org (agenda) files from recent files

- layers/+checkers/spell-checking/packages.el
- layers/+completion/auto-completion/packages.el
- layers/+distributions/spacemacs-bootstrap/packages.el
- layers/+emacs/org/packages.el
- layers/+emacs/outshine/packages.el
- layers/+fun/games/packages.el
- layers/+misc/multiple-cursors/packages.el
- layers/+music/pianobar/packages.el
- layers/+music/spotify/packages.el
- layers/+pair-programming/floobits/funcs.el
- layers/+pair-programming/floobits/packages.el
- layers/+readers/deft/funcs.el
- layers/+readers/deft/packages.el
- layers/+source-control/git/packages.el
- layers/+source-control/github/packages.el
- layers/+source-control/perforce/packages.el
- layers/+spacemacs/spacemacs-defaults/packages.el
- layers/+spacemacs/spacemacs-editing/packages.el
- layers/+spacemacs/spacemacs-layouts/packages.el
- layers/+themes/colors/packages.el
- layers/+tools/dap/packages.el
- layers/+tools/eaf/packages.el
- layers/+tools/geolocation/packages.el
- layers/+tools/pandoc/packages.el
- layers/+tools/pass/packages.el
- layers/+tools/quickurl/packages.el
- layers/+tools/ranger/packages.el
- layers/+tools/vagrant/packages.el
- layers/+web-services/evernote/packages.el
- layers/+web-services/streamlink/packages.el
- Updated usage of `spacemacs/declare-prefix`, which
supports multiple pairs of replacements now.
- Replaced `setq` by `defconst` when declaring a layers'
package list.
- Some other minor changes.
> update spacemacs/declare-prefix usages

- layers/+emacs/tabs/README.org
- layers/+emacs/tabs/config.el
- layers/+emacs/tabs/funcs.el
- layers/+emacs/tabs/packages.el
- Replaced tab movement commands key bindings with
vim-style bindings:
- <kbd>g t</kbd>/<kbd>g T</kbd> for going to next/previous tab
(instead of <kbd>Ctrl-{</kbd>/<kbd>Ctrl-}</kbd>)
- <kbd>g Ctrl-t</kbd>/<kbd>g Ctrl-T</kbd> for moving current
tab to right/left
(instead of <kbd>Ctrl-Meta-{</kbd>/<kbd>Ctrl-Meta-}</kbd>)
- Removed unused layer variables from config.el
- Improved documentation in README.org
- Added header in funcs.el
> tabs: Rework

- layers/+completion/compleseus/funcs.el
- layers/+completion/ivy/funcs.el
things like `C++` will be quoted as `C\+\+` and search will produce desired result
> [compleseus][ivy] quote regex when search for region or symbol at point

- layers/+completion/compleseus/packages.el
consult--source-file has been renamed/deprecated. It is now called
consult--source-recent-file.
See https://github.com/minad/consult/issues/508.
> Fix consult-buffer error

- layers/+completion/compleseus/packages.el
consult--source-project-file has also been renamed/deprecated. It is now called consult--source-project-recent-file.
> Fix the use of consult--source-project-file

- layers/+spacemacs/spacemacs-defaults/config.el
- layers/+spacemacs/spacemacs-defaults/funcs.el
Added a new `kill-buffer-hook` that prompt the user to save a buffer
before killing it.
closes #12857
> spacemacs-defaults: Added prompt to save a buffer

- layers/+web/eww/config.el
- layers/+web/eww/funcs.el
- layers/+web/eww/packages.el
- Moved nested functions out
- Moved variables declarations to config.el
- Moved transient state bindings for `textfrag`, `writeroom-mode`,
and `zoom-frm` to their respective `post-ini` functions.
Signed-off-by: Lucius Hu <lebensterben@users.noreply.github.com>
> eww: cleaned up

- layers/+spacemacs/spacemacs-evil/funcs.el
- layers/+spacemacs/spacemacs-evil/packages.el
Revert "Improve temporary fix for evil-redirect-digit-argument"
This reverts commit d3071ae37bbd3a527e3ad429d6f0e8f9bfd8c980.
Revert "Add temporary fix for `evil-redirect-digit-argument` error"
This reverts commit 23367d08f890873e77fd9a434c9332cf53d5f9df.
The change for the original iedit is so tiny but sadly the owner never has time to merge it. We should use the fork for now instead of all the dirty hacks we put on us.
> [iedit] use fork

- CHANGELOG.develop
- layers/+os/nixos/README.org
- layers/+os/nixos/funcs.el
- layers/+os/nixos/layers.el
- layers/+os/nixos/packages.el
Add support for rnix-lsp. This is still largely experimental,
so it remains opt-in even if the LSP layer is enabled.
> Add basic LSP support to NixOS layer

- layers/+spacemacs/spacemacs-purpose/README.org
Just a small rephasing to the sentence which I hope makes it eaiser to read.
```diff 
- Layers can allocated buffers, which have been created by their packages, to certain purposes.
+ Layers can assign purposes to buffers that have been created by their packages.
```
> spacemacs-purpose: Improved README.org

- layers/+readers/pdf/packages.el
For some reason the current 'syntax' for setting the TAB key functionality in pdf outline work does not work.
The small syntax change in this PR fixes the issue.
> Fix tab key functionality in pdf outline mode

- layers/+completion/compleseus/packages.el
Some of the consul function names changed slightly.
Note that vertico is now on ELPA as well. But I couldn't figure out how to handle the extension packages. They are part of the vertico package and I don't know how to reference the extension directory and files inside the vertico package.
> compleseus: corrects name of some renamed consul commands

- .gitignore
- CHANGELOG.develop
As you start `devdocs-install`ing packages, the `devdocs` directory is created.
> Add 'devdocs' dir to '.gitignore' file.

- layers/+os/osx/packages.el
fixes #15370; see there for more explanation
Note: Actively using `dired-quick-sort` will still break things via tramp when the remote is using a version of `ls` that doesn't support `--sort=` or `--group-directories-first`, but at least now it doesn't start off broken :)
> [osx] don't set dired-listing-switches

- CHANGELOG.develop
- layers/+lang/scala/README.org
- layers/+lang/scala/funcs.el
- layers/+lang/scala/packages.el
This is another standard command (in addition to [these](https://github.com/syl20bnr/spacemacs/pull/15160)), not one specific to my build configuration. It can be useful only to compile the tests if your tests require any setup or do not run quickly.
> [scala] add keybinding for running `Test / compile` in SBT

- layers/+tools/shell/packages.el
Setting PAGER with setenv changes the environment variable for any child process
launched fom within emacs, such as terminals apps (gnome-terminal, tilix,
etc.). This can interfere with paginated tools --  pydoc, bat and others.
This commit sets PAGER only within eshell sessions.
> fix: do not setenv PAGER in shell layer

- core/core-configuration-layer.el
I was mucking around in the `cfgl-layer` class and noticed I wasn't able to get help to come up, i.e., if I did `SPC h d f cfgs-layer RET` I'd get an error about `(concat...)` not satisfying `stringp`. I did some digging, and it seems to me that `:documentation` is not evaluated and needs to be a literal string. This was actually previous fixed back in fcf186faff8afdeda51c3dd20b61943e876acae5, but was subsequently accidentally reverted in dc58801c7ddd770a1f94a17890b4efbd1f20f6e8.
This PR restores the fix of fcf186faff8afdeda51c3dd20b61943e876acae5.
> reinstate cfgl-layer docstring fix

- core/core-spacemacs-buffer.el
org-agenda-files can be a string or a nil. The meaning of string is different
than that of a single-member list.
The code treated the org-agenda-files variable like it needs to be a list.
Instead, one can use the org-agenda-files function to ask org-mode to resolve
the agenda files.
> Use org-agenda-files correctly in insert-recent-files

- CHANGELOG.develop
- layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
From Emacs version greater than 27.1, `return` is an obsolete alias
Replace with cl-return as directed in the warning message
Resolve #15396
> [space-doc] use cl-return as return is obsolete

- CHANGELOG.develop
- layers/+source-control/git/README.org
Add documentatation to the Spacemacs Git layer describing how to configure basic git identity and more importantly how to configure Magit Forge to access GitHub / GitLab using a machine configuration and an encrypted file to hold the personal access token.
> [git] document configuration of Magit Forge and Git identity

- layers/+completion/helm/README.org
Just found an error while reading the docs. A rogue `==` was breaking the markup.
> [completion] Fix readme markup.

- layers/+completion/helm/packages.el
helm-ls-git is specified as a package belonging to the helm layer, but it's
declared with the (non-existent) keyword :require, which should likely be
:requires. Changing it to :requires means that helm-ls-git will be installed
only if the git *package* is installed. It seems possible the original author's
intent was to install helm-ls-git only if the git *layer* was installed, but
it's hard to know for sure. As far as I know, no current spacemacs layers
install the git package, so fixing this typo will effectively remove helm-ls-git
except for cases where the git package is somehow installed (either explicitly
by the user, or through a private layer, etc).
As of writing, helm-ls-git is currently interfering with some git-rebase
keymaps (see #15089 for discussion), so fixing this typo …
> [helm] fix typo in helm-ls-git requires

- layers/+os/nixos/README.org
I simply copied the setting form the README to my config and wondered why nothing would happen... :-)
> Fix variable name in layers/+os/nixos/README

- CHANGELOG.develop
- layers/+source-control/github/README.org
- layers/+source-control/github/packages.el
Purpose of the PR changed after discussion and further review of the `github` layer
Remove github-clone & github-search packages from the layer, their key bindings and associated documentation.  Magit in the `git` layer can support cloning in a more secure way.
Update documentation:
- add depreciated layer notice and explanation
- remove reference to Magit forge (forge is added via the `git` layer)
- remove reference to git-link (git-link is added via the `git` layer
- Remove documentation regarding a GitHub access token (no longer required)
`grip-mode` and its configuration / documentation remains as the only functionality in the layer until it is decided what to to with this package.
Resolve #15377
> [github] mark layer as deprecated - remove unsecure packages

- CHANGELOG.develop
- layers/+email/notmuch/packages.el
In notmuch-message-mode, vanilla notmuch.el enables notmuch-company by
default.
This is done by `notmuch-address-setup()` which calls
`notmuch-company-setup()`.
In `notmuch-company-setup()`, we `setq-local company-backends`.
Unfortunately, `company-backends` gets overriden later on by
`spacemacs//init-company-text-mode()`, breaking email address completion
in `notmuch-message-mode`.
Tell spacemacs that `notmuch-company` should be added as a company backend
for `notmuch-message-mode` to solve this.
Signed-off-by: Mattijs Korpershoek <mattijs.korpershoek@gmail.com>
> notmuch: fix company based address completion

- layers/+spacemacs/spacemacs-editing/packages.el
Initialize `undo-tree-history-directory-alist` to stop `*.~undo-tree~` files from scattering all around.
Fix: #15426
> [spacemacs-editing] initialize `undo-tree-history-directory-alist`

- layers/+tools/eaf/packages.el
Relevant eaf layer keybinding code is based on suggestion from upstream eaf repo wiki. However, eaf API evolves faster than its wiki pages. This PR fixes #15306 using the workaround in the discussion. 
- Replace outdated eaf API call with most recent ones
- Tested with eaf-browser on my machine
- Both (kbd "SPC") and (kbd ",") works fine in eaf-browser
> Fix #15306. Reflect eaf layer keybinding logic to upstream changes.

- CHANGELOG.develop
- layers/+completion/helm/local/helm-spacemacs-help/helm-spacemacs-help.el
Several (but not all) of the functions responsible for constructing helm sources
for use with spacemacs help simply construct alists rather than using the
'helm-build-*-source' macros. The former approach is discouraged by the [helm wiki](https://github.com/emacs-helm/helm/wiki/Developing#sources).
One of the consequences of this approach is that some of the nice helm features
one might expect don't work. For example, before adopting this commit, try
bringing up the layer help with 'SPC h l', and then type 'evil space'. One would
expect this to match 'spacemacs-evil' (since space-separated "words" are treated as
separate search strings), but this match doesn't work. Even worse, just type
'evil ' (with a trailing space): there will be no candidates (presumably because
it is treating the …
> Improve helm completion in spacemacs help

- layers/+source-control/git/packages.el
See #15448 for full discussion.
In brief, `evil-surround` interferes with line-wise staging using `magit`, so this PR adds to the `magit-status-mode-hook` so that `evil-surround` is disabled in `magit-status` buffers.
> disable evil-surround in magit-status buffers

- layers/+lang/zig/packages.el
A typo introduced in 41393004881109d014dc2166c7110545ece9c32e prevented the backend to actually load lsp. This commit fixes this.
> [zig] Fix setup backend hook

- layers/+spacemacs/spacemacs-defaults/packages.el
This PR just binds `gr` to revert-buffer in process-menu-mode.  I bound it to `gr` rather than `g` so that `gg` still works.
> Add key binding for revert-buffer in process-menu-mode

- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
This change allows :pre-bindings to specify bindings using `(kbd
"C-x")` or variables that contains key sequences.
> [spacemacs-bootstrap] Fix :pre-bindings evaluation in evilified-state-evilify-map

- layers/+lang/json/README.org
Cf https://github.com/emacs-lsp/lsp-mode/issues/3395 the Node package to install has changed.
Installing the wrong Node package leads to `lsp-mode` not detecting the LSP and suggesting to install it automatically.
> doc: vscode-json-languageserver -> vscode-langservers-extracted

- layers/+lang/common-lisp/README.org
Hi,
This PR fixes a typo in the doc table for common lisp key bindings.
> common-lisp: Fix typo

- CHANGELOG.develop
- layers/+source-control/git/README.org
- layers/+source-control/git/packages.el
Add Spacemacs style key bindings menu when editing a Magit Forge topic (issue,
pull request)
Surfaces the Magit forge Topic commands describe in this section of the official documentation
https://magit.vc/manual/forge.html#Editing-Topics-and-Posts
> `forge-merge` command is discouraged by the official documentation and a local merge and push is recommended.  Therefore, a key binding is not included for this command.  
Replace: #15450
> [git] key bindings to edit magit forge topics

- layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el
In a terminal TAB and C-i generate the same key press. So to "avoid TAB being overlapped in terminal mode", function spacemacs/init sets evil-want-C-i-jump to nil. Unfortunately commit bbd40f1 always binds C-i to evil-jump-forward regardless
of the value of evil-want-C-i-jump. This pull request fixes that.
This pull request addresses ticket #15472.
> Only bind TAB when evil setting allows it

- CHANGELOG.develop
- layers/+lang/latex/README.org
- layers/+lang/latex/packages.el
Add support for the very useful [evil-tex package](https://github.com/iyefrat/evil-tex) to the latex layer.
Of particular note, this package provides numerous text objects for latex, e.g.,
latex-style quotes and double quotes, and also provides valuable toggles for
managing delimeters.
I've mapped its "magnificent toggles" (which are otherwise under a `mt` prefix)
to `SPC m m` (m for magnificent) to avoid interfering with any standard evil features.
I added brief documentation for evil-tex to the latex layer's README, which
primarily refers the reader to evil-tex's thorough documentation rather
than duplicating it in the readme.
> [latex] add, configure, and document evil-tex package

- layers/+emacs/org/packages.el
Org roam protocol can be used from outside Emacs and as such, loading it only
after some org-roam buffers are opened defeats the purpose. Without this change
the org-protocol links won't work after emacs restart until at least one
org-roam buffer is loaded.
I will note that it's not clear to me if there's a better way to fix this that
does not involve require (even if conditional). Alternatively we could just update the docs to make sure people put the require block in their user init (as I did to workaround the issue). But I think that defeats the purpose of spacemacs.
Fixes #14487
> When enabled require org-roam-protocol immediately

- layers/+completion/helm/local/helm-spacemacs-help/helm-spacemacs-help.el
Change `'` to `#'`, resolves #15443
> Fix function quote warning

- core/core-command-line.el
- core/core-compilation.el
- core/core-configuration-layer.el
- core/core-custom-settings.el
- core/core-display-init.el
- core/core-documentation.el
- core/core-dotspacemacs.el
- core/core-early-funcs.el
- core/core-emacs-backports.el
- core/core-env.el
- core/core-fonts-support.el
- core/core-funcs.el
- core/core-hooks.el
- core/core-jump.el
- core/core-keybindings.el
- core/core-progress-bar.el
- core/core-release-management.el
- core/core-spacemacs-buffer.el
- core/core-spacemacs.el
- core/core-themes-support.el
- core/core-toggle.el
- core/core-use-package-ext.el
For most of the core files the change was just ` -*- lexical-binding: t -*-` added to the top line.
Major and risky changes are in [core/core-configuration-layer.el](https://github.com/syl20bnr/spacemacs/compare/develop...thanhvg:feat/lexical?expand=1#diff-8abc7faad21a170282bd7b305596fb44024d8456e258863d40eea2be0ff6d630) which really depended on dynamic scope. For a basic test I was able to add and remove layers. And Spacemacs runs a bit faster.
I'm not very sure this change is safe, I am using this change on my boxes as a way to verify it. But I would like to push it to dev at some point to crowd source testing this change.
> [core] enable lexical binding for all

- CHANGELOG.develop
- layers/+web-services/search-engine/README.org
- layers/+web-services/search-engine/packages.el
This PR, adds Rails API (https://api.rubyonrails.org/) to supported search engines
> [search-engine] Add Rails API

- README.md
Fixes #14843.
This is in line with 964f4c5af3615b648a7707a39b82b7ef02dc4807, whose message states that "we no longer support master releases directly".
> [doc] Remove install instructions for old master

- layers/+emacs/org/README.org
This PR makes a minor change to the docs for `org-superstar-mode`. 
* update defaults to new default values
* correct variable name in example code block
* correct usage of character literals
> update org-superstar-mode docs

- core/core-debug.el
- When reporting issues on GitHub, it will copy the issue body to clipboard and
ask user to manually paste the content to the web browser, when the resulting
URL become too long.
- Cleaning up.
- Suppressed all compiler warnings.
- Re-ordered all top-level forms into various sections according to its functionality.
fixes #14309
> core-jump: reworked

- layers/+lang/rust/packages.el
When using LSP, there is little to no need to use Racer as well. So, this patch
conditionally enables Racer, only when it is selected as a backend.
Note: I'm unsure if the use case "racer-mode + lsp" is interesting for anyone. In that case, it would maybe be beneficial to add a separate variable to control this behavior.
> Enable racer only when it is selected as a backend

- layers/+spacemacs/spacemacs-evil/packages.el
Looks like `SPC` was missing when you're in lisp state :shrug:.
> [evil] fix missing spacemacs-default-map in evil-lisp-state.

- layers/+lang/javascript/packages.el
.cjs is an extension for CommonJS files, and is needed if `"type": "module"` is specified for a Node package.
> [javascript] Use js2-mode with .cjs files

- layers/+completion/compleseus/packages.el
As mentioned in #15555 the function consult-completing-read-multiple has been removed in the latest version of consult
> removing consult-completing-read-multiple in compleseus

- CHANGELOG.develop
- layers/+lang/fountain/README.org
- layers/+lang/fountain/packages.el
This new layer adds support for the [fountain](https://fountain.io/) screenwriting format, using the [fountain-mode](https://github.com/rnkn/fountain-mode) by @rnkn.
> Add fountain layer, a screenwriting file format

- core/core-spacemacs-buffer.el
- core/templates/.spacemacs.template
The default logo is rather big. Users might prefer to use the screen size for
other information (while still showing a banner).
This PR adds a configuration variable `dotspacemacs-startup-banner-scale`
to the dotfile
> Make startup banner scalable (from dotfile)

- layers/+emacs/org/packages.el
Starting with (org-contrib v0.4)[https://git.sr.ht/~bzg/org-contrib/commit/3dd98415225823f21fb7e12f272c0f199ac7407f] org-contacts is no longer part of it. Instead it is an own package.
> org-contacts no longer built-in

- core/core-spacemacs-buffer.el
A final 'force push' to PR #15574 implemented functionality to make the banner
size depend on the actual 'startup list' instead of the configured maximum
startup list size. However, that 'new' functionality uses
`spacemacs-buffer//do-insert-startupify-lists` which, effectively, activates `recentf-mode`,
and unfortunately, activating `recentf-mode` this early in the startup process
somehow breaks `recentf` functionality, see comments at
https://github.com/syl20bnr/spacemacs/commit/a485b5a84b3fa4f8a06b25f51cf6df49b51defb0.
This commit 'reverts' the functionality by making the banner size depend on the
configured maximum startup list size.
> Fix broken recentf functionality due to PR #15574

- README.md
Several changes are made to the home README file to improve the readability. 
A large portion of the changes is in the grammar and sentence structure. The
remaining changes were split between fixing inconsistent use of capitalisation,
odd line breakings in the Org file, and handling links by making use of
Markdown's referencing feature
> Correct grammar for homepage README file

- core/core-spacemacs-buffer.el
The function `spacemacs-buffer/jump-to-recent-files` is used for jumping to the recent files by press `r` in Spacemacs home buffer.
Try to byte-compile the file `core-spacemacs-buffer.el`,
```
(byte-compile-file (concat spacemacs-core-directory "core-spacemacs-buffer.el"))
```
Restart the Spacemacs, then the function `spacemacs-buffer/jump-to-recent-files` is missed, press `r` in Spacemacs home buffer will not work, describe-function will not find the function.
This change fixed the issue with giving correct lisp for byte-compiler (avoid using the `eval` in lexical scope).
> [core] fix functions missed for byte-compiled core-spacemacs-buffer.el

- layers/+lang/python/packages.el
There is an issue that running `describe-key` (`C-h k`) will trigger an error message:
> mapcar: Symbol’s value as variable is void: code-cells-mode
The root cause is the `code-cells` package in `python` layer should use the `:config` instead of the `:init` tag.
Deatils:
It happend with Spacemacs `develop` branch with `python` layer, emacs-28 with native-comp enabled, on CentOS 7.
In GNU Emacs 28.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.12)
of 2022-06-18 built on dev
Repository revision: 422f958030f1c105c8f62f670b82875559b38e69
Repository branch: HEAD
Windowing system distributor 'The Cygwin/X Project', version 11.0.12101003
System Description: CentOS Linux 7 (Core)
Configured using:
'configure CC=clang CXX=clang++ CFLAGS=-Os CXXFLAGS=-Os …
> [python] fix config issue for native-comp

- core/core-configuration-layer.el
There is the error messages when byte-compiling the `core-configuration-layer.el`, 
```
(byte-compile-file (concat spacemacs-core-directory "core-configuration-layer.el"))
```
Part of the error messages:
>In configuration-layer//filter-packages-with-deps-recur:
core-configuration-layer.el:1889:33: Error: ‘add-to-list’ can’t use lexical
var ‘result’; use ‘push’ or ‘cl-pushnew’
> [core] fix error msg on byte-compiling core-configuration-layer.el

- layers/+source-control/git/packages.el
This is an extension of #15462.  I noticed that the fix did not apply
to magit-diff buffers, which still had the issue of `s' not being
available to stage diff hunks.  `magit-diff-mode' is the parent mode
of all magit modes, in which evil-surround is not useful, so disabling
there makes the most sense.
> [git] Disable evil-surround-mode in all magit modes

- layers/+source-control/git/packages.el
magit v3.2.0 now defines `magit-git-executable` as a
function (actually a defsubst), and two separate variables,
`magit-git-executable` and `magit-remote-git-executable`.  On darwin,
magit already sets `magit-git-executable` to the result of
`(executable-find "git")`, so having this is now redundant in
Spacemacs.
> [git] Remove magit-git-executable hack, which is no longer needed

- layers/+spacemacs/spacemacs-defaults/packages.el
Entries of recentf-exclude must be expanded, e.g., `~` for the home
directory won't work.
> [defaults] Exclude `custom-file` correctly in recentf

- CHANGELOG.develop
- core/core-dotspacemacs.el
- core/templates/.spacemacs.template
- layers/+checkers/spell-checking/README.org
- layers/+lang/coq/packages.el
- layers/+spacemacs/spacemacs-evil/README.org
- layers/+spacemacs/spacemacs-evil/funcs.el
- layers/+spacemacs/spacemacs-evil/packages.el
- layers/+tools/shell/packages.el
- layers/+vim/vim-empty-lines/README.org
- layers/+vim/vim-empty-lines/packages.el
- layers/LAYERS.org
https://github.com/syl20bnr/spacemacs/issues/15622
Revert "Delete vim-empty-lines layer and merge its code into spacemacs-evil"
This reverts commit ebd920e23a287eacf0a42ff0e3eef4b2db95d3dd.
> [evil] bring back vi-tilde-fringe

- layers/+email/mu4e/packages.el
As  0ce1201a3 did not fix issue #15618 as expected, this hopefully does.
The variable used to determine the version is set in the file which should be loaded.
This is a bit hacky, and may be removed some time in the future when mu versions older than 1.8.2 are no longer supported.
> Fix a previous attempted fix loading mu4e.

- .gitignore
More context: on the `develop` branch, I updated from 1a4912e51fdc012ba571c670e8c8e8c5eb4695d1 to 4eaff25268634fcb8137b91fb7d0b7598588cbca and I noticed I have `recentf~` created in `~/.emacs.d`. If you delete it it gets created again on the next emacs restart.
Given that I have the spacemacs code as a submodule of my dotfiles repo, this shows up as an unwanted change.
This seems a not too controversial change *there is already `.recentf` and `.recentf~` for example), but let me know if you want me to do more investigation.
> Add /recentf~ to .gitignore

- CHANGELOG.develop
- layers/+distributions/spacemacs-bootstrap/config.el
- layers/+distributions/spacemacs-bootstrap/packages.el
- layers/+spacemacs/spacemacs-editing/README.org
- layers/+spacemacs/spacemacs-editing/packages.el
As was the case with `vim-style-remap-Y-to-y$', or rebinding "s" to
evil-surround over vim's default substitute, by rebinding "u" to undo-region
is a sensible trade-off given that prior to this, undo-region was accessible
only through SPC SPC C-_.
See https://emacs.stackexchange.com/questions/32244/undo-region-spacemacs
Comments and suggestions?
> Undo-region: more ergonomic keybindings

- CHANGELOG.develop
- core/templates/.spacemacs.template
- layers/+distributions/spacemacs-bootstrap/packages.el
More discussion at https://github.com/syl20bnr/spacemacs/discussions/15455
Is it alright if the advising function is anonymous?
> [spacemacs-bootstrap] Remove whitespace from kill ring.

- layers/+completion/compleseus/funcs.el
- layers/+completion/compleseus/packages.el
Copy from: https://github.com/minad/vertico/issues/22
Anyway `M-n` in compleseus is still not so smart as helm and ivy.
> [compleseus] improve M-n

- layers/+lang/major-modes/README.org
- layers/+lang/major-modes/packages.el
Really simple PR, just adds [gemini.el](https://git.carcosa.net/jmcbray/gemini.el) for Gemtext support and adds leader-key bindings for its functions.
Gemtext is the native markup language for the [Gemini protocol](https://gemini.circumlunar.space).
> [major-modes] Add Gemtext support

- core/core-dotspacemacs.el
Commit 861ea131e1be7963b9602e774024f687fe9d4a29 refactored the definition of
dotspacemacs-directory, but did not ensure that the path ended with a slash,
which is expected elsewhere in the code
This prevented spacemacs from loading the environment file and the user's custom layers
> fix: dotspacemacs-directory is expected to end with a slash

- CHANGELOG.develop
- layers/+completion/helm/README.org
- layers/+tools/docker/packages.el
After several weeks using the layer for building Dockerfiles, I've came up with a few enhancements:
* I've flattened the `, c b` and `, c B` keys for build commands to just `, b` and `, B` to save keystrokes. I'm hesitant to remove existing ones because of annoying existing users, but feels redundant. Feedback on this is needed.
* Since [Silex/docker.el](https://github.com/Silex/docker.el)'s package is also installed for managing the `docker` daemon, I've added some command shortcuts for convenience (in addition to the existing `SPC a t d ...` ones):
* `p` for `docker ps`, which can be used to delete failed builds' containers.
* `i` for `docker images`, to delete old image builds.
* `d` to access all the `docker` package commands (incl. `images` and `ps`): `docker {volumes,networks,...}`. …
> Improve Docker layer 'dockerfile-mode' major mode keybindings

- layers/+lang/julia/README.org
lsp-julia-default-envornment is set by default to ~/.julia/environments/v1.0 .
To make the lsp server show completions for installed packages, the environment
location must be the same as that of the installed julia version enviornment.
Documentation was added to notify users to set the emacs variable to their
enviornment location.
> Added documentation to set julia envornment location for lsp server

- core/core-configuration-layer.el
Hi,
The log for the rshadow relationship message is really confusion , and after check the code, it's from the wrong line.
This patch is try to fix it.
> * core/core-configuration-layer.el: fix log for rshadow relationship

- core/core-dumper.el
Hi,
I enabled the native-compile for my local emacs28/emacs29 buildings, and try to compile all the `spacemacs/core/*.el` files into the `*.elc` files, then emacs will do native-compile for these `*.elc` files automatically. 
After native-compile `spacemacs/core/*.elc` files done, restart the Spacemace, there will has "invalid-function" error as follow, then the emacs stucked. 
This pull request just re-order the functions, it will fix the error for this scenario, and everything worked.
```
Debugger entered--Lisp error: (invalid-function spacemacs|unless-dumping)
spacemacs|unless-dumping(nil)
spacemacs/dump-restore-load-path()
(let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) …
```
> *core/core-dumper.el: Enhance for native-compile support

- core/core-dotspacemacs.el
Hi,
The variable `list-size` is unused in the lambda function, there will has a warning message when byte-compile the file.
Please help review the change. Thanks.
> core: remove unused variable

- core/core-compilation.el
- core/core-spacemacs.el
- init.el
Hi,
Currently `dotspacemacs-byte-compile` is `t` will only compile serveral files in `core/lib/*`.
After the PR #15692, all files in `core/` will be able byte-compile/native-compile.
So we'll byte compile the `core/` directory when `dotspacemacs-byte-compile` is `t`.
> core: byte-compile the "core/libs/" folder when dotspacemacs-byte-compile is t

- init.el
Refs: https://github.com/syl20bnr/spacemacs/issues/11585
Seems to me we should prefer compatibility over speed here.
PR open for comments from public and maintainers,
> Disable incompatible optimisation in init.el

- layers/+tools/docker/README.org
- layers/+tools/docker/packages.el
As requested by @arifer612 on #15414:
* Use `package-installed-p` instead of `with-eval-after-load` to check for package presence before adding bindings (to account for excluded package).
* Wrap `:config` block in a `progn` as per [CONVENTIONS.org](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#use-package).
* Add keybindings to docs.
> Docker: Followup for #15414: fix bindings not loading, add docs

- core/core-dumper.el
The built-in function was apparently renamed. See the Emacs' ChangeLog.3:
> native-comp-available-p is the definitive test
> — 2021-10-05  Stephen Gildea  <stepheng+emacs@gildea.com>
> Fix `spacemacs/emacs-with-native-compilation-enabled-p`

- layers/+tools/tree-sitter/README.org
- layers/+tools/tree-sitter/packages.el
Hi, I am the author of [ts-fold](https://github.com/emacs-tree-sitter/ts-fold). The repo has moved under the same domain `emacs-tree-sitter`, this PR updates the repo link.
> chore(ts-fold): Update repo link for ts-fold module

- layers/+spacemacs/spacemacs-defaults/config.el
Native compilation is extremely verbose with thousands of individual warnings from packages popping up in a window that can't be dismissed, unless you disable the warnings, or you suppress them.
> Surpress native compilation *Warnings* buffer

- layers/+readers/pdf/packages.el
Currently, due to evil entering visual state, the selection behavior in pdf-tools is different from and more cumbersome than in vanilla Emacs (see https://github.com/emacs-evil/evil/issues/1671).
This commit prevents evil from entering evil-state in pdf-mode and moves the (only) visual-state yank binding to the evilified-map.
It doesn't look pretty, but it is working much better than before.
> Fix cumbersome pdf-tools selection behavior
