syl20bnr/spacemacs

contrib/lang/scala/packages.el
Rename init functions and fix custom variables forms.
=> Scala fixes

contrib/lang/scala/funcs.el, contrib/lang/scala/packages.el, spacemacs/funcs.el
General improvements to the scala editing experience.
=> Scala extensions

spacemacs/funcs.el, spacemacs/packages.el
=> Yet another modeline fix

core/core-themes-support.el
=> Fix the path for loading solarized.

core/core-configuration-layer.el
This is related to #3184 and #3187.
=> Loading warnings for using warning-minimum-level

layers/+lang/haskell/README.org
Mostly did it to describe how to install `ghc-mod`. Following #2142.
Also made some minor improvements to this document. Hope you'll like it :smile:
=> Add notes for stack users

layers/+source-control/git/README.org, layers/+source-control/git/packages.el
Sorry @TheBB didn't think to update the docs on that last pr
=> Update magit docs for evil-magit and don't enable if emacs editing style

layers/+lang/haskell/packages.el, layers/+vim/evil-snipe/packages.el
This is a meta-PR. I'll be collecting all the commits I see that need to be applied to master to keep it working.
@syl20bnr
=> Release 0.104.3

layers/+distribution/spacemacs-base/packages.el
@TheBB this is causing an error on startup
=> spacemacs-base: Fix paren problem

layers/+lang/ruby/config.el
* layers/+lang/ruby/config.el (ruby-mode): Fix
=> Fixed undefined (ruby-)mode which key prefix declaration

layers/+lang/html/packages.el
This was reported on gitter.
https://gitter.im/syl20bnr/spacemacs?at=565aad8e49e74fad21eb92fa
=> Fix smartparens loading in web-mode

layers/+keyboard-layouts/bepo/README.org, layers/+keyboard-layouts/bepo/config.el, layers/+keyboard-layouts/bepo/funcs.el, layers/+keyboard-layouts/bepo/keybindings.el
=> Bepo layer rewrite

layers/+distribution/spacemacs-base/keybindings.el
Some how it got lost moving helm into its own layer.
=> spacemacs-base: Add back view-emacs-news

layers/+lang/python/packages.el
=> Only load pyenv if it is installed

layers/+distribution/spacemacs-base/funcs.el
=> Fixes #5448 - guard nil buffer size

layers/+lang/python/extensions.el
A very simple fix for the yapf bug.
=> fix yapf still being in extension, causing its loading to fail

layers/+completion/ivy/packages.el
Fix for https://github.com/syl20bnr/spacemacs/commit/4dead4cca7f0fcf1575feef0bd79482c3eda7690#commitcomment-17708424
=> completion/ivy: fix projectile-switch-project-action

layers/+lang/purescript/README.org, layers/+lang/purescript/packages.el
Adds keybindings for new psc-ide functionality
=> [purescript] add keybindings for goto definition functionality

layers/+source-control/github/README.org
Fix formatting in the github layer introduced by me
=> fix table formatting

layers/+lang/asciidoc/README.org, layers/+lang/asciidoc/packages.el
Upstream fix: https://github.com/sensorflo/adoc-mode/commit/656e7670c5dd9fee54dfe466cf0b7006f50e0355
=> Fix asciidoc demote function name

layers/+lang/ruby/README.org
=> add docs for ruby minitest mode

CHANGELOG.org
=> Fix org markup in the changelog

layers/+spacemacs/spacemacs-evil/funcs.el, layers/+spacemacs/spacemacs-evil/packages.el
=> Activating linum-relative now activates linum

layers/+lang/go/packages.el
https://github.com/syl20bnr/spacemacs/issues/7552#issuecomment-256273894
=> go-guru on MELPA

layers/+lang/scheme/config.el
Fixes scheme layer error similar to typescript one in #7377 . Fix copied from 7869154e9dd5ad2228dd09e3546a3722a522961a
=> fix void-variable company-backends-scheme-mode

layers/+distributions/spacemacs-base/keybindings.el
=> spacemacs-base: add prefix for ripgrep search

layers/+chat/slack/README.org
Just fixing a misspelling of "everything".
=> Fix minor typo

layers/+frameworks/ruby-on-rails/packages.el
I just pushed a change to projectile-rails https://github.com/asok/projectile-rails/commit/168ab64262d5927520a838bb659ab38b4f001eee
Anyone that will update the package needs this change in order for it to work.
=> Use projectile-rails-global-mode

layers/+spacemacs/spacemacs-evil/packages.el
My previous commit left behind a trailing white space.
=> Update packages.el, remove trailing white space

core/core-themes-support.el
https://github.com/syl20bnr/spacemacs/issues/8633
Thank you <3
=> Fix the issue of terminal failed to load theme.

README.md
=> typo: your -> you're

core/libs/spacemacs-theme/README.md, core/libs/spacemacs-theme/spacemacs-common.el
Few more updates to the theme.
=> Latest spacemacs-theme updates

layers/+lang/java/packages.el
=> fix(java): typo

layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
=> org: fix https links

layers/+tags/gtags/funcs.el
https://github.com/syl20bnr/spacemacs/issues/10031
This is issue is about gtags navigation command.
=> [#10031] Fix issue "counsle-gtags command doesn't work in c-c++ layer"

layers/+lang/extra-langs/layers.el
This layer has long been deprecated and is due to be nuked.
=> [BREAKING CHANGE] delete extra-langs layer

layers/+emacs/org/README.org, layers/+emacs/org/packages.el
Add global and layer key bindings for `C-c C-x g` and `C-c C-x G` (org-feed-update-all & org-feed-goto-inbox, respectively).
=> Add key bindings for org-feed-update-all and org-feed-goto-inbox

core/libs/spacemacs-theme/README.md, core/libs/spacemacs-theme/spacemacs-common.el
The latest updates of spacemacs-theme :purple_heart:
=> Latest updates of spacemacs-theme

.circleci/config.yml, .gitignore, .travis.yml
=> Testing the tests

EXPERIMENTAL.org
Add windows instructions for building emacs with pdumper
=> Add windows instructions for building emacs with pdumper

core/core-dotspacemacs.el
The editing style test should be updated after recent commits.
=> Fix editing style test

tests/core/core-configuration-layer-utest.el
Disabling some mocks to not discourage contributions.
=> Trying to fix the tests

layers/+tools/finance/README.org, layers/+tools/finance/packages.el
Small addition to the finance layer to use [evil-ledger](https://github.com/atheriel/evil-ledger).
=> finance: use evil-ledger.

layers/+emacs/org/README.org
In the dedicated sitting, with a cup of tea, I started to read through the `org` layer manual.
And perceived that the text can have a much better phrasing.
So far I got to the `org-journal`.
After I would get `org-journal` working and would get adjusted to it - I would go further and submit the rest of the changes.
<sub>
P.S.</sub>
<sub>And after I get this `org` study done, and https://github.com/NixOS/nix/pull/1565 installer done (after July 31) - I would be able to get https://github.com/syl20bnr/spacemacs/pull/10977 done.</sub>
=> layer: org: README.org: text changes

layers/+completion/templates/README.org
=> update document of layer templates to match recent changes

.circleci/PR_base, .circleci/PR_rebased, .circleci/config.yml, .circleci/shared
=> [CI] Check if PR needs rebase

.circleci/format
Make fixing documentation formatting more convenient
=> [CI] Generate patches for ez formatting

layers/+email/mu4e/README.org, layers/+email/mu4e/config.el, layers/+email/mu4e/packages.el
Kills mu4e layout when user quits mu4e app
=> [mu4e] kill mu4e layout on app exit

layers/+lang/pact/README.org, layers/+lang/pact/packages.el
This PR adds a language layer for the Smart Contract language [Pact](https://github.com/kadena-io/pact).
=> Pact Layer

.travisci/pub_html.sh, .travisci/pub_org_fmt.sh, .travisci/pub_prep.sh
=> [TravisCI] fix publishing

.travisci/pub_html.sh, .travisci/pub_org_fmt.sh, .travisci/pub_prep.sh
This time it will work! :angry:
=> [TravisCI] Select only .org files for autofix

.travisci/pub_org_fmt.sh, layers/+lang/clojure/README.org
=> Fix typo && url

.travisci/pub_org_fmt.sh, .travisci/pub_prep.sh
Make bot open documentation fixing PR against proper branch.
=> [TravisCI] update hub && set [AF] PR branch

.travisci/pub_org_fmt.sh
=> [TravisCI] fix hub flag name

.travisci/pub_html.sh, .travisci/pub_org_fmt.sh
=> [TravisCI] add newlines to PR messages

.travisci/pub_html.sh, .travisci/pub_org_fmt.sh
sorry for spamming PR.  I underestimated my ability to make stupid mistakes :roll_eyes:
=> [TravisCI] add newlines symbol

layers/+lang/ipython-notebook/README.org, layers/+lang/julia/README.org, layers/+lang/pact/README.org, layers/+lang/typescript/README.org, layers/+tools/shell/README.org, layers/LAYERS.org
Merge with care - I'm just a stupid bot. Beep boop.
=> [Spacebot]Documentation fixes

.travisci/pub_org_fmt.sh
=> Fiddling with TravicCI

layers/LAYERS.org
Merge with care - I'm just a stupid bot. Beep boop.
=> [bot] Documentation formatting

layers/+lang/rust/README.org, layers/+lang/rust/config.el, layers/+lang/rust/funcs.el, layers/+lang/rust/packages.el
Add rust-lsp completion with company, flycheck and bindings.
Edit: Updated with typo fix
refs: #10443 #11161
=> Add: rust-lsp

.travisci/pub_html.sh, .travisci/pub_org.sh
Protecting from re-running old builds.
=> [TravisCI] Make sure that we deploy only from HEAD

.travisci/pub_html.sh, .travisci/pub_org.sh
Trust Hub about whether we need to commit anything.
=> [TravisCI] Use Hub to test for empty commits.

core/libs/spacemacs-theme/README.md, core/libs/spacemacs-theme/spacemacs-common.el
Update spacemacs theme to commit c162ad13 upstream.
https://github.com/nashamri/spacemacs-theme/commit/c162ad13e4ae1965619012332d3b5f57c9172e98
Contains a fix for https://github.com/syl20bnr/spacemacs/issues/10877
=> update spacemacs theme

layers/+lang/c-c++/README.org
=> Fix src blocks in c-c++ layer

doc/DOCUMENTATION.org
Hope that it helps.
Happy hacking!
=> DOCUMENTATION.org: Fix typos

core/core-documentation.el
Slight to the left :roll_eyes:
=> Fat fingers

layers/+distributions/spacemacs-docker/deps-install/installers/go/README.org, layers/+distributions/spacemacs-docker/deps-install/installers/go/install.el, layers/+distributions/spacemacs-docker/deps-install/installers/gtags/install.el, layers/+distributions/spacemacs-docker/deps-install/installers/pandoc/install.el
Updating dependencies for docker stuff.
=> Update layers dependency installers

Dockerfile.emacs25, Dockerfile.snapshot
Environment variables from deps no longer missing. :hugs:
=> Fix environment variables export

Dockerfile.emacs25, Dockerfile.snapshot, layers/+distributions/spacemacs-docker/funcs.el, layers/+distributions/spacemacs-docker/layers.el
Previous solution happened to be buggy :thinking:
=> Load docker env vars via user config hook

layers/+spacemacs/spacemacs-defaults/keybindings.el, layers/+spacemacs/spacemacs-editing-visual/funcs.el, layers/+spacemacs/spacemacs-editing-visual/packages.el
Simple transient state for shrinking and enlarging centered buffer.
=> Add transient state for centered buffer

doc/DOCUMENTATION.org
Document new centering key bindings :roll_eyes:
=> document new centering key bindings

layers/+tools/ansible/README.org
@robbyoconnor must have created branch from master before, sorry
=> Fixing incorrect shortcuts in README

.circleci/PR_changelong, .circleci/config.yml, .circleci/select
The thingy should suggest adding changelog entry.
=> add changelog update check

.circleci/PR_changelong
@emacspace  just a :robot:  after all.
=> Don't ask emacspace to update changelog

layers/+lang/purescript/packages.el, layers/+source-control/git/packages.el, layers/+spacemacs/spacemacs-purpose/packages.el
Minor changes to recently merged PRs #12067 and #12093. 
(No need to update the changelog since it's just adjustments to recent changes)
=> Minor bug fixes

layers/+source-control/git/funcs.el, layers/+source-control/git/packages.el
Fix missing newline warning
Keep lines under 80 chars
=> [git] Code formatting

CHANGELOG.develop, layers/+lang/python/README.org
Importmagic and epc isn't really optional if error messages are to be avoided.
=> Added instruction on installing importmagic and epc.

CHANGELOG.develop, layers/+lang/javascript/README.org, layers/+lang/javascript/config.el, layers/+lang/javascript/funcs.el, layers/+lang/javascript/packages.el, layers/+lang/typescript/funcs.el
Adding configurable formatting on save functionality similar to typescript
layer. One small syntax error fix in typescript layer.
=> Adding format on save to javascript layer

.ci/spacedoc-cfg.edn, .circleci/PR_changelong, .circleci/validoc/validate, .travisci/pub_prep.sh, layers/+lang/asm/README.org, layers/+lang/forth/README.org, layers/+tools/xclipboard/README.org
Add testing version of the new  LAYERS.org generator
=> new  LAYERS.org generator

.ci/spacedoc-cfg.edn
=> Add new tags to the config file

.travis.yml, .travisci/pub_prep.sh, layers/LAYERS_WIP.org
Fixed relative links in descriptions. So html export should work now.
=> Working on ney layers.org generator

CHANGELOG.develop, layers/+lang/clojure/README.org, layers/+lang/clojure/config.el, layers/+lang/clojure/packages.el
Finally made it work properly(maybe?, hopefully..) with Spacemacs.
=> add flycheck-clojure

.ci/spacedoc-cfg.edn, Dockerfile, layers/+distributions/spacemacs-base/README.org, layers/+distributions/spacemacs-bootstrap/README.org, layers/+distributions/spacemacs-docker/deps-install/installers/html/install.el, layers/+distributions/spacemacs/README.org, layers/+lang/alda/README.org, layers/+spacemacs/spacemacs-completion/README.org, layers/+spacemacs/spacemacs-defaults/README.org, layers/+spacemacs/spacemacs-editing-visual/README.org, layers/+spacemacs/spacemacs-editing/README.org, layers/+spacemacs/spacemacs-evil/README.org, layers/+spacemacs/spacemacs-language/README.org, layers/+spacemacs/spacemacs-layouts/README.org, layers/+spacemacs/spacemacs-misc/README.org, layers/+spacemacs/spacemacs-modeline/README.org, layers/+spacemacs/spacemacs-navigation/README.org, layers/+spacemacs/spacemacs-org/README.org, layers/+spacemacs/spacemacs-project/README.org, layers/+spacemacs/spacemacs-purpose/README.org, layers/+spacemacs/spacemacs-visual/README.org, layers/+themes/colors/local/nyan-mode/README.org
=> A bunch of fixes

CHANGELOG.develop, layers/+lang/html/README.org, layers/+lang/html/config.el, layers/+lang/html/funcs.el, layers/+lang/html/packages.el
Add LSP support for stylesheet buffers.
=> Add LSP support for stylesheet buffers

CHANGELOG.develop, layers/+frameworks/react/funcs.el, layers/+lang/javascript/funcs.el, layers/+lang/typescript/funcs.el, layers/+tools/lsp/funcs.el
- company-lsp is now smarter and supports fuzzy matching
=> Remove the fix-lsp-company-prefix since it is no longer needed

layers/+lang/reasonml/README.org, layers/+tools/dotnet/README.org, layers/+tools/sailfish-developer/README.org
=> update .org tags

CHANGELOG.develop, layers/+themes/themes-megapack/packages.el
"A dark chocolatey theme for Emacs" by Valeriy Savchenko.
https://github.com/SavchenkoValeriy/emacs-chocolate-theme/
=> [theme-megapack] Add chocolate-theme

.travis.yml, .travisci/pub_prep.sh
Should fix the build. Theoretically :thinking:
=> fix TravisCI

.travisci/pub_prep.sh
Hopefully this will do :crossed_fingers:
=> [CI] fix file path

layers/+lang/haskell/README.org
gotta fix them one by one :sleeping:
=> fix a link in Haskell docs

layers/+emacs/org/README.org, layers/+lang/mercury-layer/README.org, layers/+lang/zig/README.org
=> doc fixes and new tags

tests/core/core-configuration-layer-ftest.el
=> skip some tests on PRs

.travis.yml
=> [docfmt] Make stale overrides rarer

.travis.yml
=> [CI] Fix deploy condition

.travis.yml
Seems like that multi-line form makes Travis go bunkers. :confused:
=> [CI] Cramp deploy conditions into a single line

.travis.yml, .travisci/pub_org.sh, .travisci/pub_prep.sh
Documentation fixing bot stuff
=> Use patches to fix docs

.travisci/pub_prep.sh
html export should happen even if docs don't need any fixes.
=> [CI] Do not exit prematurely.

layers/+email/notmuch/README.org
=> Testing if .org fmt still works

.travis.yml, .travisci/pub_html.sh, .travisci/pub_org.sh, .travisci/pub_prep.sh
Ok bot. Start working or else :shipit:
=> Fix revision check

.travis.yml, .travisci/pub_html.sh, .travisci/pub_org.sh, .travisci/pub_prep.sh
Maybe this time it will do the trick :roll_eyes:
=> [CI] Fix doc fmt bot && cleanup

.travisci/pub_html.sh, .travisci/pub_org.sh, .travisci/pub_prep.sh
This time it will work :shipit:
=> [CI] store base_rev in file

.travisci/pub_html.sh, .travisci/pub_org.sh
last time I said this time it will work :shipit:
=> [CI] re-export token

.circleci/config.yml, .github/workflows/changelogs.yml
=> Move changelog test to GitHub actions

.ci/spacedoc-cfg.edn, CONTRIBUTING.org
Hopefully nothing brakes :crossed_fingers:
=> Better docs for layer tags

CONTRIBUTING.org
=> Improve tags documentation

layers/+lang/emacs-lisp/packages.el
=> Add flycheck-elsa

CHANGELOG.develop, layers/+lang/plantuml/README.org
Pretty self explanatory, I think.
=> update link to plantuml reference guide

.github/workflows/stale.yml
=> add stale action

.github/workflows/stale.yml
So now it should run every 15 minutes and process 30 iussues/PRs at a time :thinking:
=> adjust timer stale action timer

.github/workflows/stale.yml
Now it will (probably) run every 15 minutes. Unless it has to be in the "master" branch :thinking:
=> add stale... Again

core/core-spacebind.el, layers/+distributions/spacemacs-bootstrap/funcs.el, tests/core/core-spacebind-utest.el, tests/layers/+distribution/spacemacs-base/spacebind-utest.el
Doing requested fixes/updates. Also streamlined implementation.
=> Rename spacebind macro

core/core-spacebind.el, tests/core/core-spacebind-utest.el, tests/layers/+distribution/spacemacs-base/spacebind-utest.el
More docs and tests for `spacebind` macro + basic which-key replacements impl (without test for now)
=> Spacebind key ranges

core/core-spacebind.el, tests/core/core-spacebind-utest.el, tests/layers/+distribution/spacemacs-base/spacebind-utest.el
Current progress + hot fix  for ` (void-function every)`
=> Spacebind stuff

core/core-spacebind.el, tests/core/core-spacebind-utest.el
=> [spacebind] generate less code

CHANGELOG.develop, layers/+lang/c-c++/README.org, layers/+lang/c-c++/config.el, layers/+lang/c-c++/layers.el, layers/+lang/c-c++/packages.el, layers/LAYERS.org
- it is no longer supported and it is causing troubles.
=> Remove cquery backend

CHANGELOG.develop, layers/+lang/scala/README.org, layers/+lang/scala/config.el, layers/+lang/scala/funcs.el, layers/+lang/scala/layers.el, layers/+lang/scala/packages.el
Adding support for DAP and lsp-treeview in the scala layer
=> Add support for DAP and lsp-treeview in scala layer.

CHANGELOG.develop, layers/+frameworks/react/funcs.el, layers/+frameworks/vue/funcs.el, layers/+lang/c-c++/README.org, layers/+lang/c-c++/funcs.el, layers/+lang/elixir/funcs.el, layers/+lang/ess/packages.el, layers/+lang/go/funcs.el, layers/+lang/java/funcs.el, layers/+lang/javascript/funcs.el, layers/+lang/julia/packages.el, layers/+lang/lua/README.org, layers/+lang/lua/funcs.el, layers/+lang/python/funcs.el, layers/+lang/rust/funcs.el, layers/+lang/typescript/funcs.el, layers/+tools/docker/README.org, layers/+tools/lsp/README.org, layers/+tools/lsp/packages.el, layers/LAYERS.org
- Also removed some cquery artefacts which accidentally ended up in this PR
instead of in #13446
=> Removed company-lsp in favour of company-capf

CHANGELOG.develop, layers/+filetree/treemacs/config.el, layers/+filetree/treemacs/packages.el
- use treemacs-use-icons-dired to enable/disable it
=> [Treemacs] Use treemacs-icons-dired when treemacs layer is present

layers/+frameworks/react/README.org, layers/+frameworks/react/packages.el
add key bindings for log functions from the javascript layer to the react layer since they are oh so useful
=> add js log key bindings to react layer

CHANGELOG.develop, layers/+lang/emacs-lisp/README.org, layers/+lang/emacs-lisp/packages.el
see https://github.com/Wilfred/emacs-refactor
- I got my inspiration for the keybindings from the clojure layer
=> [emacs-lisp] Added emr integration

layers/+tools/debug/README.org
This patch helps fix a broken link in documentation of debug layer.
Thank you <3
=> [Debug][Doc] Fix broken link in documentation.

layers/+tools/fasd/packages.el
- Underestimated but a very handy package.
=> [fasd] Use helm-fasd in fasd layer when helm is present

CHANGELOG.develop, layers/+readers/pdf/README.org, layers/+readers/pdf/packages.el
fix pull request/align key binding table
Thank you <3
=> add pdf-mode keybindings to scroll through history

layers/+lang/javascript/funcs.el, layers/+lang/javascript/packages.el
move stray execution in funcs into package init
=> [javascript] proper hook setting for js-doc

CHANGELOG.develop, layers/+frameworks/react/layers.el, layers/+lang/javascript/layers.el
=> Avoid unnecessary packages installation of tern layer

README.md
Following https://github.com/d12frosted/homebrew-emacs-plus/issues/214
=> add instructions to build emacs-plus with Spacemacs icon

layers/+emacs/org/README.org, layers/+spacemacs/spacemacs-org/packages.el
org-bullets has been deprecated
=> [org] replace org-bullets with org-superstar

layers/+emacs/org/packages.el
When navigating source code blocks, it is now possible to execute several of
them without exiting the transient state.
Thank you <3
=> Tune org-babel transient state.

.circleci/PR_base, .circleci/PR_changelong, .circleci/PR_rebased, .circleci/select, .circleci/shared, .circleci/validoc/export, .circleci/validoc/validate
=> CI cleanup

.circleci/PR_base, .circleci/PR_changelong, .circleci/PR_rebased, .circleci/config.yml, .circleci/select, .circleci/test, .circleci/validoc/export, .circleci/validoc/validate
=> [CI] auto-load shared

.circleci/PR_base, .circleci/PR_changelong, .circleci/PR_rebased, .circleci/select, .circleci/shared, .circleci/validoc/export, .circleci/validoc/validate
=> [CI] Fail job when CircleCI didn't set required vars

layers/+lang/haskell/README.org
Just a small documentation tweak
=> update stack project-root command

CHANGELOG.develop, layers/+spacemacs/spacemacs-defaults/keybindings.el, layers/+tools/bm/README.org, layers/+tools/bm/packages.el, layers/+tools/chrome/README.org, layers/+tools/chrome/keybindings.el, layers/+tools/command-log/README.org, layers/+tools/command-log/packages.el, layers/+tools/docker/README.org, layers/+tools/docker/packages.el, layers/+tools/geolocation/README.org, layers/+tools/geolocation/packages.el, layers/+tools/ipython-notebook/README.org, layers/+tools/ipython-notebook/packages.el, layers/+tools/kubernetes/README.org, layers/+tools/kubernetes/packages.el, layers/+tools/pass/README.org, layers/+tools/pass/packages.el, layers/+tools/prodigy/README.org, layers/+tools/prodigy/packages.el, layers/+tools/quickurl/README.org, layers/+tools/quickurl/keybindings.el, layers/+tools/ranger/README.org, layers/+tools/ranger/packages.el, layers/+tools/shell/README.org, layers/+tools/shell/packages.el, layers/+tools/transmission/README.org, layers/+tools/transmission/packages.el, layers/+tools/vagrant/README.org, layers/+tools/vagrant/packages.el
refactor key bindings for packages under +layers/tools
Several more pull requests will be created to refactor other layer groupings.
Relates to #13503
=> [applications] refactor key bindings to tools

CHANGELOG.develop, layers/+lang/go/funcs.el
=> [go] Fix search for current test function to run

CHANGELOG.develop, layers/+lang/sql/README.org, layers/+lang/sql/config.el, layers/+lang/sql/funcs.el, layers/+lang/sql/layers.el, layers/+lang/sql/packages.el
I added lsp support for [sqls](https://github.com/lighttiger2505/sqls) whiches configuration was added to lsp-mode. ( https://github.com/emacs-lsp/lsp-mode/commit/26eccfa561dc19e162a7504eefa61c83645bcaa2 )
If anyone have more better way to implement correct intends of the supporting than my code, I would like to agree it. I'm anxious about setting of lsp and company.
Thanks for great distribution Spacemacs.
=> [SQL] Add lsp support

layers/+lang/semantic-web/README.org, layers/+lang/semantic-web/packages.el
=> [semantic-web][docs] Fix layer renamed from semweb

doc/VIMUSERS.org
Related discussion:
vim migration guide: what's the way to convert keybindings which result in multiple actions? #13763
=> [doc] Document how to bind keys to a macro (one or more keys)

layers/+lang/haskell/README.org
I spent some time tracking down how to fix this since I never used Hlint before, so I thought it might be helpful to put short instructions in FAQ. I expect this to be relatively often problem, for example if project is using QuasiQuotes.
=> [layers/+lang/haskell] Added FAQ about fixing HLint parse error.

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE
All those red crosses on the PR page are too cringe.
=> Remove changelog CI check

layers/+intl/keyboard-layout/README.org, layers/+intl/keyboard-layout/config.el
I've found that this small change makes a huge difference when coding.
=> Make Colemak layout more ergonomic

CHANGELOG.develop, layers/+spacemacs/spacemacs-editing/packages.el
Not really sure if I should keep `xA` and `xm`. Those key bindings might be more useful for something else.
=> Better UX for opening and copying links

layers/+lang/haskell/README.org
First of all thanks for this awesome layer and docs :)!
I was just recently revisiting haskell layer because I wanted to improve my haskell experience in spacemacs, and I found that some things in README maybe could be better explained (especially comparison of backends) so I am creating this PR!
I also have few additional questions:
1. Why are we calling these backends "completion backends"? Most of them are doing more than just completion, they also do syntax checking, navigation, auto-fixing of errors. Is that leftover from before?
2. Why is Dante not a default backend? I get that company-ghci was chosen as default because it is lightweight and was guaranteed to work and Dante was probably not in the game yet then, but I believe Dante offers the same guarantees or working out of the …
=> [layers/+lang/haskell] Updated README with more detail about Dante + misc

layers/+lang/emacs-lisp/README.org
see title & https://github.com/syl20bnr/spacemacs/issues/13817
new to feedback, am sure I got things wrong but wanted to contribute / get the ball rolling
=> add emacs-lisp (e)debug keybindings to readme

layers/+lang/bibtex/packages.el
for more details, see https://github.com/syl20bnr/spacemacs/commit/63a42d7600fbd44fae7003242c7b211dd902d02b#commitcomment-41661412 or `org-ref-completion-library` document.
=> [bibtex] use `org-ref-completion-library' option to clean code

layers/+lang/hy/README.org
=> fix code block

layers/+lang/haskell/README.org
Fixed the typo and made the url correct
Thank you <3
=> fixed typo in haskell/README.org

.travis.yml, .travisci/pub_prep.sh
=> add cache to Travis CI

.circleci/config.yml, .circleci/shared, .github/workflows/scripts/test, .github/workflows/test.yml
=> Use GitHub Actions for testing elisp

.github/workflows/scripts/test, .github/workflows/test.yml
=> add windows test

layers/+lang/emacs-lisp/README.org
following up on feedback from https://github.com/syl20bnr/spacemacs/issues/13817
tested all of these keys rather than working from docs, should all be right now
=> Bug fix emacs lisp debug keybindings

README.md
- add alt text to html badge
- add language to code blocks in order to get syntax highlight
=> README: improve badges

doc/FAQ.org
=> Expand solution for underscores in word motions

tests/core/core-configuration-layer-ftest.el
=> [tests] skip spacelpa test on emacs26+win

.github/workflows/rebase.yml
Welp lets see if it works (as I imagine it should)
=> Add "Automatic Rebase" action

.github/workflows/scripts/dot_lock.el
Let's see if it stops those dependency installation freezes and if so come up with a better fix :thinking:
=> [tests] Catching heisenbug

layers/+tools/lsp/README.org, layers/+tools/lsp/packages.el
=> [lsp] Add support for lsp-origami

layers/+tools/pass/README.org, layers/+tools/pass/packages.el
=> [pass] Add support for auth-source-pass and password-store-otp.

layers/+fonts/unicode-fonts/README.org, layers/+fonts/unicode-fonts/config.el
Fix up some typos and suggest a few more fonts with ligature support
=> Unicode fonts layer docs

CHANGELOG.develop, layers/auto-layer.el
Resolves: [protobuf] Auto-detect protobuf files and suggest to install the protobuf layer #12767
=> Lazy install protobuf layer for .proto files

layers/+emacs/org/README.org, layers/+emacs/org/packages.el
Add toggle to enable automatic hierarchical numbering for org-mode.
=> Add toggle for org-num-mode

layers/+distributions/spacemacs-bootstrap/local/holy-mode/holy-mode.el
I missed holy-mode when updating copyright..so catching it here
=> Update copyright in holy-mode to 2020

core/core-spacebind.el, tests/core/core-spacebind-utest.el
=> fix spacebind prefixing bug

layers/+chat/rcirc/README.org
Just updated the port and set tls encryption.
=> Port fix and enabled TLS encryption

core/core-dotspacemacs.el
=> fixed typo in .spacemacs template

CHANGELOG.develop, layers/+source-control/git/packages.el
I indeed observed the slowness and this helped. It may not be necessary for every old version of Mac OS but should be harmless on them all.
=> [git] Implement performance hack for MacOS from Magit Manual

layers/+lang/purescript/README.org, layers/+lang/purescript/config.el, layers/+lang/purescript/funcs.el, layers/+lang/purescript/layers.el, layers/+lang/purescript/packages.el
I made PR because there are nothing lsp support for purescript.
But I'm not sure if this change is enough.
I am waiting for your opinions.
Thanks!
=> Add lsp support for purescript

layers/+tools/shell/funcs.el
Vterm => VTerm sorry :)
@smile13241324 @gondalez
=> fix #14100

layers/+lang/dhall/packages.el, layers/+lang/scala/config.el, layers/+lang/scala/funcs.el
Latest commit integrates the dhall layer with lsp support 
also turns the treeview in the scala layer into an option...
=> add lsp support for dhall

layers/+lang/emacs-lisp/README.org
=> Add instructions to open emacs-lisp layer README

CHANGELOG.develop, layers/+lang/clojure/README.org, layers/+lang/clojure/packages.el
Add cider inspect key bindings missing from Spacemacs
=> [clojure] add cider-inspect key bindings

layers/+tools/tide/funcs.el, layers/+tools/tide/packages.el
fix jump handler
regression introduced in https://github.com/syl20bnr/spacemacs/pull/14141
thanks @Claude-Ray for finding it out.
=> [tide] fix regression caused by e3b6464649b28f5cc048f78ace825256615814f9

layers/+spacemacs/spacemacs-editing/README.org
Just just adds the fact that evil-easymotion is integrated into the spacemacs-editing layer
=> Add evil-easymotion to the features in the README

core/core-keybindings.el
Shouldn't break anything important, except light speed :shipit:
=> Store major mode replacements in keymap (when possible).

layers/+spacemacs/spacemacs-editing/packages.el
Related to #14156
https://github.com/syl20bnr/spacemacs/pull/14156#issuecomment-744475312
cc @duianto
=> Use transient and set dired-quick-sort-suppress-setup-warning to 'message

layers/+checkers/spell-checking/README.org
I'm pretty sure this is a typo but please check before merging.
=> Fix typo in spell-checking docs

.ci/built_in_manifest, .travis.yml, .travisci/pub_auto_update.sh, .travisci/pub_prep.sh
Semi-auto updating built-in libs.
=> Auto update built-in

.travis.yml, .travisci/pub_prep.sh
Travis started to his [the new Docker quota](https://www.docker.com/increase-rate-limits?utm_source=docker&utm_medium=web%20referral&utm_campaign=increase%20rate%20limit&utm_budget=). We need a workaround.
=> Cache docker images

.travisci/pub_prep.sh
Fixing built in file list path for Travis :crossed_fingers:
=> [ci] fix path

.travis.yml, .travisci/pub_auto_update.sh
Fixing CI stuff for publishing auto updates.
=> Travis fixes

.ci/built_in_manifest
Updating the list of auto-updated files.
=> [ci] update built-in manifest

core/libs/dash.el, core/libs/ht.el, core/libs/ido-vertical-mode.el, core/libs/package-build-badges.el, core/libs/package-build.el, core/libs/package-recipe-mode.el, core/libs/package-recipe.el, core/libs/page-break-lines.el, core/libs/quelpa.el, core/libs/spacemacs-theme/spacemacs-common.el, core/libs/spinner.el, doc/DOCUMENTATION.org, layers/LAYERS.org
Merge with care - I'm just a stupid bot. Beep boop.
=> [bot] Auto-update

core/core-compilation.el, core/core-release-management.el, core/core-spacemacs.el, layers/+tools/tide/README.org
Mainly byte-compile improvements but also some text formatting.
=> Core comp2

core/core-spacemacs-buffer.el
Prepend numbers to the Recent Files list.
and bind the number keys to open that file.
Before:
After:
Fixes: Is it able to show the index of the recent files/projects in spacemacs home page? #12519
And possibly: Improve keybindings on spacemacs buffer (home buffer) #14230
=> Add home buffer recent files numbers

layers/+spacemacs/spacemacs-evil/config.el
Hopefully ;) or at least the RET key binding. I use `ranger` so I can't tell this will cover all the cases.
=> [evil-collection] support for dired

CHANGELOG.develop, layers/+lang/ess/packages.el
=> ESS: Fixes #13282

core/core-spacemacs-buffer.el
Define named functions: spacemacs-buffer/jump-to-...
for the home buffer shortcuts. So that a descriptive name is shown,
in for example the view-lossage (C-h l) buffer.
Before:
```
r                      ;; anonymous-command
p                      ;; anonymous-command
```
After:
```
r                      ;; spacemacs-buffer/jump-to-recent-files
p                      ;; spacemacs-buffer/jump-to-projects
```
=> Add home buffer named shortcuts functions

core/core-spacemacs-buffer.el
=> [core] Refactor spacemacs-buffer//do-insert-startupify-lists

layers/+emacs/org/packages.el
That's too long for too much space.
Cheers!
=> diminish valign

layers/+lang/javascript/README.org, layers/+lang/javascript/packages.el
Add [npm-mode](https://github.com/mojochao/npm-mode) to the javascript layer.  This allows easy execution of npm
commands at the project root from any javascript file in the project.
=> [javascript] add npm-mode

layers/+spacemacs/spacemacs-defaults/funcs.el
=> Refactor spacemacs/rename-current-buffer-file

layers/+lang/elm/README.org
There is no such NPM package named elm-analysis, but there is an elm-analyse.
=> Change NPM package elm-analysis -> elm-analyse in the elm-layer README

core/core-compilation.el, core/core-spacemacs.el, init.el
This way orphaned .elc files won't be a problem.
=> Better .elc cleanup

layers/+lang/markdown/packages.el
Fix warning message for #14387.
=> [markdown] fix warning message for #14387

CHANGELOG.develop, layers/+tools/lsp/README.org, layers/+tools/lsp/config.el, layers/+tools/lsp/packages.el
- lsp-ui is very opinionated so better to have it enabled/installed on demand
=> [lsp] Do not include lsp-ui by default

layers/+tools/lsp/README.org
=> fix variable name in lsp doc

core/core-spacemacs-buffer.el
Pressing a number key on the Spacemacs home buffer,
doesn't reliably open the expected recent file.
The number keys are bound to open the files in the
order they are listed in the `recentf-list`.
The `recentf-list` is updated when a file is saved.
The home buffers recent files list is only updated
when the home buffer is created/refreshed/resized.
Open the recent files in the order they were listed
when the home buffer was last updated.
Fixes: incorrect order number in recent files on home buffer #14471
=> Open home buffer recent files in expected order

CHANGELOG.develop, layers/+readers/pdf/README.org, layers/+readers/pdf/packages.el
I think restore last visited page should probably be the default in a pdf-viewer. [pdf-view-restore](https://github.com/007kevin/pdf-view-restore) does it simple and fine.
=> Add pdf-view-restore to pdf layer

CHANGELOG.develop, layers/+emacs/org/README.org, layers/+emacs/org/config.el, layers/+emacs/org/packages.el
=> [org] Add org-appear support

layers/+spacemacs/spacemacs-layouts/funcs.el
Macro `spacemacs|define-custom-layout` requires `name` argument and `:binding` property **bound** if they are symbols. If one of them is not defined before calling this macro, an error message
```
Eager macro-expansion failure: (void-variable <layer name>-spacemacs-layout-name)
```
will come out in `*Messages*` buffer.
Macro `spacemacs|define-custom-layout` will check if both `name` and `binding-prop` are not unbound symbols, otherwise, do nothing.
Fix: #8363
=> Ensure required arguments of macro spacemacs|define-custom-layout are all defined.

CHANGELOG.develop, layers/+lang/emacs-lisp/README.org, layers/+lang/emacs-lisp/packages.el
Added Edebug Eval List key bindings.
=> Add Edebug Eval List key bindings

core/core-dotspacemacs.el
fixes syl20bnr#14535 syl20bnr#14537 syl20bnr#14529 syl20bnr#10638 (comment)
=> fixup! Validate .spacemacs variables.

core/core-spacemacs-buffer.el
Added support for jumping to two digit numbers.
How quickly two numbers have to be typed,
can be modified with the variable:
`spacemacs-buffer-multi-digit-delay`
---
The file/dir opens as soon as the idle timer runs (default `0.4` seconds).
While typing: `Jump to startup list: <nr>` 
If the startup list number isn't found: `Couldn't find startup list number: <nr>`
When the number matches a startup list line: `Opening file/dir: <nr> <file or dir name>`
=> [home] Add multi-digit numbers to the startup lists

CHANGELOG.develop, layers/+email/mu4e/packages.el
=> Revert "Fix void variable `mu4e-view-mode-map`" to fix issue #14548

layers/+lang/haskell/funcs.el, layers/+lang/haskell/packages.el
=> fixup! haskell: refactor

layers/+lang/c-c++/config.el, layers/+lang/c-c++/funcs.el, layers/+lang/c-c++/layers.el, layers/+lang/c-c++/packages.el
This reverts commit e62d55b4fdc04b3c2a1cfb88b978a420cf1b94fe.
This fixes https://github.com/syl20bnr/spacemacs/pull/14509#issuecomment-813023508
=> fixup! c-c++: refactor

.github/workflows/rebase_on_push.yml
Rebase  PR when develop branch gets updated.
=> [CI]rebase PRs on develop push

.github/workflows/rebase_on_push.yml
Seems like it needs more arguments or something :thinking:
=> [CI]try fixing rebase workflow

.github/workflows/rebase_on_push.yml
=> [CI]try fixing rebase workflow X2

README.md
=> docs: fix ‘gzip-for-windows’ link error

layers/+lang/python/README.org
* Document how to make Nix + Microsoft LSP work
* Add links to Microsoft LSP and Pyright repos
=> [Python layer] Add links to the LSP implementations

core/core-early-funcs.el, core/core-spacemacs.el, early-init.el
Can provide a smoother startup by reducing graphical artifacts.
=> [init] Disable GUI elements in early-init as well

CHANGELOG.develop, layers/+lang/zig/README.org, layers/+lang/zig/config.el, layers/+lang/zig/funcs.el, layers/+lang/zig/layers.el
Add support to LSP via zls (see also https://github.com/emacs-lsp/lsp-mode/pull/2723)
=> Enhance +lang/zig layer

layers/+emacs/org/README.org
Links should have GitHub style.
=> Make TravisCI happy.

README.md
=> Align badges

layers/+web/eww/README.org
=> Fix ewww docs

layers/+misc/nav-flash/README.org, layers/+misc/nav-flash/config.el, layers/+misc/nav-flash/funcs.el, layers/+misc/nav-flash/packages.el
=> [new layer] nav-flash

layers/+lang/ocaml/packages.el
Made a mistake in #14691 moving some code around after I tested it.
Oops.
=> [ocaml] Fix typo

layers/+window-management/exwm/config.el, layers/+window-management/exwm/funcs.el, layers/+window-management/exwm/packages.el
*  Add the proprer header to layer files
*  Remove unnecessary `cl-generic` from `exwm-packages`
*  Replace `defvar`s with `defcustom`s in `config.el`
=> Fix issues with EXWM layer

layers/+window-management/exwm/README.org
=> fix exwm readme

layers/+window-management/exwm/README.org
It was more screwed than I realized.
=> [doc]fix the rest of exwm readme hls

layers/+lang/scheme/README.org, layers/+lang/scheme/packages.el
Additionally this commit fixes(corrects) the register-repl command.
=> Scheme layer, add REPL keybindings

layers/+lang/scheme/packages.el
=> [scheme] Fix geiser company backends

layers/+intl/keyboard-layout/packages.el
=> Revert "[keyboard-layout] Fix colemak-hneio next/prev line in magit"

core/core-spacemacs-buffer.el
Show the first 5 lines of the home buffer notes:
Quick Help and Release Notes.
Added a button to show the full note.
---
=> [home] Show notes preview, with full note button

layers/+readers/pdf/README.org
Reflect change in maintainership to current maintained repo:
https://github.com/vedang/pdf-tools
Cheers!
=> [pdf] Update pdf-layer documentation (#14791)

layers/+source-control/git/packages.el
fixes the warning https://github.com/syl20bnr/spacemacs/pull/14825#issuecomment-855208034
=> fixup #14715

layers/+lang/scheme/packages.el
=> Small fix: unquote keymap symbols in scheme layer

CHANGELOG.develop, README.md
Fix dead link. Addresses #14860.
This is meant to replace #14871 since the original author had closed the PR. Addressing the open change request by @lebensterben, I credited the author of the page that the original link referenced to because I feel that it is important to give credit where it is due.
=> [Readme] Fix link

.circleci/config.yml, .circleci/org/export, .circleci/org/validate, .circleci/update/maybe_pr, .circleci/update/upd_built_in
Fixing CI stuff... Boring stuff.
=> [ci] Fix CircleCI stuff

.circleci/config.yml, .circleci/shared, .circleci/update/upd_built_in
Tidy stuff up. Also there was a typo.
=> [ci] move bot init into separate file

.circleci/bot_init, .circleci/config.yml
Forgot to add this file :face_with_head_bandage:  :palm_tree:
=> [ci] add init script for bot

.circleci/config.yml
=> [ci] Reorder steps in CircleCI for built-in upd

.circleci/config.yml, .circleci/update/maybe_pr
=> [ci] clean-up

.circleci/apply_patch
Forgot to update the path...  I'm not even surprised by this point.
=> [ci] fix patch name

.circleci/built_in/maybe_pr, .circleci/org/maybe_pr, .circleci/push
This way it should be easier to debug 🤔
=> [ci] Don't mask push  outputs (CircleCI masks secrets anyway)

.circleci/config_tmpl.yml
Looks like cron jobs don't run for generated configs (for now?)  so we'll gonna update them on develop branch push.
=> built-in cron workaround

.circleci/apply_patch, .circleci/config_tmpl.yml, .circleci/make_patch, .circleci/maybe_pr, .circleci/org/update_docs, .circleci/web/htmlize
=> [ci] refactor

.circleci/make_patch, .circleci/org/update_docs, .circleci/push, .circleci/shared
Lets see why LAYERS.org doesn't get updated.
=> [ci] testing stuff

.circleci/config_tmpl.yml, .circleci/make_patch, .circleci/maybe_pr, .circleci/web/.spacemacs, .circleci/web/htmlize, .circleci/web/install_deps
Moving web updating scripts to CircleCI
=> [ci] port html export to CircleCI

.circleci/config_tmpl.yml
Cache deps  to speedup things.
=> [ci] cache deps for web export

doc/DOCUMENTATION.org, layers/+music/tidalcycles/README.org
=> [doc] fix links

.circleci/push
Random failures on push drives me crazy...  We gonna need the logs here,
=> [ci] unmask hub push logs

.circleci/push
Last commit I added explanation comment but forgot to actually unmask it :D
=> [ci] actually unmask the logs

layers/+completion/compleseus/README.org, layers/+completion/compleseus/config.el, layers/+completion/compleseus/funcs.el, layers/+completion/compleseus/layers.el, layers/+completion/compleseus/local/compleseus-spacemacs-help/compleseus-spacemacs-help.el, layers/+completion/compleseus/packages.el, layers/+completion/helm/layers.el, layers/+spacemacs/spacemacs-layouts/funcs.el, layers/+spacemacs/spacemacs-layouts/packages.el
Built on consult embark orderless selectrum/vertico.
It's been working ok. Basic features are in, let's merge it and let our community
improve it together :)
thanks @iyefrat for the cool name and his Doom counterpart which I took some for vertico
Things to do next:
- docs
- ...
=> [compleseus] new completion layer built on consult, embark, orderless and selectrum/vertico

layers/+completion/ivy/README.org
regarding the modifier for transient mode
Cheers!
=> fixed a small typo in the ivy docu

layers/+lang/plantuml/README.org
=> plantuml layer supports .puml extension

layers/+completion/ivy/funcs.el, layers/+completion/ivy/packages.el
=> [ivy] add open in other window for ivy-xref

layers/+spacemacs/spacemacs-defaults/packages.el
Image-dired is a quite nice image browser, but its modes really should open in evilified state.
=> Evilify image-dired-thumbnail/display-image-mode-(map)s

layers/+completion/compleseus/funcs.el, layers/+completion/compleseus/packages.el
consult-line-multi bindings: `spc s b` and `spc s B`
=> [compleseus] add consult-line-multi

layers/+lang/shell-scripts/README.org, layers/+lang/shell-scripts/config.el, layers/+lang/shell-scripts/packages.el
Add a configuration option for formatting shell scripts using shfmt.
=> [shell-scripts] Add shell-scripts-format-on-save

layers/+emacs/org/README.org, layers/+emacs/org/packages.el
=> Evilify and add follow link (hint) keybinding to org-roam buffer

layers/+os/nixos/README.org, layers/+os/nixos/config.el, layers/+os/nixos/packages.el
This new feature will probably require updating `nix-mode`.
=> [nixos] Add nixos-format-on-save

CHANGELOG.develop, layers/+lang/purescript/README.org, layers/+lang/purescript/config.el, layers/+lang/purescript/funcs.el, layers/+lang/purescript/packages.el
This PR adds support for formatting purescript sources using [purs-tidy](https://github.com/natefaubion/purescript-tidy).
=> Add purescript formatting support

layers/+lang/java/README.org, layers/+lang/java/funcs.el, layers/+lang/java/packages.el
just some small improvement to java layer. Removed some obsolete commands and added some. Tag @yyoncho for review
=> [java] improve binding for lsp-java

COPYRIGHT
This file includes copyright information for third-party packages/snippets
which have contents without explicit license notice.
=> Added COPYRIGHT file

CHANGELOG.develop, layers/+tools/fasd/funcs.el, layers/+tools/fasd/packages.el
Fasd & open the item in a layout
=> fasd layer: fasd & open in a layout

layers/+lang/go/README.org
See https://golang.org/doc/go-get-install-deprecation
=> Update go layer docs since go get is deprecated

layers/+completion/compleseus/README.org
This adds the docs for customizing the compleseus engine
=> Add to the docs for compleseus about selecting a completion engine

CHANGELOG.develop
follow-up for #15135 with stray leading space in CHANGELOG.develop
=> follow-up for #15135 with stray leading space in CHANGELOG.develop

doc/CI_PLUMBING.org
=> [doc] clean up

core/core-dotspacemacs.el
I didn't add anything to CHANGELOG.develop. I don't think this change warrants a bullet point and I don't mind not being on the contributors list.
=> Fix typo doftile->dotfile

core/core-documentation.el
Fighting entropy :middle_finger:
=> [ci] fix html export

core/core-documentation.el
Well that took some time for somereason.
=> Fix web export

layers/+completion/compleseus/packages.el, layers/+spacemacs/spacemacs-layouts/funcs.el
- update setup for vertico-repeat
- add vertico-{quick, directory}
- bind embark-export to C-c C-o
- layout select current project first
=> [compleseus] improve

layers/+completion/ivy/README.org, layers/+completion/ivy/packages.el
Feel like a dud :)), `ivy` has been able to select and act on multiple candidates for ages just like `helm` and I just discovered it recently.
=> [ivy] add mark unmark bindings

layers/+source-control/git/README.org, layers/+source-control/git/packages.el
Changes upstream in Evil Collection. Fix https://github.com/syl20bnr/spacemacs/issues/15162.
Cheers!
=> Fix forge evil keybinds

CHANGELOG.develop, layers/+lang/markdown/README.org, layers/+lang/markdown/packages.el
To make it consistent with Org layer :slightly_smiling_face:
=> Add binding for markdown-table-align

core/libs/quelpa.el, core/libs/spacemacs-theme/spacemacs-common.el, core/libs/spacemacs-theme/spacemacs-theme-pkg.el
Reverts syl20bnr/spacemacs#15272
It shouldn't be merged in the first place because it removed quelpa.el!
=> Revert "[bot] built_in_updates"

layers/+emacs/org/packages.el
fixed #15290
co-authored-by: xin <etimecowboy@gmail.com>
=> org: fix #15290

core/core-spacemacs.el
fixes #12105
co-authored-by: "ruquan.chen" <ccruquan@gmail.com>
=> core-spacemacs: fix daemon font size

layers/+spacemacs/spacemacs-layouts/packages.el
fix a typo from a recent commit, probably https://github.com/syl20bnr/spacemacs/pull/15278
=> [layouts] fix counsel-projectile

layers/+spacemacs/spacemacs-defaults/config.el, layers/+spacemacs/spacemacs-defaults/funcs.el
This reverts commit d33a1a8fcc11f68195f70af437b84c6c522a3a3a.
=> Revert "spacemacs-defaults: Added prompt to save a buffer (#15297)"

layers/+os/osx/keybindings.el
=> Fix ⌘-s shortcut in macOS

layers/+spacemacs/spacemacs-defaults/funcs.el
- Added a new function `spacemacs//confirm-kill-buffer` which prompts the user
to save a buffer to a file before killing it.
- Added the said new function to the buffer-local `kill-buffer-hook` of scratch
buffer and any buffer created via command `spacemacs/new-empty-buffer`.
closes https://github.com/syl20bnr/spacemacs/issues/12857
=> spacemacs-defaults: Prompt to save a buffer for certain operations

CHANGELOG.develop, layers/+emacs/org/README.org, layers/+emacs/org/config.el, layers/+emacs/org/packages.el
I am new to `org-transclusion` and somewhat inexperienced at adding new packages and coming up with keybindings, so I'm very open to feedback.
=> [org] add support for transclusion

CHANGELOG.develop, layers/+lang/emacs-lisp/packages.el
this package provide highly accurate jump to the definition, it even works with
local variable
=> [elisp] add elisp-def

layers/+tools/tree-sitter/README.org, layers/+tools/tree-sitter/config.el, layers/+tools/tree-sitter/funcs.el, layers/+tools/tree-sitter/packages.el
Add option to disable tree-sitter-hl on some modes.
=> [tree-sitter] add option to seletively disable tree sitter hl mode

CHANGELOG.develop, layers/+completion/auto-completion/README.org, layers/+completion/auto-completion/config.el, layers/+completion/auto-completion/packages.el
Add `company-posframe` https://github.com/tumashu/posframe
=> [auto-completion] add company-posframe

layers/+spacemacs/spacemacs-org/packages.el
I'm pretty sure we can remove this FIXME.
=> Remove disabled code and FIXME: resolved.

layers/+lang/python/README.org
This fixes a broken link in the python layer docs.
=> python: Fix broken link

CHANGELOG.develop, layers/+spacemacs/spacemacs-defaults/keybindings.el, layers/+tools/translate/README.org, layers/+tools/translate/funcs.el, layers/+tools/translate/keybindings.el, layers/+tools/translate/packages.el
New layer `translate` for doing article translation jobs.
=> Add layer `translate` for doing translation jobs

layers/+completion/compleseus/config.el, layers/+completion/compleseus/funcs.el, layers/+completion/compleseus/packages.el
- update vertico-repeat
- annotation for projectile
- tweak xref
- new buffer source of modified ones
- vertico settings
- use consult-org-heading
- tweak orderless
- tweak consult-line to start from top to bottom
- tweak marginalia
- tweak orderless for company and lsp
- fix persp mixing up buffer-list order
=> [compleseus] update

layers/+chat/jabber/packages.el, layers/+completion/helm/packages.el, layers/+distributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el, layers/+fun/emoji/packages.el, layers/+fun/games/packages.el, layers/+fun/xkcd/packages.el, layers/+intl/chinese/packages.el, layers/+lang/clojure/packages.el, layers/+lang/elm/packages.el, layers/+lang/factor/packages.el, layers/+lang/haskell/packages.el, layers/+lang/python/packages.el, layers/+os/osx/packages.el, layers/+readers/pdf/packages.el, layers/+source-control/version-control/packages.el, layers/+spacemacs/spacemacs-navigation/packages.el, layers/+tools/finance/packages.el, layers/+tools/prodigy/packages.el, layers/+tools/tide/funcs.el, layers/+vim/vinegar/packages.el
This PR simply adds the obsoletion notification as proposed in #14388.
=> Add obsoletion notification evilified-state-evilify

CHANGELOG.develop, layers/+lang/scala/README.org, layers/+lang/scala/funcs.el, layers/+lang/scala/packages.el
Next logical step after #15372 and #15160 .
=> [scala] add keybinding for running `It / compile` in SBT

layers/+lang/shell-scripts/README.org
see https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/shell-scripts/config.el#L28 for rationale
=> [doc] shell-scripts: explain backend auto-select

layers/+tools/finance/packages.el
Just a small fix to a bug that occurs on init
=> [finance] Fix void-variable ledger-report-mode-map

layers/+email/mu4e/packages.el
=> Use a different require on newer mu versions.

doc/FAQ.org
At least on my machine, SPC u M-x works fine and repeat pasting works as well.
=> Remove obsolete documentation in FAQ.org.

layers/+completion/compleseus/packages.el, layers/+spacemacs/spacemacs-layouts/funcs.el
make tramp completion work and  layout recognize remote project.
=> [compleseus] work with tramp

layers/+completion/compleseus/packages.el
=> [compleseus] fix hack for company-capf

layers/+lang/major-modes/packages.el
=> [major-modes] move gemini-mode source to MELPA

README.md
=> README: rewrite

core/core-dotspacemacs.el
This commit improved the sections regarding `dotspacemacs-director`
and `dotspacemacs-filepath`.
=> core-dotspacemacs: cleaning up

layers/+spacemacs/spacemacs-editing-visual/packages.el
@pradyparanjpe
@psisis 
Please pull in this PR and try out.
=> spacemacs-editing-visual: fix #15667

core/core-dotspacemacs.el, layers/+completion/compleseus/packages.el
https://github.com/syl20bnr/spacemacs/pull/15710 confused
hybrid-style-enable-evilified-state and hybrid-style-enable-hjkl-bindings
=> compleseus: use the correct predicate for minibuffer hjkl bindings

layers/+readers/pdf/packages.el
Quite surprisingly, PR #15736 mostly seemed to work already. However, obviously the second lambda requires an argument list also.
=> Fix PR #15736

layers/+checkers/syntax-checking/README.org, layers/+lang/groovy/README.org, layers/+lang/raku/README.org, layers/+lang/rust/README.org, layers/+spacemacs/spacemacs-defaults/funcs.el, layers/+spacemacs/spacemacs-project/funcs.el, layers/+themes/colors/README.org
=> chore: remove repetitive words
