syl20bnr/spacemacs

contrib/git/config.el

Git layer will fail to load if there is no this variable

defvar `git-enable-github-support`

---

contrib/lang/scala/funcs.el
contrib/lang/scala/packages.el

Adds some stuff that's been in my private config for the last month.
* Automatically start ensime server when there is a `.ensime` file in this project
* Bind goto-definition commands to `M-.` and `M-,`, SLIME-style
* Fix an interaction bug when inserting a `.` while completions are being displayed.
* Automatically display types in minibuffer using eldoc

Ensime tweaks

---

contrib/auctex/packages.el
contrib/auto-completion/funcs.el
contrib/auto-completion/packages.el
contrib/finance/packages.el
contrib/lang/c-c++/packages.el
contrib/lang/csharp/config.el
contrib/lang/csharp/packages.el
contrib/lang/ess/config.el
contrib/lang/ess/packages.el
contrib/lang/go/config.el
contrib/lang/go/packages.el
contrib/lang/haskell/config.el
contrib/lang/haskell/packages.el
contrib/lang/html/packages.el
contrib/lang/javascript/config.el
contrib/lang/javascript/packages.el
contrib/lang/python/config.el
contrib/lang/python/packages.el
contrib/lang/ruby/packages.el
contrib/ycmd/packages.el
spacemacs/funcs.el

Adds a helper macro for handling the simple cases of adding company backends and uses that for many of the existing layers as well as porting over some new layers to the auto-completion infrastructure with it. The macro is designed for replacing copy-paste initialization of auto-completion in the common simple cases. It replaces 5 lines in 3 separate locations with one line in one location.
I used this macro to port the modes listed in #1045 to the new infrastructure as well as fixing some bugs in c-c++ (the hook was wrong and ycmd didn't load). All these new modes have been tested to work except I couldn't test company-omnisharp (I don't have C#) but that is basically the same as many others that work.
This PR also includes #1082 but doesn't actually rely on it AFAIK. It's just in here …

Make everything support new company auto-completion

---

contrib/auctex/packages.el
contrib/auto-completion/packages.el

Institutes a temporary measure @syl20bnr and I discussed to allow company autocomplete to work in modes that have not yet been ported to the new architecture. Basically just enables company globally and patches up auctex. This might enable an earlier release (see #1046).
I have tested and this fixes all the problems I listed in #1045, except Racket (see #1081 :rage:).
Also solves #1043.

Global company temporary stopgap

---

core/core-spacemacs-buffer.el

Otherwise when the widget list is deleted to insert new widgets, the
separator "widget" is essentially text with properties and can cause
error when trying to delete it, which breaks quick help and release note
buttons, making the buttons not function anymore.

[Emergency fix] Don't add separator to the widget list

---

spacemacs/packages.el

I believe this PR should fix most if not all issues regarding #2421 and the `global-mode-string`. See my comments in #2421 for explanation.
Please @robbyoconnor and @CestDiego try it out and report back. If you get a blank modeline, copy the value of `global-mode-string` in here so I can have a look.

Fix global-mode segment

---

contrib/!lang/latex/README.org

This is related to #2464 -- it adds an update for the README and adds for [company-auctex](https://github.com/alexeyr/company-auctex) and [company-math](https://github.com/vspinu/company-math).

Update README for latex layer to include the company-math addition

---

contrib/osx/keybindings.el
contrib/osx/packages.el

reveal-in-finder was renamed to reveal-in-osx-finder.
See also
- https://github.com/milkypostman/melpa/commit/2bf40285279b761b0efd6bc8542ae9aad4b329e1
- https://github.com/kaz-yos/reveal-in-osx-finder/commit/5710e5936e47139a610ec9a06899f72e77ddc7bc

Update package name

---

contrib/!lang/clojure/packages.el

Currently, the major-mode specific keybindings are not active when editing .cljc, .cljs or .cljx files, because dedicated modes for ClojureScript, ClojureC and ClojureX were introduced
in clojure-emacs/clojure-mode@20356bc.

Set clojure-mode keybindings for derived modes

---

core/core-configuration-layer.el

GNU is having issues with SSL. Use HTTP for now. 
Fixes #2596

Change elpa to use http.

---

spacemacs/local/hybrid-mode/hybrid-mode.el

Without this fix enabling hybrid mode when running Emacs from terminal gives the following error:
```
Error (use-package): hybrid-mode :init: Wrong type argument: listp, hbar
```

hybrid-mode: fix running Emacs from terminal

---

layers/+distribution/spacemacs-core/funcs.el
layers/+distribution/spacemacs-core/local/hybrid-mode/hybrid-mode.el

Was deleted from spacemacs layer in https://github.com/syl20bnr/spacemacs/commit/b45911f3d538538e33b0ad86e81a6b1d4a095cc0, but wasn't added to spacemacs-core layer. This adds it to spacemacs-core.
Fixes #2980

Adding back hybrid-mode.el

---

layers/better-defaults/funcs.el

spacemacs/backward-kill-word-or-region: handle rectangular selection correctly

---

layers/+source-control/git/packages.el

Also turn off evilification for magit conditional on the evil-magit
package being used.

git: Add new evil-magit bindings

---

layers/+vim/evil-snipe/packages.el

This just adjusts 4e302bc0c039b7f25e0768abd78d52c5e5cdd653 to use the appropriate turn-off functions for evil snipe

evil-snipe: Use separate hooks for override mode

---

layers/+distribution/spacemacs-base/local/helm-spacemacs/helm-spacemacs.el

I added some faces. Also show leader keybinding for toggles, and I reversed the order for packages (the leftmost thing should be what you are primarily searching for). This means that the packages are not ordered by layer any more, but I think it's okay like this. I also refactored the FAQ source a bit since some of the lines were getting long.
The light blue you're seeing is `font-lock-type-face` and the dark gray is `font-lock-doc-face`. For the keybindings I went with the `helm-M-x` standard key face. I can change this of course if it turns out that these are terrible choices for some themes. We could also define our own faces.

Helm-spacemacs facelift

---

core/core-configuration-layer.el

The archive name must be a name.
Fixes `SPC a P`.

Fix type error in package-archives

---

layers/org/README.org
layers/org/packages.el

This PR evilifies the org agenda buffer, and (in a more manual sense) the minibuffer setup you get when you insert a timestamp (`C-c .`). It also sets by default so that org-agenda doesn't destroy the window setup.

More org goodies

---

layers/finance/packages.el

Key definitions no longer need to be prefixed with "m".

Fix major mode bindings for finance layer.

---

core/core-keybindings.el
core/templates/.spacemacs.template
layers/+distribution/spacemacs-base/packages.el
layers/+distribution/spacemacs/packages.el
layers/+lang/haskell/packages.el
layers/+lang/latex/README.org
layers/+lang/latex/extensions.el

Before this `<tab> => TAB` if there is no binding for `<tab>`, but then
`spacemacs/translate-C-i` turned this into `<C-i>`, which we don't want
because that would mean having to always bind `<tab>` when this option is
enabled. This commit adds a check to make sure we can't possibly be
translating from `<tab>` originally (we only want to capture the `C-i`
events in the GUI).

keys: Fix an issue with C-i/tab distinction

---

README.md

As suggested in #4000, make clear that Emacs 25 is only partially
working.

Update the README for Emacs 25 being buggy

---

layers/+lang/c-c++/config.el
layers/+lang/c-c++/funcs.el
layers/+lang/c-c++/packages.el

Since #2635 is defunct I'm opening this new PR based on copy-pasting from the diff from the old one. Can someone tell me if I did the rebase properly?
Fixes #1258.
Thanks to @zhengyangfeng00 for the original PR.

Fix flycheck clang args loading

---

layers/+distribution/spacemacs-base/funcs.el

I just stumbled over this.  I'm not sure why it was done this way, but I think it's wrong.  As per documentation, `system-type` holds a symbol denoting the OS type, and I see no reason to treat it as string for comparison.

Compare system-type as symbol

---

core/core-spacemacs.el
layers/+distribution/spacemacs/packages.el

Background: `C-i` and `TAB` are the same keycode for historic reasons.
With the current settings, evil [1] and evil-jumper [2] associate
`jump-forward` to `C-i` (==`TAB`), what overrides bindings set to
`TAB` (==`C-i`) in terminal mode, like `orc-cycle`. To fix this,
this commit:
- Set `evil-want-C-i-jump` to `nil`, to prevent `evil` and `evil-jumper`
to use the `C-i` (==`TAB`) keycode.
- Remove the spacemacs' code that bind `jump-forward` to `TAB`(==`C-i`)
The current spacemacs code already rebind `jump-forward` to the GUI-only
`<C-i>` keycode.
[1] https://bitbucket.org/lyro/evil/src/082bd65cccee9f5aa4d342c3b2921865175914af/evil-maps.el?fileviewer=file-view-default#evil-maps.el-323
[2] https://github.com/bling/evil-jumper/blob/efaa841ca4489aa7fd8edaa50d8a63b059530366/evil-jumper.el#L241 …

Use jump-forward `C-i` binding only in GUI mode

---

layers/+distribution/spacemacs/packages.el

To address #4720. The change is to bind `p` to `spacemacs/quick-ahs-backward` for finding
previous match. This is mostly for non-Evil users.
Thanks for reviewing in advance.

Key bindings: additional key binding for symbol-highlight (p for finding previous match)

---

layers/+lang/python/packages.el

Fix pylookup binding
https://github.com/syl20bnr/spacemacs/issues/5220

Fix pylookup binding

---

layers/+spacemacs/spacemacs-completion/packages.el

For those of us who hate echo-in-input-line.

Move helm setq out of with-eval-after-load

---

layers/+spacemacs/spacemacs-ui-visual/funcs.el

This prohibits a crash when powerline is excluded in dotspacemacs-additional-packages.

fix startup crash if powerline is excluded

---

core/core-configuration-layer.el

I had a duplicated layer, but the message that's printed broke spacemacs starting up because it was a format string but wasn't in a `format` form. Simple fix. Spacemacs works again! Yay!
This issue was introduced in https://github.com/syl20bnr/spacemacs/commit/c0851ddcb3cd0f18e41c37f7bfe6b195117f3e27, according to a quick `git bisect`. :)

Fix duplicated layer string format error

---

layers/+distributions/spacemacs-base/packages.el
layers/+emacs/org/packages.el

As @syohex pointed out, `outline-show-all` was introduced in Emacs 25.1. Shouldn't we use `show-all` instead which is aliased to `outline-show-all` in Emacs 25.1 (not by Spacemacs though, but in `outline.el`).
Also, am I missing relation between `org` and `outline`? I mean, why `(with-eval-after-load 'org ...)`? Because of this I moved code back to `spacemacs-base` layer.
Fixes #6500

fix call to show-all

---

layers/+spacemacs/spacemacs-ui-visual/funcs.el

Small typo in the docstring for `spacemacs/disable-smooth-scrolling`.

Fix typo in docstring

---

layers/+source-control/github/README.org

The docs weren't correct. This corrects them.

Fix magit-gh-pulls docs since #g isn't defined

---

layers/+completion/ivy/packages.el

We're already defining `SPC p p` to `counsel-projectile` [here](https://github.com/syl20bnr/spacemacs/blob/5c371f0843ccdbeee3d7d1b7405f201dd43463bc/layers/+completion/ivy/packages.el#L116). This change removes the extra binding since `counsel-projectile` has much more options. 
Fix #6577

ivy: remove extra projectile-switch-project binding

---

core/core-configuration-layer.el

An upstream issue with Emacs causes local file urls to incorrectly be interpreted as FTP addresses on Windows, see #6602.
cc @d12frosted

Fix #6602, Use Quelpa file fetcher instead of url for local packages

---

layers/+lang/haskell/README.org

Noticed some typos while reading. Corrected them quickly.

Fix typos in Haskell layer README

---

layers/+spacemacs/spacemacs-ui/packages.el

"Open junk file" is duplicated in the docstring.

Remove duplicated words in docstring

---

doc/LAYERS.org

Fix references to declare-used-layer(s) in docs

Fix references to declare-used-layer(s) in docs

---

layers/+os/osx/README.org
layers/+os/osx/config.el
layers/+os/osx/packages.el
layers/+spacemacs/spacemacs-language/packages.el

Why?
- Offline hence fast
- Definitions are better than default(wordnet?)
- Pronunciation
How does it look?

osx: add osx-dictionary and make it default for OS X

---

layers/+completion/ivy/packages.el

As the tip says: ‘ivy-recentf’ is an obsolete command (as of 0.8.0); use ‘counsel-recentf’ instead.

Replace "ivy-recentf" with "counsel-recentf"

---

layers/+spacemacs/spacemacs-ui/packages.el

4b2f123 recently removed a workaround which according to the comment was fixing some window-numbering bug. I just reapplied the workaround as it broke my emacs.
While it was working nice on my computer at work, it broke everything on my personal laptop: when trying to quit emacs, it wouldn't, but instead all commands would only split windows.
After manually sigterming the frame, I still had to use sigkill to get rid of the emacs process taking 100% CPU.

re-fix window numbering bug

---

layers/+spacemacs/spacemacs-language/packages.el

Fix `Symbol's value as variable is void: osx-use-dictionary-app` when
not using osx layer.
Check: https://github.com/syl20bnr/spacemacs/commit/047b57223a8913699bc9ce52aa3046d934f40c9f#commitcomment-18905104
Fix: #7042

fix void variable when not using osx layer

---

layers/+lang/d/README.org
layers/+lang/d/packages.el

Add `company-dcd` package that uses DCD (a completion daemon for D) to
provide better IDE features:
- Better code completion.
- Jump to definition.
- Search symbol references.

Add more features for D language

---

layers/+lang/elixir/packages.el

Fix a typo introduced in 42a33f3ae8c58b8f416207e6d553dbcbd78e5385

Fix a typo introduced when setting up org-babel support

---

layers/+lang/plantuml/README.org
layers/+lang/plantuml/packages.el

As soon as [this PR](https://github.com/melpa/melpa/pull/4324) gets merged, the [agreed merge](https://github.com/zwz/plantuml-mode/issues/8) between [skuro/puml-mode](https://github.com/skuro/puml-mode) and [zwz/plantuml-mode](https://github.com/zwz/plantuml-mode) will be finalized.
The code provided here updates the relevant pointers to move to [the new home](https://github.com/skuro/plantuml-mode) of the one and only maintained PlantUML emacs mode.
With <3,
c.

Updated the plantuml plugin to use `plantuml-mode` instead of the now deprecated `puml-mode`

---

layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin/spacemacs-purpose-popwin.el
layers/+spacemacs/spacemacs-purpose/packages.el

https://github.com/syl20bnr/spacemacs/issues/7439

Fix spacemacs-purpose-popwin name

---

layers/+spacemacs/spacemacs-purpose/packages.el

`purpose-x-kill-setup` enables purpose's "kill" extension, which makes `kill-buffer` aware of purpose when looking for a new buffer to display in a window instead of the killed buffer. This is done by overriding `replace-buffer-in-windows`, and recently I have noticed that it can slow down some operations, so we should not enable it by default.
<s>Probably</s> fixes #7460

purpose: disable kill extension

---

core/core-configuration-layer.el
core/core-dotspacemacs.el
core/core-spacemacs-buffer.el
core/core-spacemacs.el

The first commit stores the value of `dotspacemacs/layers` immediately after calling the function, and adds a check in `spacemacs-post-user-config-hook` to check if the value was changed. If it was, it issues a warning. (Note, the comparison is done with `eq`, not `equal`.) It also uses the saved value when reporting an issue.
The second commit shows warnings as a non-removable startup list.
Example:

Higher visibility warnings + check if layers changed outside dotspacemacs/layers

---

doc/DOCUMENTATION.org

Some minor mistakes and typos I found while reading through the documentation (I recently decided to switch from Vim to Spacemacs on my laptop and it's awesome so far! Good job guys :smile:).
PS: I didn't document the exact changes in my commit message/PR since looking at the diff/changes should be easier anyway (imho). But I could do that ofc if requested/recommended.

Fix some minor mistakes and typos in the documentation

---

core/templates/.spacemacs.template

https://github.com/syl20bnr/spacemacs/commit/385c12743a6108936d88504c516ff23bbe1b0c61
added ripgrep support but didn't add documentation in the template or update the default value.

Add ripgrep to search tools in template

---

layers/+lang/agda/packages.el

`pre-init-golden-ratio` function was copy-pasted from Idris layer without necessary change applied. It causes a warning during startup.

Fix typo in Agda's packages.el

---

core/core-dotspacemacs.el

To match the default configuration template which [also disables it](https://github.com/syl20bnr/spacemacs/blob/a1516a600399715e86926f5ce3c07d62fd3730ec/core/templates/.spacemacs.template#L208).
See https://github.com/syl20bnr/spacemacs/issues/6251#issuecomment-262289770

Disable paste transient state by default

---

layers/+completion/helm/packages.el
layers/+completion/ivy/config.el

rg tries to be smart about printing line numbers in its output (if running inside a TTY or not). On Windows, sometimes (always?) it chooses not to print line number. However, we always want line numbers, so we need to pass -n flag.
fixes https://github.com/syl20bnr/spacemacs/pull/8065#issuecomment-285016670

rg: explicitly request line numbers

---

layers/+lang/python/packages.el

It seems the original config doesn't work when the variable is true.

Fix python-enable-yapf-format-on-save

---

layers/+lang/scala/packages.el

This PR fixes Scala's layer flyspell setup which was calling an undefined function.

scala: fix flyspell setup

---

doc/DOCUMENTATION.org

Fixed url with unescaped `+` causing broken link

---

layers/+lang/python/packages.el

Otherwise, it falls back to system python which may not have the dependencies used in the imports in the file.

[python] Prefer virtualenv python to compile file

---

core/core-dotspacemacs.el

A recent change in the `.spacemacs.template` made it so that the
`dotspacemacs-configuration-layers` variable name can be found inside a
comment right before the expression that sets it's value. This makes the
lazy insertion fail to detect the proper place to add lazy loaded
layers.
This fix solves the immediate problem but maybe a better solution can
be found.

Fix lazy insert point

---

layers/+lang/ocaml/packages.el

`merlin' is a package, not a layer.

fix misused function in OCaml layer

---

layers/+emacs/org/README.org
layers/+emacs/org/packages.el

Hi,
I find `org-resolve-clocks` quite useful and  I would like to add a global evil-leader mapping for `aokr`.
Would you be fine with this addition?
Best wishes & thank in advance for your time

adds global evil-leader mappings `aokr` for `org-resolve-clocks`

---

layers/+completion/ivy/funcs.el

Fix our search functions to reflect that`counsel--git-grep-dir` was renamed upstream to `counsel--git-dir`.
Should solve #9552

counsel: rename git dir variable

---

layers/+spacemacs/spacemacs-purpose/packages.el

Fixes #9593 
`popwin-mode` is disable in popwin's use-package's `:config` block, so we disable it immediately afterwards. A better solution is to not install popwin at all when window-purpose is used, but currently we rely on popwin's configuration even for popup windows powered by window-purpose.

purpose: disable popwin-mode at startup

---

layers/+emacs/org/packages.el

Fixes #9748, which demonstrates `org-default-notes-file` is overriding user configuration because it set after org is loaded. Moved it to `:init` so that is can be overridden by the user.

fix org-default-notes-file precedence

---

layers/+email/notmuch/packages.el

The notmuch refactor in d4b931e9355ad14843ba072038b9da864553781f broke loading of the notmuch package, this fixes that.
I'm not sure why this is necessary, but it seems to fix it.

notmuch: fix package loading

---

CONTRIBUTING.org

As suggested by @kain88-de in #8686: add a section in CONTRIBUTING.org mandating a changelog entry in every PR. This is done to share the workload of maintainers and streamline the merge process.

CONTRIBUTING.org: require a changelog entry from new PRs

---

core/templates/.spacemacs.template

remove obsolete `:powerline-scale` variable from template

core: remove obsolete :powerline-scale variable from template

---

layers/+tools/lsp/README.org
layers/+tools/lsp/funcs.el
layers/+tools/lsp/packages.el

This is a starting point to bring LSP ecosystem into spacemacs, as the initial step to address https://github.com/syl20bnr/spacemacs/issues/10134
This PR adds a new layer, without changing anything default, so it is safe to merge. Based on it, we can integrate [lsp-rust](https://github.com/emacs-lsp/lsp-rust) [lsp-haskell](https://github.com/emacs-lsp/lsp-haskell)+[haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) and many others.
I recently raised a [topic about C++ language server on Reddit](https://www.reddit.com/r/emacs/comments/7qyl39/c_language_server_cquery/). Many Emacs users expressed their interests. I am certainly confident this lsp + cquery combo works brilliantly well (refer to the Wiki [definition/references](https://github.com/jacobdufault/cquery/wiki/Emacs# …

Add +tools/lsp layer for lsp-mode & lsp-ui

---

layers/+spacemacs/spacemacs-modeline/packages.el

In 665c09b modeline separators colors have been fixed for cocoa emacs, but it has broken colors on emacs-mac port. This commit sets `powerline-image-apple-rgb` to `t` only if `window-system` is `ns`, as suggested in https://github.com/syl20bnr/spacemacs/pull/9550#issuecomment-365807703

Fix modeline colors on emacs-mac port

---

layers/+lang/ruby/README.org
layers/+lang/ruby/packages.el

Add key binding for sending a line to REPL.

ruby: add key binding for ruby-send-line

---

EXPERIMENTAL.org

The struct member is named ```remember*ed*_data```, but is mentioned before as ```remember_data```.
Hope that it helps.
Cheers!

EXPERIMENTAL.org: Fix typo in ref to struct member

---

README.md

Seems like `brew linkapps emacs-plus` doesn't work anymore. This PR updates the README with the updated recommended method from brew in order to install emacs.

Add recommended brew method to install emacs

---

EXPERIMENTAL.org

Documentation for getting pdumper work with Ubuntu. I am using ubuntu 17.10 but I think it should work for most of the up-to-date Ubuntu. It would be great if someone can add the labels for it.
Happy to take suggestions etc. 
Additionally, perf improvement:
`vanila: 5.263 sec -> 1.509 sec`

Add ubuntu section in experimental doc (for pdumper)

---

layers/+spacemacs/spacemacs-defaults/keybindings.el

Swaps usage of veritcal and horizontal in the documentation string for Window Manipulation Transient State.
This is a fix for Issue #10725.

Fix vert/horiz in Window Manipulation Transient State

---

layers/+completion/auto-completion/README.org
layers/+tools/shell/funcs.el

Automatic suggestions annoy me.  I can disable them by setting `auto-completion-idle-delay` to `nil`.  However, this customization is not documented, and the shell layer overrides any custom value.  This PR fixes both problems.
I refer to completion-after-a-delay as "automatic suggestions", but perhaps it would be better to use the phrase "auto-completion" for completion-after-a-delay and "tab-completion" for completion-on-tab-key.  I am open to suggestions on the wording.
In `spacemacs//toggle-shell-auto-completion-based-on-path`, re-enable automatic suggestions by restoring `company-idle-delay` to the value of `auto-completion-idle-delay` rather than to a hardcoded value.
Document how to disable automatic suggestions, and mention that the Tab key will still perform completion even with …

shell: Restore correct value for company-idle-delay

---

EXPERIMENTAL.org
core/core-configuration-layer.el
core/core-debug.el
core/core-spacemacs-buffer.el
layers/+completion/auto-completion/funcs.el
layers/+completion/ivy/README.org
layers/+frameworks/react/funcs.el
layers/+lang/c-c++/README.org
layers/+lang/coffeescript/README.org
layers/+lang/elm/README.org
layers/+lang/haskell/README.org
layers/+lang/html/README.org
layers/+lang/hy/README.org
layers/+lang/hy/funcs.el
layers/+lang/java/README.org
layers/+lang/javascript/README.org
layers/+lang/javascript/funcs.el
layers/+lang/json/README.org
layers/+lang/json/funcs.el
layers/+lang/perl5/README.org
layers/+lang/python/funcs.el
layers/+lang/rust/funcs.el
layers/+lang/sql/README.org
layers/+lang/typescript/funcs.el
layers/+spacemacs/spacemacs-defaults/funcs.el
layers/+tools/cfengine/README.org
layers/+tools/geolocation/README.org
news/news01.org

This PR corrects various typos.  The first commit fixes some one-off typos.  Subsequent commits group fixes by typo (in case where grepping revealed multiple instances of the same typo) or file.
Please let me know if it would be less annoying to squash, submit separate PRs, or take another approach!
"apppend" -> "append"
"availabe" -> "available"
"Descripti using ternon" -> "Description"
"you have not them" -> "you don't have them"
"new on" -> "new one"
"plained" -> "curved"
"repel" -> "REPL"
"vairable" -> "variable"
Add a missing "the".
Correct a reference to the layer as "javascript" to "coffeescript".
Fix the syntax on the link to CoffeeLint.
"formated" -> "formatted"
"formating" -> "formatting"
Fix copy-and-pasted docstring text for `spacemacs/hy-shell-eval-current-form-and-go` and …

Fix various typos

---

layers/+spacemacs/spacemacs-defaults/funcs.el
tests/layers/+distribution/spacemacs-base/Makefile
tests/layers/+distribution/spacemacs-base/line-numbers-utest.el

In response to https://github.com/syl20bnr/spacemacs/issues/9362#issuecomment-392806883. We had a few bugs in `spacemacs//linum-enabled-for-current-major-mode`, but this fixes them. And we have tests now :smile:

Line numbers: tests and bug fixes for major-mode predicate

---

layers/+lang/c-c++/packages.el
layers/+lang/java/packages.el
layers/+lang/javascript/packages.el
layers/+lang/perl5/packages.el

Trivial PR, because people seem to have problems adding languages to org-babel-load-languages (maybe because it needs to be set before loading org)
#+begin_src perl :results output
print "Hello World!"
#+end_src
#+RESULTS:
: Hello World!
#+begin_src C
printf ("Hello World!\n");
#+end_src
#+RESULTS:
: Hello World!
#+begin_src C++ :includes <iostream>
std::cout<<"Hello World!\n";
#+end_src
#+RESULTS:
: Hello World!
#+begin_src D
writefln ("Hello World!");
#+end_src
#+HEADERS: :classname HelloWorld :cmdline "-cp ."
#+begin_src java
public class HelloWorld {
public static void main(String[] args) {
System.out.println("Hello world!");
}
}
#+end_src
#+RESULTS:
: Hello world!
#+begin_src js
console.log("Hello World!");
#+end_src

add org-babel support for some of the more popular languages.

---

core/core-dotspacemacs.el
core/core-dumper.el

Given the value of `dotspacemacs-emacs-pdumper-executable-file` is "emacs", now
this executable will be auto located as per the PATH environment variable.

Fixes #10723 - Check for executable rather than the file itself

---

layers/+frameworks/react/funcs.el
layers/+frameworks/react/packages.el
layers/+lang/javascript/packages.el
layers/+lang/typescript/funcs.el
layers/+lang/typescript/packages.el

This reverts commit e4eca01e827b68447604e0a7a0b7163662334e29.
This made js snippets unavailable in typescript and react modes. They need to be
activated in a hook when the mode starts, not after yasnippet is loaded.

Revert "Move yas-activate-extra-mode setup to javascript layer"

---

layers/+lang/javascript/funcs.el

This fixes errors that appear when navigating between javascript files when using the default javascript layer setup without having the `tern` layer nor the `tern` executable installed.
While the problem is fixed I don't feel 100% satisfied with this solution since these functions are executed every time a javascript file is opened and `(locate-file "tern" exec-path)` will be called every time... but if you have the `tern` layer enabled without the tern executable installed then you probably deserve the extra warnings.
@syl20bnr @ztlevi Please take a look and advise me if you know a better way!

Checks if tern layer is enabled and tern executable exists before using it

---

layers/+completion/auto-completion/funcs.el
layers/+completion/auto-completion/packages.el

Insert snippets with ivy, similar to helm-c-yasnippet.
Closes #7401.

auto-completion: add ivy-yasnippet

---

layers/+completion/auto-completion/README.org
layers/+completion/auto-completion/packages.el

Trying to get the ivy layer up to par with helm.

auto-completion: use counsel-company to show completion candidates

---

layers/+lang/asm/packages.el
layers/+lang/rust/packages.el
layers/+lang/scheme/packages.el

Yesterday i found that imenu was missing the the package declarations in ivy by mistake when i was trying to improve jump-in-buffer with counsel so i submitted a pull request. Then i realized that there might be more errors like this so i wrote a Python script that went thru all the layers looking for missing package declarations and it found these 4.
I don't use these layers myself but i think it should improve the editing experience for those that does.
Also, as a byproduct the script also found some wonky-ness in the restructuredtext layer that i will submit a pull request for later.

Fix missing package declarations in different layers

---

layers/+completion/helm/packages.el

Fix issue where `M-x` no longer brings up `Helm M-x`, caused by helm lazy load changes: a417e3ca856a2a6c885521d35ae1ce72513de978
These 3 lines were removed in that commit, but do not seem to have anything to do with lazy-loading.
AFAIK putting this back should not break lazy-loading, and fixes the issue for me.

Fix breakage of `M-x` caused by Helm lazy load changes.

---

layers/+spacemacs/spacemacs-navigation/funcs.el

I think this code was forgotten about during a refactoring. It exists and is in use in spacemacs-visual layer and zoom-frm is initialized there.

spacemacs-navigation: remove duplicate code

---

layers/+intl/keyboard-layout/packages.el

Fix for #10865 .
New lazy-loaded packages using spacemacs|add-transient-hook introduced in bd316f4c308931a787236e8b7e4844f25e551a03 have their setup at `:config` phase instead of `:init` phase. That breaks some keyboard-layout expectation of keymap defined at `:init` time. 
This PR update the two impacted packages in keyboard-layout i'm aware of : evil-surround and flycheck.

Keyboard-Layout : after-config hooks for lazy-loaded packages

---

doc/DOCUMENTATION.org
layers/+spacemacs/spacemacs-defaults/funcs.el
layers/+spacemacs/spacemacs-defaults/keybindings.el
layers/+spacemacs/spacemacs-project/funcs.el
layers/+spacemacs/spacemacs-project/packages.el

Adds a new prefix `SPC f y` which replaces the current `spacemacs/show-and-copy-buffer-filename` keybinding.
The new keybindings will allow you to copy an absolute / relative file path, with added line and column numbers.
I still have some work and documentation to do, so it's a WIP at the moment. Also it would be nice if the spaceline PR was merged first so that toggling column indexing would show up correctly: https://github.com/TheBB/spaceline/pull/194.
/cc @agzam since we discusses a bit about these at work :wink:.

Multiple ways to copy file path

---

layers/+spacemacs/spacemacs-defaults/keybindings.el

The column-indexing toggle did not have a `:status` property.  As a result, the toggle command would enable the toggle but would not disable it.  In addition, the absence of `:status` prevented `-off` and `-on` commands from being defined.
This commit adds a `:status` property so that the toggle works properly and `-off` and `-on` commands are defined.
This commit also renames the toggle to `zero-based-column-indexing` in order to make its purpose clearer.
* `layers/+spacemacs/spacemacs-defaults/keybindings.el` (`column-indexing`): Add `:status` and rename to `zero-based-column-indexing`.

Fix and rename column-indexing toggle

---

layers/+lang/clojure/funcs.el

Fixes a regression I introduced in PR #10954 for people who have cider pinned to the stable version.
I made it use `cider-current-repl` since this is the new command, but I did not take into account the possibility of people still using cider 0.17.
In the commit where `cider-current-repl` was introduced, an alias `cider-current-connection` was also introduced to mantain backwards compatibility.
https://github.com/vspinu/cider/commit/24db03d135475c9f451ad1b7bbe16d3ec8ddfe3a#diff-1d74a90af3008c8072afc63f23ae8392

Clojure layer: fix regression for pinned cider

---

layers/+spacemacs/spacemacs-defaults/packages.el

Commit 6f15744 causes the zone initialization error. This will fix #11101.

+spacemacs: fix zone init

---

layers/+lang/elixir/packages.el

Right now `alchemist-goto-definition-at-point` is marked as sync, which
sometimes shows message "No jump handler was able to find this symbol." before jumping to correct definition.
[`alchemist-goto--open-definition`](https://github.com/tonini/alchemist.el/blob/master/alchemist-goto.el#L215) calls alchemist server before jumping to definition, which I think justifies marking this as async.
The downside is that next jump handler won't ever be called if alchemist fails to jump.
I have very little experience with either Emacs, or Spacemacs, so let me
know if there's anything I can clarify and/or test before this commit gets
merged :)

Mark alchemist jump handler as async

---

layers/+lang/go/README.org
layers/+lang/go/packages.el

This adds a key binding `SPC m =` to manually run the formatter (just like in Rust layer).
**Reason:**
After https://github.com/syl20bnr/spacemacs/pull/11082 has been merged (which disables `gofmt` before save), I'd like to have a key binding to run `gofmt` manually.

Go: Add key binding to run gofmt manually

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-defaults/funcs.el
layers/+spacemacs/spacemacs-defaults/keybindings.el
layers/+spacemacs/spacemacs-defaults/packages.el

Add aliases for commands that ido-mode remaps that we want to bind to Spacemacs keys, and use these aliases in the Spacemacs key bindings so that these bindings invoke the original commands rather than the ido commands.
See <https://github.com/syl20bnr/spacemacs/issues/10237#issuecomment-359861570>.

Work around ido mode remapping spacemacs keys

---

layers/+source-control/github/packages.el

Fix issue #10760: Magithub sections are not added to Magit.
The problem is that the Spacemacs init function's `use-package` form for Magithub specifies both `:after magit` and `:defer t`. It should specify only the former so that Magithub will be loaded when Magit is loaded.
* `layers/+source-control/github/packages.el`: (`github/init-magithub`) Delete `:defer` argument.

Fix loading of Magithub

---

layers/+spacemacs/spacemacs-editing/funcs.el

Fix issue #9477: `spacemacs/smart-closing-parenthesis` sometimes adds an extra closing parenthesis.
`spacemacs/smart-closing-parenthesis` may call `sp-up-sexp` twice: first to find the position of an existing closing delimiter or the position at which one would be inserted, and second to insert a delimiter if necessary or else move point after the existing closing delimiter.
The problem is that each call to `sp-up-sexp` may insert a delimiter, but `spacemacs/smart-closing-parenthesis` is supposed to insert at most one.
The solution is to undo any edit performed by the first call to `sp-up-sexp`.
* `layers/+spacemacs/spacemacs-editing/funcs.el`: Undo any edit performed by the first call to `sp-up-sexp`.
---
@StreakyCobra, does this change look correct?

Fix smart-closing-parenthesis extra parenthesis

---

layers/+lang/python/funcs.el

Escape the filename before calling python on the filename in the shell in the
function `spacemacs/python-execute-file` by calling `shell-quote-argument`.
Thank you <3

Fix #1109: Escape argument for shell spacemacs/python-execute-file

---

layers/+emacs/semantic/README.org

Found a small typo in semantic layer's readme.

doc: fix small typo in semantic feature block

---

layers/+completion/auto-completion/packages.el

Since `ac-ispell` is now present in there :tada: 
https://github.com/melpa/melpa/issues/5657#issuecomment-410990552
This reverts commit c290645261d9ad7a6e62ec78d7edcbceda321d7b.

melpa: Resurrect `ac-ispell'

---

layers/+spacemacs/spacemacs-layouts/packages.el

This fixes issue #5776.
* `layers/+spacemacs/spacemacs-layouts/packages.el` (`spacemacs-layouts/init-persp-mode`): Set `persp-add-buffer-on-after-change-major-mode` to `'free`.

layouts: Add free buffers to current layout

---

layers/+lang/coq/README.org
layers/+lang/coq/packages.el

Just some extra keybindings! The `mi` prefix is a bit bare right now, and these functions can speed things up a bit.

lang/coq: more insertion keybindings

---

layers/+lang/html/packages.el

When using Emacs style you use tab to indent. This binding in the html-layer make's tab either expand text or do nothing when editing html or jsx (React) code. I think using C-j (the default) for emmet is fine for Emacs style and the html-layer even links to the emmet documentation that says that C-j is used for expansion.

html: fix indenting for emacs editing style

---

core/templates/.spacemacs.template

Lexical binding is easier to reason about and it's generally recommended for new code. It's faster too.
Dynamic scoping can lead to tricky situations. Example: https://emacs.stackexchange.com/questions/10394/scope-in-lambda
This probably won't break existing code. Most people don't even know the default is dynamic binding.

Use lexical binding in dotfile template

---

layers/+checkers/syntax-checking/README.org
layers/+completion/auto-completion/README.org

Syntax-checking and auto-complete layers should more directly communicate that their function depends on the installation of individual language layers to avoid misunderstandings with new users who only install syntax-checking or auto-complete and install the packages manually.
This is part of #11073.

doc: revise docs for auto-complete and syntax-checking layers

---

doc/DOCUMENTATION.org

Added a remark to the general documentation making clear that for opening an issue with spacemacs one has to be logged in into GitHub.
This is part of #11076.

doc: add remark for necessary GitHub login to report issues

---

layers/+lang/go/funcs.el

Fixes #11180 
I've left the same structure in `spacemacs//go-setup-backend` just because we might want to add go-mode back if we need to do additional setup.

Remove unnecessary company-go function

---

layers/+lang/julia/packages.el

I added the key bindings for evil-surround that did not make it into #10444.
There are the following issues, which I did not manage to solve:
- The keybindings are not active in the first buffer opened in julia mode.
- The `s:` keybinding does not work, it worked before, when I had
```
(with-eval-after-load 'evil-surround ;'julia-mode-hook
(push '(?b . ("begin" . "end")) evil-surround-pairs-alist)
(push '(?q . ("quote" . "end")) evil-surround-pairs-alist)
(push '(?l . ("let"   . "end")) evil-surround-pairs-alist)
(push '(?: . (":("    . ")"))   evil-surround-pairs-alist))
```
in my user-init, suggestions welcome.

add key bindings julia layer evil-surround

---

layers/+tags/gtags/README.org

Fixed some issues in the gtags layer README file. Mostly typos but also difficult to understand passages which may confuse new users.

doc: fix various errors in gtags layer README

---

layers/+readers/elfeed/packages.el

This binding is redundant since Elfeed already binds q to elfeed-search-quit-window.

Fix Elfeed not saving on quit

---

layers/+lang/coq/README.org
layers/+lang/coq/packages.el

Extra keybindings for the Coq layer concerning documentation

coq: add keybindings for company-coq's documentation functions

---

layers/+lang/go/README.org
layers/+lang/go/config.el
layers/+lang/go/funcs.el
layers/+lang/go/packages.el

This PR adds support for [golangci-lint](https://github.com/golangci/golangci-lint) with [flycheck-golangci-lint](https://github.com/weijiangan/flycheck-golangci-lint).
Fixes this issue (request): #10825

Add golangci-lint support for go layer

---

.gitignore
layers/+lang/java/README.org
layers/+lang/java/config.el
layers/+lang/java/funcs.el
layers/+lang/java/packages.el

Fixes #10654
Added new backend for the Java.

LSP Java backend for the Java layer

---

layers/+spacemacs/spacemacs-layouts/funcs.el
layers/+spacemacs/spacemacs-layouts/packages.el

Before this commit, `spacemacs-layouts/init-eyebrowse` advised `rename-buffer` with `spacemacs//fixup-window-config`.  However, this advice causes problems if persp-mode is not activated when a function tries to rename a buffer.
In particular, Spacemacs's CI uses Emacs's batch mode to run `spacemacs/publish-doc`, which uses `rename-buffer`.  In batch mode, persp-mode is not activated, and consequently `spacemacs/publish-doc` was failing:
Publishing file /home/travis/.emacs.d/news/news01.org using ‘org-html-publish-to-html’
Skipping check for new version (reason: dotfile)
Wrong type argument: hash-table-p, nil
Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil
spacemacs/publish-doc failed
In order to avoid problems, this commit moves the advising of `rename-buffer` from …

Advise rename-buffer when persp-mode activated

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-editing/packages.el
layers/+tools/lsp/README.org
layers/+tools/lsp/config.el
layers/+tools/lsp/funcs.el
layers/+tools/lsp/packages.el

This adds some useful defaults to the `lsp` layer (in a new config.el), and adds some building block functions to facilitate development of derived layers.
It declares a number of major mode prefixes for typical classes of language server function, and provides the function `spacemacs/lsp-bind-keys-for-mode` which can be used by derived layers to provide a consistent set of keybindings common core language-server functions.
See README.org and the commit message for further details and a trail of the multiple amendments since initial submission.
A usage example can be found in the `lsp-c-c++` layer, in my branch of the spacemacs repo:
https://github.com/cormacc/spacemacs/tree/lsp-c-c%2B%2B-layer
N.B. The `lsp-c-c++` layer will not be the subject of a PR as is, but form the basis of a new …

lsp-layer additions: configuration and building blocks for derived layers.

---

layers/+spacemacs/spacemacs-layouts/funcs.el

Fix issue #11207.
Only try to disable eyebrowse's advice on rename-buffer if we can find that advice.  If eyebrowse is older than version 0.7.6 (2017-11-22), the advice will not exist, and attempting to delete it will cause an error:
ad-disable-advice: rename-buffer is not advised
* `layers/+spacemacs/spacemacs-layouts/funcs.el` (`spacemacs//activate-persp-mode`): Only disable the `eyebrowse-fixup-window-configs` advice for `rename-buffer` if the advice exists.

Only disable eyebrowse advice if it exists

---

layers/+lang/go/README.org

nsf/gocode is not maintained anymore. change to https://github.com/mdempsky/gocode
Thank you <3

Update gocode repo

---

layers/+lang/python/config.el
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

Since spacemacs changes the python tab width, we need to do the indent guessing after setting
the tab width.

python-mode: fix indent offset guessing for tab indentation

---

layers/+tools/lsp/README.org
layers/+tools/lsp/funcs.el

`m g a` conventionally used to switch between c/c++ source and header files, but bound to a keyboard symbol navigation function in lsp-layer. Moved lsp-layer binding under `m g k`

lsp-layer core keybinding amendments

---

layers/+distributions/spacemacs-docker/deps-install/run

Looks like the lock-file of recentf needs to be deleted after dependency installation.

[spacemacs-docker] clean .#recentf

---

layers/+lang/jsonnet/README.org

problem: a space before the closing ~, breaks the formatting
solution: remove the space to hide the ~ signs
And remove a word: "to"

[jsonnet] readme.org: fix keybinding table

---

layers/+checkers/spell-checking/README.org

In the documentation `SPC g .` instead of the actually bound `SPC S .` was documented.

Fix keybindings in documentation of spell checking transient state

---

layers/+tools/lsp/README.org
layers/+tools/lsp/config.el
layers/+tools/lsp/packages.el

lsp-ui has switched to (defcustom lsp-ui-peek-fontify 'on-demand ...) https://github.com/emacs-lsp/lsp-ui/pull/148 . This is no longer needed.

+tools/lsp: remove lsp-ui-peek-expand-by-default

---

layers/+lang/ruby/packages.el

* Add a prefix for `rake` and refactor/RuboCop/robe commands.
* Add `test` and `toggle` prefix for `enh-ruby-mode`.
* Use `enh-ruby-toggle-block` in `enh-ruby-mode`, instead of `ruby-toggle-block`.
* Remove the prefix in prefixes `ruby/`.

Fix issues in ruby layer

---

layers/+lang/coq/packages.el

`proof-general` is added to MELPA as per https://github.com/ProofGeneral/PG/commit/ff1cb6c2c355082076d99de1f560fa0c4bbcd86c

proof-general is added in MELPA

---

layers/+spacemacs/spacemacs-defaults/funcs.el

Before this commit, Spacemacs assigned an anonymous function to the `compilation-finish-function` variable.  This variable was deprecated in Emacs 22.1 and removed in Emacs 27.1 in favor of the
`compilation-finish-functions` hook.  Consequently, the assignment has no practical effect in Emacs 27.1.
Although we could add the Spacemacs function to the new `compilation-finish-functions` hook, the function serves little purpose; it prints a generic message when compilation succeeds:
compilation ok.
and it prints the key binding for `spacemacs/next-error` when compilation fails:
There were errors. Use SPC e n to visit.
However Emacs already prints messages to indicate success or failure, respectively:
Compilation finished
or (for example)
Compilation exited abnormally with code 1
Because the …

Delete compilation finish hook

---

layers/+frameworks/react/packages.el
layers/+lang/javascript/funcs.el
layers/+lang/javascript/packages.el

Use eslint_d instead of eslint. Find the eslint_d executable on opening javascript buffers.
https://github.com/mantoni/eslint_d.js/
eslint_d runs eslint as a daemon, and provides the fastest lint for .js files.

Prefer eslint_d to eslint

---

layers/+completion/ivy/packages.el

Currently, the function bound to C-r is `helm-minibuffer-history` even if ivy layer is chosen.

Ivy: Add keybinding for counsel-minibuffer-history

---

layers/+filetree/treemacs/packages.el

problem:
Which-key subgroups get the default name `+prefix`. The subgroup has to be
opened to find out which keys it contains.
solution:
Add more descriptive names:
```
c      treemacs-create
o      treemacs-visit-node
oa     treemacs-visit-node-ace
t      treemacs-toggles
y      treemacs-copy
C-p    treemacs-projects
C-p c  treemacs-projects-collapse
```

[treemacs] give names to which-key +prefix entries

---

layers/+lang/typescript/funcs.el

When the user doesn't specify a valid `typescript-formatter`, `spacemacs/typescript-format` prints a helpful error message with possible options. This change includes the recently-added option `'prettier` in the message.

Add 'prettier to error msg of spacemacs/typescript-format

---

layers/+tools/shell/config.el

`multi-term` has long been an option for `shell-default-shell` but was missing from the doc string.

Add `multi-term' to `shell-default-shell' doc

---

doc/DOCUMENTATION.org

After [loosing some time](https://github.com/syl20bnr/spacemacs/issues/11272#issuecomment-419002973) trying make relative line numbers only available on specific modes I think this minor change could make the documentation more explicit.

Improve docs for dotspacemacs-line-numbers

---

layers/+source-control/git/packages.el

Colors makes it so much easier to visually differentiate and track the ascii lines representing the commit histories of the different branches 🌈

Enable colors in magit-log

---

CHANGELOG.develop
layers/+emacs/org/README.org
layers/+emacs/org/packages.el

Just some more keybindings!
Also, the current documentation mentions
```
evil-org-recompute-clocks 
```
which actually isn't bound to that key.

layers/+emacs/org: more clock keybindings

---

layers/+lang/clojure/README.org
layers/+lang/clojure/config.el
layers/+lang/clojure/packages.el

As suggested by @bbatsov on #11194 ([comment](https://github.com/syl20bnr/spacemacs/pull/11194#issuecomment-414824521)), it makes sense to give clj-refactor the same treatment as Sayid.
This also updates Clojure's README to document how to use the newly introduced variables to enable sayid or clj-refactor.
I also updated the documentation on adding CIDER-related dependencies. CIDER 0.10
is three years old now, so I think the case where cider middleware isn't
injected automatically is getting rare. However there is still a good use case
for running your Clojure process outside of Emacs/CIDER, meaning you don't get
to benefit from `cider-jack-in`'s magic insjections, so I have focused more on
that case, adding information for clj-refactor's and sayid's middleware, as well
as CIDER's. …

Make clj-refactor off by default, update Clojure README

---

layers/+lang/python/packages.el

`anaconda-mode-go-back` is now not supported in anaconda-mode. 
And it is replaced with `xref-pop-marker-stack`

`anaconda-mode-go-back` is replaced with `xref-pop-marker-stack`

---

layers/+lang/c-c++/README.org

Fix code blocks in C++ layer documentation.
- - - - - -
`#+END_SRC emacs-lisp`   <-  this is invalid.

Fix code blocks

---

layers/+lang/c-c++/config.el
layers/+lang/c-c++/packages.el

This config variable does not make sense.
There are c++11 c++14 c++17 c++2a gnu++11 gnu++14 gnu++17 gnu++2a. `-std=c++11` will actually disable some features, for example, generic lambda.
The language option is also a per-project option, it should not be global.
https://github.com/syl20bnr/spacemacs/issues/10143

c-c++: remove c-c++-enable-c++11

---

layers/+lang/csharp/README.org
layers/+lang/csharp/packages.el

Adds ability to run csharp tests from buffer as implemented in omnisharp-emacs https://github.com/OmniSharp/omnisharp-emacs/pull/436
Also contains minor documentation updates as omnisharp-emacs will start the server automatically if it is able to.

Add new test binding + improve documentation

---

layers/+source-control/git/packages.el

Magit creates a buffer for almost every possible action that you can do with it. Since recently, these buffers get added to the current perspective, which I find a good and sensible thing. But then, browsing your perspective with `<SPC> b n` or `<SPC> b p` gets tedious as you have to pass all the magit buffers.
I find that setting Magit's buffers as useless makes sense, since these buffers are accessed through Magit's commands (and they get refreshed that way).

Set magit buffers as useless

---

layers/+tools/shell/packages.el

It seems that I had forgotten to update binding for inferior shell, after
fixing unexpected popup window layout issue(#11422).
This binds the new shell wrapper function to `SPC a s i` binding.

Fix broken leader key binding for inferior shell

---

layers/+misc/multiple-cursors/packages.el
layers/+spacemacs/spacemacs-evil/packages.el

As per #5324 and my own experience, the currently documented way of activating `evil-mc` conflicts with (at least) Magit and Treemacs `gr` binding.

document better way of activating evil-mc

---

layers/+tools/lsp/README.org
layers/+tools/lsp/config.el
layers/+tools/lsp/funcs.el
layers/+tools/lsp/packages.el

Added a configuration option to specify a preference for lightweight xref/lsp navigation functions (for find definition/implementation etc.) or lsp-ui-peek. By default, lightweight functions bound under `m g` and lsp-ui-peek equivalents under `m p`. Setting a config var to either `simple` or `peek` eliminates the bindings under `m p prefix` and binds either the xref/lsp (simple) or lsp-ui-peek (peek) nav functions under `m g`.
Also added functions for derived layers to provide server-specific extensions in a manner consistent with the specified preference (i.e. using `lsp-find-custom`, `lsp-ui-peek-find-custom` or both as specified by the configuration variable).
Prompted by a number of comments on the original lsp-layer-improvements PR (#10486) and subsequently on the c-c++ lsp backend …

lsp layer -- Configure for lsp-ui-peek OR xref/lsp navigation

---

core/libs/quelpa.el

Brings our bundled version of Quelpa to [e250c749](https://framagit.org/steckerhalter/quelpa/commit/e250c74952c3b0b3cd48ace98decacd8cd7c303d). Fixes a [bug](https://framagit.org/steckerhalter/quelpa/issues/156) where some recipes would not install on systems where tar's default format is `pax` (or `posix`).

core: update Quelpa to last version

---

layers/+lang/c-c++/README.org
layers/+lang/c-c++/funcs.el
layers/+lang/c-c++/packages.el

Follow-up of https://github.com/syl20bnr/spacemacs/pull/11242
c-c++-enable-rtags-support has been removed in favor of c-c++-backend. Don't mention it in README
Delete .ccls from c-c++-adopt-subprojects
as in ccls, .ccls-root (detected by emacs-ccls) is recommended for this purpose
Delete the extra parameter :levels 3 from $ccls/inheritance
Finding the immediate bases is usually more desired
The parameters of refs-* in ccls are not in :context

Some tweak to c-c++ layer

---

doc/DOCUMENTATION.org

All described in the changelog for 0.200, but missing from the docs.
My 2¢.
Cheers!

DOCUMENTATION.org: Missing help keybindings

---

layers/+tools/cmake/README.org

Hi guys,
This PR show an example of integration `projectile` and `helm-make`, `helm-ctest` packages.

README.org [helm-make][helm-ctest] - add configuration sample with projectile

---

layers/+tools/lsp/funcs.el

To avoid multiple peek popup situation:

fix: lsp-ui-peek-find-definitions is an async jump handler

---

doc/DOCUMENTATION.org
layers/+emacs/org/README.org
layers/+emacs/org/packages.el
layers/+source-control/version-control/README.org
layers/+source-control/version-control/keybindings.el
layers/+spacemacs/spacemacs-defaults/keybindings.el
layers/+spacemacs/spacemacs-navigation/packages.el

By analogy with the "zz", "zb", "zt" vim / evil bindings, this adds an
additional key binding "z" for `recenter-top-bottom` to the following
transient states which navigate around the buffer in large jumps:
- auto-symbol-highlight
- error
- buffer
- vcs
- org-babel
This allows for repositioning of the buffer for visibility without having to
exit the transient state.
Some updates are also made to the documentation of other transient states (98bd369)

Add `z` binding to transient states to recenter buffer

---

layers/+lang/html/packages.el

This commit reverts ab34cc2d9dd53f7c31ba1c7af01b6f5e6c67aad5. Setting
company-minimum-prefix-length to 0 causes issues indicated in issue #8222. While
the user is free to set company-minimum-prefix-length to 0 if they please, doing
so affects editing any files that also use web-mode such as jsx files.
Additionally, new users to Spacemacs may be confused by this behavior since no
other layer sets company-minimum-prefix-length to 0.

[html] revert: set company min. prefix length to 0 for company-web backend

---

layers/+spacemacs/spacemacs-defaults/funcs.el

Spacemacs doesn't keep the current position on toggle maximize. This PR suggests a dumb and simple fix.
to repro the issue:
- create multiple splits, 
- maximize the window, 
- move cursor around
- toggle maximize-buffer
observed behavior: cursor is not where it was

Keeps previous position on toggle-maximize-buffer

---

layers/+spacemacs/spacemacs-defaults/funcs.el

problems:
the delete file prompt doesn't show which file it's about to delete,
and when the deletion request is canceled, then the question remains in the
minibuffer (the text disappears when an action updates the minibuffer, like
moving the cursor, but it might be confusing to still be seeing the question
after it's been answered)
solution:
show the file name in the delete file prompt, and show a canceled message

Update delete file messages

---

layers/+lang/clojure/README.org
layers/+lang/clojure/funcs.el
layers/+lang/clojure/packages.el

First commit fixes #11531, adding clojure-mode refactorings and which-key prefixes in default layer configuration.
Later 2 commits are not strictly necessary, could be omitted

Improve clojure layer without clj-refactor

---

layers/+lang/typescript/funcs.el
layers/+lang/typescript/packages.el

Because the setup functions run after local vars are set, setting jump handlers needs to happen directly. Otherwise setting them only applies to the next typescript file that is opened, which may or may not even have the same backend.

typescript: Fix jump handling with multiple backends

---

layers/+lang/ess/packages.el

https://github.com/syl20bnr/spacemacs/issues/11617#issuecomment-440272037
ess-disable-underscore-assign introduced via #9102 relies on functionality deprecated in ESS 18.10. The deprecated functionality may be removed from ESS soon and as melpa follows ESS master branch, spacemacs should be adapted.

Update ess-disable-underscore-assign for ESS 18.10

---

layers/+lang/markdown/packages.el

problem: MMM is shown in the mode-line when a .md markdown file is opened.
solution: hide MMM when mmm-mode is configured.

Hide MMM mode-line indicator

---

CHANGELOG.develop
layers/+chat/rcirc/README.org
layers/+chat/rcirc/config.el
layers/+chat/rcirc/local/rcirc-late-fix/rcirc-late-fix.el
layers/+chat/rcirc/packages.el

Fix the following errors:
rcirc-late-fix.el:49:12:Warning: ‘rcirc-print-hooks’ is an obsolete
variable (as of 24.3); use ‘rcirc-print-functions’ instead.
rcirc-late-fix.el:51:1:Warning: defface for ‘rcirc-late-fix-face’ fails
to specify containing group
In rcirc-late-fix-hook:
rcirc-late-fix.el:79:82:Warning: (lambda (x) ...) quoted with ' rather
than with #'
In rcirc-late-fix-matching-buffer:
rcirc-late-fix.el:85:34:Warning: function ‘find-if’ from cl package
called at runtime
Add a configuration variable to enable the included rcirc-late-fix package in the rcirc layer.  The package is still disabled by default.

Add variable rcirc-enable-rcirc-late-fix

---

layers/+lang/java/README.org
layers/+lang/java/funcs.el
layers/+lang/java/packages.el
layers/+tools/dap/README.org
layers/+tools/dap/config.el
layers/+tools/dap/funcs.el
layers/+tools/dap/packages.el

- I had some issues related to finding the corresponding shortcuts for each of
the commands and I am looking for suggestions for improvements.
- updated the lsp-java readme since the server installation is now automatic. If
you already have jdt server installation, please run lsp-java-update-server
which will download the related dap-mode related stuff.
- Make sure that you have latest melpa versions of lsp-java, lsp-ui and dap-mode
since several issues related to the java integration were fixed lately.
- dap-mode is pretty young package and it is not extensively tested
- dap-hydra which will be used as a transient state for the breakpoints and
debugging, in general, is not synched with the shortcuts in the layer. I will sync
them once there is agreement on the shortcuts configuration. …

dap-layer implementation

---

core/core-funcs.el

This could be a follow up of issues like #8414 , #7641 and may help with several
others where recompilation is involved.
A commonly proposed solution is to delete all byte-compiled modules to force
their recompilation, but it may not work as expected.
- Upgrade emacs or spacemacs.
*Observed behaviour:* :eyes: :broken_heart:
Mostly issues related with org-contrib packages,
e.g. source code blocks evaluation (org-babel).
Recompilation skips many packages, and version conflicts still cause issues.
*Expected behaviour:* :heart: :smile:
A smooth transistion towards a better world for everyone ?
Given the docstring of
[`byte-recompile-directory`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Compilation-Functions.html#Compilation-Functions#ind …

Recompiling Elpa: don't skip missing .elc files

---

layers/+source-control/git/packages.el

Just a simple change to optimize startup times - without deferring it was adding 6-7 seconds to the total startup because of `(require 'org)` and `(require 'magit)`

Defer orgit package

---

layers/+completion/ivy/funcs.el
layers/+completion/ivy/packages.el

This function was renamed upstream:
https://github.com/abo-abo/swiper/commit/58bf1b94c8346491b906aa306f5ed734be67310c
If we should support both versions, please let me know the best way to do that.

ivy: Fix counsel search

---

CHANGELOG.develop

Summarizing: https://github.com/syl20bnr/spacemacs/commits/develop?before=69a89cc41243cfb189238a2297fde4498d7fcf6d+718
Started with: 4cc57dea74b9b3391821b518c5fad76153904972
New pointer: https://github.com/syl20bnr/spacemacs/commits/develop?before=69a89cc41243cfb189238a2297fde4498d7fcf6d+683
Start with: 5b70ac500963390c0343bd78eafa6ead177f0405
---
* Fix automatic syntax checking for cfengine · syl20bnr/spacemacs@4cc57de
Added under changes to the cfengine layer.
* Fix `l` keybinding in neotree to open in MRU window · syl20bnr/spacemacs@7982406
Skipped; fix by Sylvain for a regression against the last release.
* Fix: remove buggy hooks in javascript and typescript · syl20bnr/spacemacs@5c14486
Skipped; fix-up by the original author of the code (who is already credited).
* xclipboard: Fix …

Updated change log (+718)

---

CHANGELOG.develop
layers/+lang/go/README.org

Summarizing: https://github.com/syl20bnr/spacemacs/commits/develop?before=69a89cc41243cfb189238a2297fde4498d7fcf6d+473
Started with: https://github.com/syl20bnr/spacemacs/commit/7238e232aed6217d33c6900e064567d00e4b3329
New pointer: https://github.com/syl20bnr/spacemacs/commits/develop?before=69a89cc41243cfb189238a2297fde4498d7fcf6d+438
Start with: https://github.com/syl20bnr/spacemacs/commit/c41a122b24a609d17cdc4f30c67650d43ade0c5f
---
| Commit                                                                                             | Action                                                                                             |
|----------------------------------------------------------------------------------------------------|------------------------------------------------------ …

Updated change log (+473)

---

core/core-documentation.el

Looks like `org-set-tags-to` suddenly started to inserts tags into wrong place. 
Hopefully simple inlining will help.

Fiddle with layers.org TOC generation.

---

.gitignore

Where by `forge` I mean: https://github.com/magit/forge

Include magit/forge SQLite db file in .gitignore

---

layers/+filetree/treemacs/config.el
layers/+filetree/treemacs/packages.el

Deferred git-mode adds a 0.5s delay to fontification, so treemacs will almost never have to wait for a git process to finish.

[treemacs] Use deferred git-mode by default.

---

layers/+source-control/github/README.org

Update the documentation for `forge` per upstream changes to key bindings in [evil-magit](https://github.com/emacs-evil/evil-magit/commit/49978d07d369fa182971890bc75693b2aef3b5bc).
* `layers/+source-control/github/README.org`: Update key bindings for `forge`.

github: Update forge key bindings

---

layers/+distributions/spacemacs-docker/config.el

We already have environment variables loaded so we don't need this code anymore.

Spacemacs docker cleanup

---

CHANGELOG.develop

It's easier to read the key bindings as a list.

Changelog.develop: Inline key bindings to list

---

CHANGELOG.develop
layers/+lang/nim/packages.el

As described here: https://github.com/nim-lang/nim-mode/issues/159,
company-capf makes nim-mode unusable. I am replacing it with
company-nimsuggest as it is much more responsive. The reason I elected not to
leave company-capf in as a backup is that it would somehow still make it to the
car of company-backends, regardless of position at assignment, thus becoming the
default completion backend. Given that no functionality is lost this way, and
that nimsuggest is now part of the core nim installation
(https://github.com/nim-lang/nimsuggest), I do not think anything has been
sacrificed.

Replace company-capf with company-nimsuggest in nim-mode.

---

layers/+source-control/git/packages.el

Moves the history.el, values.el and levels.el files into the .emacs.d/.cache directory.

Add init function for transient package

---

core/core-custom-settings.el
core/core-spacemacs.el

Fixes a bug where saving a custom variable (e.g. package-selected-packages) before reading the custom settings from dotspacemacs/emacs-custom-settings could overwrite the stored settings.
Should fix #10504.

custom setting: don't write to dotfile before loading all of them

---

layers/+source-control/git/packages.el

- magit-svn-popup renamed to magit-svn (more fallout of Transient)
- more reliable placement of Transient cache files
- also defers Transient

Transient and magit-svn fixes

---

CHANGELOG.develop
doc/DOCUMENTATION.org
layers/+completion/helm/packages.el

Change the binding to be more mnemonic.
It calls helm-[a]propos and it pretty much describes [a]ll.
---
This seems to be the commit that added it as `SPC h d d`: 
Add `helm-apropos` on `SPC h d d` https://github.com/syl20bnr/spacemacs/commit/ad448d66832163b387d711e915e04c6b73e5505f
The docstring for these commands say:
- `helm-apropos`
>Preconfigured helm to describe commands, functions, variables and faces.
- `apropos`
>Show all meaningful Lisp symbols whose names match PATTERN.
Symbols are shown if they are defined as functions, variables, or
faces, or if they have nonempty property lists.
There's also a PR for adding `counsel-apropos` to the ivy layer:
Ivy: Add `SPC h d a` counsel-apropos #11969 
`counsel-apropos` docstring says:
>Show all matching symbols.
See `apropos' for further …

Change `helm-apropos` from `SPC h d d` to `SPC h d a`

---

CHANGELOG.develop
layers/+lang/clojure/README.org

Updated documentation for Clojure layer to currently recommended versions of
build tools and `cider-nrepl`, ensuring that connecting to a manually run
Clojure REPL works correctly with the current version of CIDER.
Leiningen version 2.9.0
Boot version 2.8.2
`cider-nrepl` 0.21.1

Clojure Layer - Updated docs for Cider manual quick start

---

CHANGELOG.develop
layers/+source-control/git/packages.el

---
In Spacemacs, the Magit commit edit commands (ex: fixup, squash, augment, etc) opens two buffers:
- `magit-log-select <project>`
- `magit-diff <project>`
but only the diff buffer is visible, even though the minibuffer shows the instructions for the log buffer.
>Type C-c C-c on a commit to fixup into it, or C-c C-k to abort
The diff buffer has to be closed `q` first, to get to the log buffer.
The purpose-x-magit extension brings back the default Magit behavior of showing both the diff and log buffers at the same time, with the log buffer selected.
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp …
```

Show magit-log-select and diff in two windows

---

layers/+checkers/spell-checking/README.org

Change "compeled" to "compelled"

Fix typo in spell-checking layer documentation

---

doc/FAQ.org

The FAQ has an entry for configuring Spacemacs to use double-space as the sentence delimiter.  This FAQ entry instructs the reader to set the `sentence-end-double-space` variable in the `dotspacemacs/user-init` function.
The problem is that the spacemacs-defaults layer sets `sentence-end-double-space` when it loads, and Spacemacs loads layers after calling `dotspacemacs/user-init`, which means the layer overrides any setting for `sentence-end-double-space` in `dotspacemacs/user-init`.
To solve this problem, this commit modifies the FAQ entry to instruct the reader to set the variable in the `dotspacemacs/user-config` function, which Spacemacs runs after loading layers.
The FAQ entry was added in https://github.com/syl20bnr/spacemacs/pull/3835.
* `doc/FAQ.org`: Instruct the reader to set …

FAQ: Set sentence-end-double-space in user-config

---

CHANGELOG.develop
layers/+lang/haskell/README.org
layers/+lang/haskell/config.el
layers/+lang/haskell/funcs.el
layers/+lang/haskell/packages.el

This allows the use of the `lsp` layer as a backend for the Haskell layer along with an installation of `hie`.
The first commits are from https://github.com/syl20bnr/spacemacs/pull/11550, which performs some useful preparatory refactorings. All I did was fix the merge conflict (indentation), and get rid of the form-feed characters as requested in the review.
After that it's mostly a matter of just adding the appropriate additional hook.
The existing setup is now a little inconsistent, since we talk about the *completion* backend for the layer, whereas the `lsp` backend provides a bunch of other stuff too. However, I'm not planning to try and change that here.

Haskell: add LSP support via HIE and lsp-haskell

---

CHANGELOG.develop
layers/+tools/shell/README.org
layers/+tools/shell/packages.el

Hi,
I think this change will be positive, as it adheres to the Navigation conventions when users are in hybrid or vim mode.
It also adds shortcuts for term-line-mode and term-char-mode, which are handy for navigating terminal output to both editing styles.

Improve & apply conventions to multi-term keybinds

---

layers/+lang/go/README.org

go-mode uses multiple tools for doc view, and `godoc-at-point` (`, hh`) uses `godoc` only, so added godoc installation into README.

Add godoc installation into go layer README

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Adds `SPC m e u` to the Clojure layer to call `cider-undef`, a function that remove an
existing definition from the current namespace.
This provides a Spacemacs style keybinding for the existing Emacs style keybinding `C-c C-u`

[clojure] keybinding - cider-undef - remove symbol from current ns

---

layers/+spacemacs/spacemacs-navigation/packages.el

What: Move "[z] recenter" to end of first row.
Why:  Top row (red keys) will not exit, bottom row (blue keys) exits.
---
Before: 
After:

Update Symbol Highlight TS: Reorder keys

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-modeline/packages.el

problem:
the doom-modeline isn't applied to the messages buffer
solution:
call `(doom-modeline-init)` without a hook
Resolves #11404 
---
The `doom-modeline-init` function sets the modeline to `main` in the `*Messages*` buffer, if the `after-init-time` variable is `nil`, but it's `(23507 65018 227374 0)` when the `after-init-hook` runs.
```elisp
(defun doom-modeline-init ()
"Initialize doom mode-line."
;; Create bars
(doom-modeline-refresh-bars)
(unless after-init-time
;; These buffers are already created and don't get modelines. For the love
;; of Emacs, someone give the man a modeline!
(dolist (bname '("*scratch*" "*Messages*"))
(with-current-buffer bname
(doom-modeline-set-modeline 'main)))))
```
https://github.com/seagle0128/doom-modeline/blob/cb1727d95623e178b7bc0cb8559ca5b352ced886/d …

Fix doom-modeline in the messages buffer

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-layouts/funcs.el
layers/+spacemacs/spacemacs-layouts/packages.el

Fix issue #11282.
When a new perspective (layout) is created and we are in a Projectile project, add all buffers belonging to that project to the perspective.
* `layers/+spacemacs/spacemacs-layouts/funcs.el` (`spacemacs//add-project-buffers-to-persp`): Add new function.
* `layers/+spacemacs/spacemacs-layouts/packages.el` (`spacemacs-layouts/init-persp-mode`): Add `spacemacs//add-project-buffers-to-persp` to `persp-created-functions`.

spacemacs-layouts: Add project buffers to new persp

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-defaults/funcs.el

This pull request includes various improvements when indent code:
- When we use `spacemacs/indent-region-or-buffer` ( <kbd>SPC j =</kbd> ) to indent region or buffer explicitly, don't check for `spacemacs-indent-sensitive-modes`.
- Make variable `spacemacs-indent-sensitive-modes` customized.
- New variable `spacemacs-yank-indent-modes` to enable auto indent in modes not derived from `prog-mode`. Set default value to `latex-mode`.
This pull request also changes the behavior of `spacemacs//yank-indent-region`. This function was taken from `Prelude`, but there are some errors when imported it, which has already been pointed out in https://github.com/syl20bnr/spacemacs/pull/1485#issuecomment-335436702. And it is ambiguous when we trigger <kbd>C-u C-y</kbd> ( details described in …

Various improvements when indent code

---

.travis.yml
.travisci/pub_prep.sh

Broken relative links in the new LAYERS file fail html export script and it fails entire CI.

Temporarily disable html export

---

CHANGELOG.develop
layers/+completion/ivy/funcs.el
layers/+completion/ivy/packages.el
layers/+spacemacs/spacemacs-layouts/funcs.el
layers/+spacemacs/spacemacs-layouts/packages.el

Delete the hook that https://github.com/syl20bnr/spacemacs/pull/11642 added to `persp-created-functions`, and change `spacemacs/ivy-spacemacs-layouts`, `spacemacs/helm-perspectives`, `spacemacs/helm-persp-switch-project`, and `spacemacs/ivy-persp-switch-project` to achieve the intended goal of adding the desired buffers after creating a new perspective.
Change `spacemacs/helm-persp-switch-project` and `spacemacs/ivy-persp-switch-project` as follows: If the user selects a project but then quits without selecting a file or buffer, the new perspective is now immediately killed.  Otherwise, if the perspective did not already exist, any buffers that belong to the selected project are added to the perspective.
Add the following actions to `spacemacs/ivy-spacemacs-layouts` and …

spacemacs-layouts: Fix adding buffers to new persp

---

layers/+spacemacs/spacemacs-defaults/keybindings.el
layers/+spacemacs/spacemacs-misc/packages.el

A nice tool to have as a backup.  
- - - - - -
[dash layer](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Breaders/dash/packages.el) adds keybindings under "SPC d"  without naming the prefix. So I  defined it more generally  `("d"   "documentation")`

add devdocs tool

---

CHANGELOG.develop
layers/+lang/typescript/funcs.el
layers/+lang/typescript/packages.el

In `typescript-tsx-mode` buffer, `emmet-mode` is enabled (derived from `web-mode`), but it was not configured for TSX syntax.

Configure emmet-mode for typescript-tsx-mode

---

CHANGELOG.develop
layers/+lang/python/README.org
layers/+lang/python/config.el
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

Added support for MS Python Language Server as alternate backend.
Options are now `anaconda`, `lsp` or `lsp-ms`.
See layer README for configuration info.

python mode / lsp : Added support for Microsoft Python Language Server

---

CHANGELOG.develop
layers/+completion/helm/packages.el

When trying to complete a path at the `:e ` evil-ex-completion prompt by
pressing `TAB`.
Before: The default Emacs `*Completions*` buffer opens.
After: The `HELM Completion At Point` buffer opens.
And sorted the transient hooks alphabetically.
---
The issue was reported in the gitter chat:
https://gitter.im/syl20bnr/spacemacs?at=5cf3ab63e41fe15e75fc0e9f

[helm] Load helm before completion-at-point

---

CHANGELOG.develop
layers/+lang/html/packages.el

This PR enables `prettier` formatter for HTML buffers. Currently, `web-beautify` is being used, despite `(html :variables web-fmt-tool 'prettier)` set in `dotspacemacs/layers`. HTML is supported by `prettier` since [version 1.15.0](https://prettier.io/blog/2018/11/07/1.15.0.html).

Enable prettier formatter for HTML buffers

---

CHANGELOG.develop
doc/DOCUMENTATION.org
layers/+spacemacs/spacemacs-defaults/keybindings.el
layers/+spacemacs/spacemacs-purpose/packages.el

This one adds Spacemacs-flavoured bindings for [indirect buffer](https://www.gnu.org/software/emacs/manual/html_node/emacs/Indirect-Buffers.html) functions: `make-indirect-buffer`, `clone-indirect-buffer`, `clone-indirect-buffer-other-window` under `SPC b i` prefix.

Add new key bindings for indirect buffer functions

---

CHANGELOG.develop
layers/+lang/clojure/README.org

Don't need this `cider.nrepl/cider-middleware` in lein profiles.clj.
It will result in error, the `cider.nrepl/cider-middleware` not middleware but a vector of all cider-nrepl middlewares:
> https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl.clj#L483

Remove `cider.nrepl/cider-middleware` in lein quick start setting

---

CHANGELOG.develop
core/core-funcs.el
doc/DOCUMENTATION.org

Rationale: very often users required to find and delete all *.elc files
manually. That's a bit tedious.

spacemacs/recompile-elpa with argument deletes all existing *.elc files

---

CHANGELOG.develop
layers/+lang/agda/packages.el

It's now `agda2-auto-maybe-all`. They changed the functionality slightly and so have renamed it (it now tries to solve all goals if your cursor is not in a goal.)

Adapt agda layer to Agda 2.6.0.0 changes (fixes #12342)

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-evil/packages.el

A common use case for vim's / evil-mode's `inc-at-point`/`dec-at-point` is to change numbers across several lines, as in numbered lists. This patch adds `next-line` / `previous-line` to `evil-numbers-transient-state` to enable incrementing across lines without having to exist and restart the transient state.

Add j/k to evil-numbers transient state

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Although the Clojure repl utils (clojure.repl) are including in the `user`
namespace in Clojure projects, they are not available in your application
namespace.
The existing CIDER function `cider-repl-require-repl-utils` adds the Clojure
repl utils into the current namespace, so you can use functions such as `doc`
and `source`.
This is often a source of confusion for those new to Clojure / CIDER.

[Clojure] Keybinding require Clojure repl utils in current namespace

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Latest CIDER release uses the following commands for starting the REPL from
within Emacs (these commands have been in CIDER for over 6 months already)
`cider-jack-in-clj` to start a Clojure REPL
`cider-jack-in-clj&cljs` to start a Clojure and ClojureScript REPL
`cider-jack-in-cljs` to start a ClojureScript repl
The older aliases are deprecated and are being removed in the latest beta
release of CIDER (the version that Spacemacs uses, so this PR fixes broken keybindings)
`cider-jack-in`
`cider-jack-in-clojurescript`
Keybindings for these jack-in commands have been updated and as there are three
options they have been moved under Clojure mode repl > jack-in menu
The top level of the Clojure mode menu has the existing keybindings updated to
use the new commands.  A third top-level keybinding …

[Clojure] keybinding for updated repl jack-in commands

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Update the existing `SPC m g g` keybinding to use the command
`spacemacs/clj-find-var`.  
This makes finding a function definition a much
better experience as you dont have to have the REPL running to find a
definition, but when it is you can use a CIDER specific function.
`spacemacs/clj-find-var` is a wrapper that calls `cider-find-var` if the REPL is
running, otherwise it uses `dump-jump-go`.
Wrapper added in #9792

[Clojure] keybinding spacemacs/clj-find-var

---

CHANGELOG.develop
layers/+tools/shell/config.el

As mentioned in https://github.com/syl20bnr/spacemacs/issues/10779#issuecomment-427712967,
emacs 26.1 changed the default behavior for term-char-mode to prevent cursor
movement. This commit restores consistent behavior on all versions of emacs and
allows normal-mode motions to work again.
Note that the buffer is still read-only while in normal-mode, so operators that
change the line (such as `C`, `D`, `S`) still don't work.
Fixes #10956
Fixes #10779

shell: allow evil normal-mode movement in terminal buffer

---

CHANGELOG.develop
layers/+lang/go/README.org

`gopls` is Google’s upcoming Go language server; the other implementation
mentioned in the `lsp-mode` doc¹ has been discontinued².
So, I've added the recommended procedure³ to install `gopls`.
¹: https://github.com/emacs-lsp/lsp-mode/
²: https://github.com/saibing/bingo
³: https://github.com/golang/go/wiki/gopls

[go] Update doc on LSP setup.

---

CHANGELOG.develop
layers/+tools/ansible/packages.el

Fixes: #10848
Tested with:
<details><summary>
Ubuntu 18.04
</summary>
<pre>
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c5c63f48c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
</pre>
</details>
<details><summary>
Windows 1903
</summary>
<pre>
- OS: windows-nt
- Emacs: 26.3
- …

[ansible] Fix void-variable company-backends

---

layers/+completion/helm/funcs.el
layers/+completion/helm/packages.el

Filter useless buffers in Helm-mini, add command to unfiltered list buffers

---

CHANGELOG.develop
layers/+lang/html/packages.el

One-line commit that adds the ability to edit .svelte files to html mode.

[html] Add .svelte files to web-mode auto-mode-alist :mode handler

---

layers/+web-services/search-engine/packages.el

* `layers/+web-services/search-engine/packages.el` (`search-engine/init-engine-mode`): Fix typo "Hoggle" for the name of the Hoogle search engine.

[search-engine] Fix typo of "Hoogle" as "Hoggle"

---

CHANGELOG.develop
doc/FAQ.org
layers/+completion/helm/local/helm-spacemacs-help/helm-spacemacs-faq.el

The helm-org-get-candidates function was removed upstream.
Reversed the helm headings list, to match the order of the
questions in FAQ.org, so that the Common questions are
listed first.
Removed the : (colon) after the heading: How do I
in FAQ.org, to match the other parent headings.
Resolves: #13123
---
This PR proposes two solutions:
- `Version 1` uses the private function: `helm-org--get-candidates-in-file`
- `Version 2` uses `helm-org-build-sources`
This version uses a somewhat convoluted way to drill down to the FAQ.org headings:
`     (dolist (c (aref (aref (cdadar cands) 2) 0))`
Maybe there's a simpler method for accessing the headings.
Is one version better than the other?
Both versions seem to work the same otherwise.
With either version, when a helm candidate is chosen, then the …

Fix helm-spacemacs-help-faq, SPC h f

---

layers/+lang/rust/README.org

Fix an unclosed code block in README.org for Rust layer.

rust: Fix a broken code block in README

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Added keybindings for the Sesman REPL session management commands to the Clojure
layer, following the Spacemacs keybinding conventions.
https://docs.cider.mx/cider/0.23/usage/managing_connections.html
Sesman has been a part of CIDER for many versions now and provides session
management for nREPL connections (in fact any connections).
Sesman keybinds are placed in the `SPC m c` menu, providing a cleaner separation
between sending code to the repl and session management.
See issue #12593 and PR #13140 which covers the background for the design of
these additional keybindings.
Formatting the region and defun keybinds have been added, along with formatting
for edn files.
Evaluation up to point keybinding has also been added.
Documentation in the README has been updated to complete the …

[Clojure] Sesman and missing eval / format keybindings

---

core/core-spacebind.el
core/core-spacemacs.el
layers/+distributions/spacemacs-bootstrap/funcs.el
layers/+distributions/spacemacs-bootstrap/packages.el
tests/core/Makefile
tests/core/core-spacebind-utest.el
tests/layers/+distribution/spacemacs-base/Makefile
tests/layers/+distribution/spacemacs-base/spacebind-utest.el

Testing new macro for binding keys. The pros are:
- It's pretty much self descriptive.
- Enforces definition of prefixes for which-key
- Much more compact and readable than a bunch of function calls
- [Integrated with use-package](https://github.com/syl20bnr/spacemacs/pull/13300/files#diff-b2ea4bf2528d69e613b7735aba542594R99)
- Declarative and can be statically analyzed so:
- We'll be able to catch key binding collisions in CI
- Pull out data for  generating and keeping in sync key binding tables in README.org files.

Add spacebind macro and tests for it

---

CHANGELOG.develop
layers/+music/pianobar/README.org
layers/+music/pianobar/config.el
layers/+music/pianobar/packages.el

Configuration instructions are more detailed than usual, because it requires unusual effort to piece together otherwise.
This should save users a lot of keystrokes and/or configuration fiddling.

Add layer music/pianobar

---

CHANGELOG.develop
layers/+email/gnus/README.org
layers/+email/gnus/packages.el

The gnus variables were set in the `gnus/init-gnus`
functions `:config` section, that made them override
any user configurations.
Moving the variable declarations to the `:init`
section made them user configurable.
Fixes #13268
The diff doesn't match the description.
The variables were moved up a about 15 lines, but the diff shows the configurations that were above the variables being moved down instead.
---
(it still applies, but the change described above applies to all the variables that the `gnus` layer configures)
Made `gnus-summary-thread-gathering-function` user changeable
as a layer variable.
---
With the following `gnus` layer variable:
```elisp
(gnus :variables
gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
```
>gnus-summary-thread-gathering-function’s …

[gnus] Make the gnus variables user configurable

---

layers/+email/mu4e/config.el

The previous PR ( #13331 ) failed to handle everywhere `mu4e-modes` list is being used. So this will bring it back, but still use the added lists for `purpose` setup.

[#1598] Fix missing mu4e-modes error

---

.circleci/PR_changelong

Seems like the test gets skipped for the forks with CircleCI enabled :thinking:

Make changelog check more reliable.

---

core/core-themes-support.el

Fixes #13370 .
Theme was replaced by another one upstream.

Replaced doom-molokai with doom-monokai-classic

---

core/core-themes-support.el

Theme was restored upstream. Add it back
#13370

Add doom-molokai back to supported themes

---

core/core-themes-support.el

Add support for `doom-monokai-pro` theme.

[core-themes] Add support for doom-monokai-pro

---

layers/+emacs/helpful/packages.el

Follow help buffer convention for displaying helpful popup.
Reference: https://github.com/syl20bnr/spacemacs/blob/b7fd2fab6ed76f0877a9eb93eb39cc919634bfd2/layers/+spacemacs/spacemacs-visual/packages.el#L93

[helpful] follow help buffer convention for displaying helpful popup

---

layers/+spacemacs/spacemacs-completion/packages.el

Ivy-hydra is autoloaded so the require statement here is unnecessary. Because this require (commented out) statement was here before I uncommented it in the last PR (#13377), I leave it here (commented out) as it was before that PR.

fix issue #13395

---

CHANGELOG.develop
layers/+emacs/org/packages.el

It's been fixed upstream.
Use helm-goto-char to show match and reveal outlines
https://github.com/emacsorphanage/helm-ag/pull/304

[org] Remove obsolete fix, helm-ag unfold org line

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-defaults/README.org
layers/+spacemacs/spacemacs-defaults/keybindings.el

Add keybindings for the built in Emacs application called Easy PG, that provides
tools to encrypt/decrypt/sign/verify files and regions using PGP encryption.
Keybindings are defined using spacebind.
Resolves #13319

[easypg] keybindings using spacebind

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-layouts/README.org

Add layer variable documentation for persp-autokill-buffer-on-remove
Set to kill-weak, then buffers are deleted when the layout is deleted.
https://github.com/Bad-ptr/persp-mode.el#suggested-configuration
Add usage section
- describe the core usage of layouts
Add keybindings section
- include all keybindings for the layer
Fix formatting
- = instead of ~ and vice versa
Resolve #11698

[spacemacs-layouts] update readme with config and keybindings

---

CHANGELOG.develop
layers/+emacs/org/README.org
layers/+emacs/org/packages.el

`org-journal-new-scheduled-entry` and `org-journal-schedule-view` are both basic org-journal features.  `SPC a o j t` adds `t` for TODO under the org-journal prefix (`t` because it adds a TODO). 
Besides providing these shortcuts, their (self-)documentation exposes this functionality to the user.

add and document org-journal scheduled(-view) shortcuts

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-visual/packages.el

- reuse the bottom window for all windows that are in compilation mode and in
dap-server-log-mode. Without this change, you will get two windows on top of each
other when you do `SPC c c` and then `SPC m d d d`

[visual] Pin dap debug buffers to the bottom

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-misc/packages.el
layers/+tools/dap/README.org
layers/+tools/dap/packages.el

- added the same bindings you normally have under `SPC m d` under `SPC d`
similar to what Debug layer does. Most of the dap-bindings are not content
sensitive(e. g. rerun last debug session) and it doesn't make sense to restrict
them only to particular major modes.
- Moved `spacemacs/browse-docs-online-at-point` from `SPC d b` to `SPC h b d` to
avoid collisions.

[dap] Provide global keybindings for dap-mode

---

layers/+frameworks/vue/README.org

The package `vue-language-server` has been renamed to `vls`.
See https://github.com/vuejs/vetur/tree/master/server
Trying to use the old package would result in an error: https://github.com/neoclide/coc-vetur/issues/28

[vue] Update package name for vue-language-server

---

CHANGELOG.develop
layers/+lang/python/funcs.el

Update python-test-last to use pytest-again, which was added recently in the upstream pytest package.

[Python] Reflect upstream pytest update to python-test-last.

---

CHANGELOG.develop
layers/+filetree/treemacs/packages.el

Opening a dired buffer from the Treemacs buffer,
right after starting Spacemacs, shows the error message:
>treemacs-icons-dired--display: Wrong type argument: char-or-string-p, nil
Loading `treemacs-icons-dired-mode` from the `dired-load-hook`,
instead of from the `dired-mode-hook`, seems to fix it.
The `dired-load-hook` docstring says:
>Run after loading Dired.
The `dired-mode-hook` docstring says:
>Run at the very end of ‘dired-mode’.
---
A dired buffer can be opened from the Treemacs buffer:
- By pressing `SPC a d` and choosing a directory.
- Or with the cursor on a Treemacs projects directory and pressing: `oo`

[treemacs] load treemacs-icons-dired-mode earlier

---

layers/+lang/dart/packages.el

- lsp-dart was moved into a separate package so it has to be required separately.

[lsp][dart] Fix dart layer

---

CHANGELOG.develop
layers/+lang/major-modes/README.org
layers/+lang/major-modes/packages.el

The function `pkgbuild-update-srcinfo` was just added¹ to `pkgbuild-mode`,
and allows to easily produce a `.SRCINFO` file for a given `PKGBUILD`,
which is a required¹ element of an AUR package.
¹: https://github.com/juergenhoetzel/pkgbuild-mode/pull/18
²: https://wiki.archlinux.org/index.php/.SRCINFO
Cheers!

[major modes]: Add keybinding for pkgbuild-update-srcinfo

---

layers/+emacs/org/packages.el

for verb-response-headers-mode It's a major mode not a minor one.
lazy keybinding for  verb-response-body-mode
Without this change `C-h k` will crash throwing verb-response-headers-mode
variable is void.

[org-mode] [verb] fix binding for verb-response-headers-mode

---

layers/+lang/idris/packages.el

Since `idris` is indent-sensitive like Haskell, Python, Agda or PureScript, it should be added to `spacemacs-indent-sensitive-modes`.
Without this configuration, spacemacs inserts indentation when pasting a fragment of codes, which is not desirable.

[idris] Add to spacemacs-indent-sensitive-modes

---

layers/+lang/ruby/README.org

`ruby-mode` by default inserts an encoding comment at the top of a `.rb` file, which triggers [an error from RoboCop](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/Encoding) on Ruby 2.0+. [There is a variable to disable it](https://stackoverflow.com/questions/6453955/how-do-i-prevent-emacs-from-adding-coding-information-in-the-first-line). The instruction for doing so is added in the README for the Ruby layer.

[ruby] Add instruction on disabling the automatic insertion of encoding comment

---

CHANGELOG.develop
layers/+emacs/org/packages.el

Enable missing org-module.
fixes the open bug: 
https://github.com/syl20bnr/spacemacs/issues/13252
Last year's open discussion that touches similar topic:
https://github.com/syl20bnr/spacemacs/issues/12003
I believe that enabling it is a reasonable default, if org-agenda shows "Habit" enabled in the bottom of its UI and `org-habit` variables and functions are visible for the user.

[org] Enable org-habit module.

---

CHANGELOG.develop
layers/+tools/imenu-list/README.org
layers/+tools/imenu-list/funcs.el
layers/+tools/imenu-list/packages.el

The imenu-list layer currently defines a single global binding, which toggles the imenu tree sidebar.
With only a single buffer open, it's easy to refocus the sidebar using `spc w l` (the created window doesn't get an index for easy navigation), however this gets annoying with multiple buffers open. I've added a new function to focus the sidebar, creating it if it hasn't already been created.
New function bound under `spc b i`.
Existing toggle binding moved under UI toggle prefix: `spc T i` (previously `spc b t`). As this seems more consistent with the project binding mnemonics...
Bindings now using spacebind macro (via use-package keyword mechanism). Because it's shiny and new.

[imenu-list] Added keybinding to focus the imenu-list sidebar, creating if necessary.

---

CHANGELOG.develop
layers/+lang/clojure/packages.el

I changed key sequence of `cider-eval-print-last-sexp` from `ep` to `epl`.
This PR fixes this warning when reloading spacemacs configuration:
```
Error (use-package): cider/:init: Key sequence e p ; starts with non-prefix key e p
```
If anyone have the better way than this PR to resolve above warning, I would like to agree it.
Thanks for Spacemacs which is a wonderful distribution.

[clojure] Change leader key to fix warning

---

CHANGELOG.develop
layers/+tools/shell/funcs.el
layers/+tools/shell/packages.el

The variable: layouts-enable-local-variables
and function: spacemacs/make-variable-layout-local
are defined in the layer: spacemacs-layouts
But the spacemacs-layouts layer isn't loaded
in the distribution: spacemacs-base

[spacemacs-base] Fix void layout local variable and function

---

layers/+lang/python/README.org

Removed suggestion to manually install Python packages that are already
dependencies of python-language-server [1].
[1] https://github.com/palantir/python-language-server/blob/6a7eae7600a17b4f076263016639ff2a430b72e3/setup.py#L50-L58

[doc] Update list of suggested packages to install with python-language-server

---

CHANGELOG.develop
core/core-dotspacemacs.el
core/templates/.spacemacs.template

I started playing around with Andrea Corallo's `feature/native-comp` branch in upstream Emacs (a.k.a. [gccemacs](http://akrl.sdf.org/gccemacs.html)), and I realized that because his branch is based on Emacs 28, it's probably not going to remain compatible with Emacs 27 pdumps. In general, the layout of core elisp objects in Emacs might change between Emacs releases; for example, there have already been some changes to eieio slots in the Emacs 28 branch compared to what's in Emacs 27. This strategy is similar to how Spacemacs already uses `emacs-version` as the value of `dotspacemacs-elpa-subdirectory`, so that we have different byte-compiled elpa packages for different Emacs major versions.

[core] Encode emacs-version in dotspacemacs-emacs-dumper-dump-file

---

layers/+email/mu4e/packages.el

From the author of mu4e, org-mu4e.el is not supported anymore. Load the
supported org functionality from mu4e-org.el instead.
mu4e author -- "org-mu4e.el has been obsoleted in mu4e 1.4.x... the supported
parts are in mu4e-org.el now. And there's currently no real expectation you can
load those separately (it might work)."
I believe by separately means loading mu4e-org w/o having loaded mu4e.

Update mu4e to 1.4.x changes.

---

CHANGELOG.develop
layers/+source-control/git/README.org
layers/+source-control/git/config.el
layers/+source-control/git/funcs.el
layers/+source-control/git/packages.el

Minified hint:
`Chunks: n N p P RET Commits: b r f e q`
Full hint:
```
Chunks                   Commits                     Other
[p/P] prev /same commit  [b] adding lines            [c] cycle style
[n/N] next /same commit  [r] removing lines          [Y] copy hash
[RET] show commit        [f] last commit with lines  [B] magit-blame
[e] echo                    [Q] quit TS
[q] quit blaming
```
---
`q` is used in other transient states to close the transient state, but `magit-blame` uses it to close blame buffers and to disable `magit-blame-mode` from the last blame buffer.
Therefore I bound `Q` to close the transient state.
`q` can also be used to close the transient state when `magit-blame-mode` is disabled, it just requires `q` to be pressed one more time after the last blame buffer has …

[source-control] Add Git Blame Transient State

---

layers/+spacemacs/spacemacs-layouts/funcs.el
layers/+spacemacs/spacemacs-layouts/packages.el

Helm v3.3 no longer uses ido to get buffer list. So the change perp-mode makes
to ido won't affect helm anymore. Hence helm buffer list commands such as
helm-mini and helm-buffer-list will shows all buffers regardless of current
layout. Also `SPC l l` crashes with new helm.
This PR fixes them. We use the new helm variable helm-buffer-list-reorder-fn
to filter buffers. Because we compose this value users are still able to
customize this variable.

[layout] fix persp-mode integration with helm v3.3

---

layers/+spacemacs/spacemacs-editing/packages.el

Closes #13640
Moves origami bindings from `evil-normal-state-map` to `evil-motion-state-map`.
It enables folding in non-editable buffers like compilation buffers.

Move folding bindings to evil motion state map

---

CHANGELOG.develop
core/core-fonts-support.el
core/core-funcs.el

In a terminal, when a modes mode line name is diminished,
to two characters, and the first one is a unicode character,
then the second character overlaps the right side of the first character.
Resolves #12016

[core] Terminal fix mode line indicator overlap

---

layers/+lang/latex/config.el

Added additional tabular environments to latex-nofill-env variable.
This deactivates the automatic fill in a few more tabular environments.

Added additional tabular environments

---

layers/+filetree/treemacs/README.org

delete `ta`,`tf`,`th`,`tw` duplicate key binding.

[doc] Remove duplicate keyboard shortcuts

---

CHANGELOG.develop
layers/+tools/cfengine/README.org
layers/+tools/cfengine/packages.el

Mustache is the preferred templating in modern versions of CFEngine and it's
nice to have syntax highlighting when working with templates.
Now, when the CFEngine layer is in use, files ending in .mustache will be opened
in mustache-mode.

Added mustache-mode to CFEngine layer

---

layers/+checkers/syntax-checking/config.el
layers/+checkers/syntax-checking/packages.el

When you select `next-error` (which defaults to `spacemacs/next-error`) it will either call `flycheck-next-error` or emacs `next-error`.
With this variable set, when flycheck mode is enabled, the next-error function will first check for flycheck errors, then check for compilation buffer errors. (Personally i think this should be the default, but I'm preserving behaviour).

Allow config syntatx-checking-use-standard-error-navigation.

---

CHANGELOG.develop
layers/+intl/keyboard-layout/packages.el

Hi, this patch provides keyboard mappings for the `evil-lisp-state` package. 
It may be related to the unmerged #11625, but this is a different mode altogether.

[keyboard-layout] evil-lisp-state

---

layers/+intl/keyboard-layout/packages.el

When you use structurally safe editing, cleverparens is called and provides a different keymap that isn't remapped by keyboard-layout machinery. This problem is stated in #10174 . 
This PR opens the remapping for evil-cleverparens. As I do not use it myself, I think I didn't remap many of important movement bindings. Currently it provides a basic support for HJKL. 
Ideas of keys remapping are welcomed.

keyboard-layout: add evil-cleverparens remapping

---

layers/+email/mu4e/packages.el

When mu4e layer is present, org-store-link doesn't work immediately when you
start Emacs, unless you explicitly load mu4e.
It'd display "Please load mu4e before mu4e-org" message and do nothing.

fix: org-store-link doesn't work unless you load mu4e

---

CHANGELOG.develop
layers/+intl/keyboard-layout/README.org
layers/+intl/keyboard-layout/packages.el

Add `ediff` support to the `keyboard-layout` layer.
It works well using the bepo layout and should work with the other layouts but is untested with those.
`ediff-mode-map` is only defined once ediff is started, that's why I used `ediff-startup-hook` instead of `spacemacs|use-package-add-hook` or `with-eval-after-load` as I read in this issue: noctuid/general.el#59 but there may be another way. I'm new to emacs and spacemacs and this is my first time writing elisp so I'm not entirely sure.
See also this issue: https://github.com/emacs-evil/evil-collection/issues/196#issuecomment-419681661

[keyboard-layout] Add ediff remapping

---

CHANGELOG.develop
layers/+lang/factor/README.org
layers/+lang/factor/config.el
layers/+lang/factor/funcs.el

Fuel mode is responsible to connect to a Factor instance.  This change extends
the Factor layer to handle a graphical listener process, to which fuel can
connect afterwards.
A major motivation is also to make it easier to develop with different Factor
versions, which can be specified with (project-/directory-specific) variables.
When starting a Factor listener in a certain location this way, the elisp code
for fuel/factor mode is reloaded from that location.

Support running graphical Factor listener from Spacemacs and reloading relevant elisp code

---

CHANGELOG.develop
core/core-debug.el

This fixs #13681.
time-date.el requires cl-lib under Emacs 27 and above. Then the around advice
spacemacs//timed-require and spacemacs//load-timer of require will cause
recursive load under emacs 27 and above. The load sequences is: requiring cl-lib
uses autoload function time-since which loads time-date.el and then time-date.el
requires cl-lib.
The solution to break this recursive load sequence is to load time-date.el
before adding the around advice spacemacs//timed-require and
spacemacs//load-timer to require.

[core] fix broken --timed-requires and --adv-timers under emacs 27 and above

---

.circleci/shared

Apparently CircleCI substitutes vars in logs so the fail message reads like a  joke:
```
CircleCI didn't set 
nor ! This time...
Job restart sometimes helps.
Aborting the job.
```
:smile:

[CI] Tidy fail message

---

layers/+lang/haskell/README.org
layers/+lang/haskell/packages.el

The Hayoo site hasn't been available for quite a while now, and it doesn't seem to be coming back any time soon. There isn't much point in having a keybinding for it, I think.

[haskell] Remove hayoo from Haskell layer keybindings

---

layers/+completion/helm/funcs.el

This was the only place where `incf` was used instead of `cl-incf`, the PR fixes this error:
> Symbol’s function definition is void: incf

Fix incf causing an error message

---

layers/+spacemacs/spacemacs-layouts/funcs.el

`spacemacs//fixup-window-configs` is added as an `:around` advice for
`rename-buffer`.  It should preserve `rename-buffer`'s return value,
which is the new name of the buffer.
This pull request makes it do so.

[spacemacs-layouts] Fix return value of `rename-buffer`

---

CHANGELOG.develop
layers/+tools/vagrant/packages.el

According to the README, `SPC a t v t` should start `vagrant-tramp-term`, but
instead, it seems to have been bound to `SPC a t v`.  This means that it
overrode all of the other vagrant keybindings under the prefix `SPC a t v`.
The issue seems to have been a typo from commit e38c33f.
Relates to #13503.

[vagrant] Correctly bind `vagrant-tramp-term`

---

layers/+tools/lsp/packages.el

lsp-mode does not require yasnippet in order to function
from [the source](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L60):
```
(require 'yasnippet nil t)
```
This just removes the `:requires` clause from the lsp layer's packages list

[lsp] remove requirement for yasnippet

---

doc/BEGINNERS_TUTORIAL.org

[Unicode Character 'RIGHT DOUBLE QUOTATION MARK' (U+201D)](https://www.fileformat.info/info/unicode/char/201d/index.htm) breaks inline `code` styling.
Replacing it with [Unicode Character 'QUOTATION MARK' (U+0022)](https://www.fileformat.info/info/unicode/char/0022/index.htm) fixes it.

Fix inline `code` styling

---

core/core-configuration-layer.el

This fixes the issue that users have to import the public key manually
to pass spacelpa archive verification. See #12652

Fix spacelpa public key file name

---

layers/+emacs/org/packages.el

A simple replacement of obsolete function by new one to avoid warning in *messages* buffer 
Related to comments in [Issue: #13735]

[org] update org-journal obsolete functions

---

layers/+lang/html/packages.el

When editing Cakephp template files there is not highlighting. This adds the
`.ctp` files to the html language using web-mode.

Add ctp files to html language

---

layers/+lang/haskell/packages.el

The shortcut ", h h" gets bound to `lsp-describe-thing-at-point` by the LSP
layer. Having a shortcut for Hoogle is still very useful, so bind it to ", h g"
when LSP is activated.
*N.B.* This change doesn't yet contain any logic to limit the change to only when the LSP layer is active. I'd like to add that, but don't know how. I'm hoping some kind soul will let me know how to achieve that :)

[haskell] Add keybinding for Hoogle that works with LSP

---

layers/+os/osx/config.el

Restore the `SPC x w d` key binding for define-word-at-point, from
spacemacs-language.

[osx] Don't initialize osx-dictionary on non-mac systems

---

CHANGELOG.develop
layers/+distributions/spacemacs-bootstrap/funcs.el

The evil state foreground color on the mode-line was set to
the mode-line background color.
This caused problems with some themes.
[FEATURE REQUEST] Darker option for mode-line color codes #13731
Solution:
Set the evil state foreground color to the darker of the
mode-line face foreground or background colors.
---
I did a quick scan through the `themes-megapack` themes and it seemed to work for all of them.

[spacemacs-bootstrap] Fix mode-line evil state foreground

---

layers/+themes/theming/README.org

The names for the example attributes and the optional variables in the theming layer's documentation were lost in a previous commit. This commit restores those names.

Restore attribute and variable names in theming layer docs

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Add key bindings to refactor namespace forms for existing functions in clojure-mode
"ran" 'clojure-insert-ns-form
"raN" 'clojure-insert-ns-form-at-point
"rsn" 'clojure-sort-ns

[clojure] refactor namespace key bindings

---

layers/+tools/shell/README.org

Back in commit ac3752ffd, the binding for `vterm` was updated to fit in with the
rest of the `shell` layer bindings (under `SPC a t s v`).  However, the `README`
was not updated to match.  This PR updates the `README` for the `shell` layer.
Relates to #13503.

[shell] Update vterm binding in README

---

CHANGELOG.develop
layers/+source-control/version-control/README.org
layers/+source-control/version-control/packages.el

Recently discovered `browse-at-remote` and it seems to not be tied to github, it handles many other websites, so this change makes the key binding simpler.

Change browse-at-remote to "SPC go" sicne it is not github specific

---

layers/+chat/slack/packages.el

1. Make slack-mode bindings available in slack-thread-message-buffer-mode
2. Bind : to slack-insert-emoji
Let me know if you would prefer I split these into separate patches.

Improve slack layer keybindings

---

layers/+filetree/treemacs/README.org
layers/+filetree/treemacs/config.el
layers/+filetree/treemacs/packages.el

The author of Treemacs recently published a package enabling [all-the-icons support](https://melpa.org/#/treemacs-all-the-icons). This PR adds a variable to optionally enable this theme.

Add support for `all-the-icons` in Treemacs layer

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-defaults/keybindings.el

When Spacemacs' fancy logic works well, it is breathtaking. Sometimes, however,
you may need a way to reach in for something a little more raw: in this case,
going straight to `next-error` rather than `spacemacs/next-error`.
I chose `cn`/`cN` because:
* They seem to be unused thus far
* It makes sense to put these keybinding under compile, since they are
associated with Emac's base functionality for compilation.
* The analogous Ex commands are `:cn` and `:cN`. They work this way even in
Spacemacs (but I am trying to wean myself off Ex mode, since I see the
Spacemacs keybindings as far superior most scenarios).
* `cp` was already taken, so `cN` had to be used for going back.
Fixes #13815.

feat: mnemonic, ergonomic keybindings for next-error, previous-error

---

layers/+lang/haskell/config.el

`literate-haskell-mode` was renamed to `haskell-literate-mode` in this commit:
https://github.com/haskell/haskell-mode/commit/7ccb1ab0cc460bbc84e0e4b35719839f2a9dd598
Even though a deprecated alias was added, it broke Spacemacs' keybindings, which
were still all bound w.r.t. the old name.

[haskell] fix: keybindings not bound in haskell-literate-mode

---

layers/+lang/ess/packages.el

- use ess-offset-continued to replace the obsolete variables (from ESS 15.04):
ess-first-continued-statement-offset and ess-continued-statement-offset
- remove ess-expression-offset: no such variable now

[ESS] Fix: remove obsolete variables in ESS

---

CHANGELOG.develop
layers/+chat/slack/README.org
layers/+chat/slack/packages.el

Two patches:
1. alphabetize existing keybindings
2. add keybindings for `slack-all-threads` and `slack-all-unreads`
I tested by trying each of the keybindings.
Note that `slack-all-unreads` is buggy for me, which might be an argument for not publicizing it with toplevel keybindings.  But it mostly works, and the bug is unrelated to the keybindings (I can reproduce via `M-x`). I'd like to bind the function now and hope for a fix from upstream later.

Add more slack keybindings

---

layers/+lang/hy/README.org

hy-mode relies on jedhy for auto-completion
Fixes #12624
---
This also changes the `hy` installation instructions to use `pip3` instead of `pip`, 
because at least in PopOS 20.04, `pip3` works, but `pip` is not found:
>username@pop-os ~ % pip --version
zsh: command not found: pip
>username@pop-os ~ % pip3 --version                      
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
In Windows 1903, both `pip` and `pip3` works.
>C:\Users\username>pip --version
pip 20.2 from c:\users\username\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
>C:\Users\username>pip3 --version
pip 20.2 from c:\users\username\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

[hy] Add auto-completion installation instructions

---

layers/+lang/rust/packages.el

RON (Rusty Object Notation) is a JSON alternative used in the Rust community, and it currently is not available in Spacemacs. This PR Makes it a part of the Rust Layer (Sorry if I call it the "Rust Crate", Rust terminology).
1. RON is used in the Amethyst Game Engine to store data and configure it, adding it would make gamedev in Spacemacs easier
2. It's small and lite, so it's not THAT much more disk usage
3. It is only used in Rust, so having it's own layer makes no sense

Add Rusty Object Notation (RON) support to the Rust layer

---

layers/+lang/c-c++/README.org
layers/+lang/c-c++/funcs.el

The change will add 3 shortcuts for dependency, references trees and for finding dead functions.

[layers/+lang/c-c++]Add RTags shortcuts for trees and dead functions

---

layers/+lang/haskell/packages.el

Currently, when dante is used as backend, hlint is not used at all in flycheck.
Therefore, in this PR I added hlint checker as next checker after dante checker.
I have to admit I wasn't sure at all where to put the code in question. I can confirm that it works currently, but I am considering this first commit more of a first try and I hoping somebody will me guide better where to put it exactly and how to implement this properly.

[layers/+lang/haskell] Make flycheck run hlint checker after dante checker.

---

CHANGELOG.develop
layers/+misc/multiple-cursors/funcs.el

Paste using *table--cell-yank, in org-src-mode.
Fixes: Pasting into cells of table.el breaks table #13821

Fix org table evil paste

---

CHANGELOG.develop
layers/+checkers/syntax-checking/README.org
layers/+checkers/syntax-checking/config.el
layers/+checkers/syntax-checking/packages.el

While recently using haskell layer, I realized that flycheck popups dissapear after 5 seconds, which was making my development really hard -> error messages in haskell are usually pretty complex and lenghty, and trying to read them in 5 seconds is in most cases impossible, so I would repeatedly have to move and return my cursor on the position of error to see the message again and again.
After some digging and help from people on gitter, I learned that by default flycheck shows popup for 5 seconds (this default is coming from flycheck-pos-tip), and that duration of popup can be modified with `flycheck-pos-tip-timeout` variable. I put it to 20 seconds since I believe that is fairly long, we could even put it to something longer. I am not even sure if this popup timeout is useful at all to …

[layers/+lang/haskell] Prolong flycheck popup duration in Haskell layer.

---

CHANGELOG.develop
layers/+lang/haskell/README.org
layers/+lang/haskell/config.el
layers/+lang/haskell/funcs.el
layers/+lang/haskell/packages.el
layers/LAYERS.org

@duianto and @smile13241324 : here is another PR for Haskell layer with changes that we discussed. Solves issues #13867 and #13868.

[layers/+lang/haskell] Removed intero, ghc-mod and company-ghci backends, set dante as default backend.

---

.gitignore
CHANGELOG.develop

The Lua readme: https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/lua
and lsp-mode instructions: https://github.com/emacs-lsp/lsp-mode/wiki/Install-EmmyLua-Language-server
suggest adding `EmmyLua-LS-all.jar` to `~/.emacs.d`
That makes the file appear as an untracked file in magit.

[lua] Ignore EmmyLua-LS-all.jar in .emacs.d

---

layers/+lang/rust/packages.el

Hi, it's me again. A few weeks ago, I added Nabero's ron-mode package to the Spacemacs Rust layer. Since then, I've been working on my own package which adds support for RON to EMACS for a few reasons:
1. Nabero's package is not on MELPA. My new package has finished going through their review process and is now a part of that repository.
2. Nabero's package is a fork of a dead project. My new implementation is built from scratch, which is nessicary for a few purposes (most notably the licensing part, which is discussed in point 3).
3. Nabero's package appears to be unlicensed. This may be problematic in a project as large as Spacemacs (see https://choosealicense.com/no-permission/, GitHub's TOS prevent its use from becoming illegal but it is best to use a properly licensed project). My …

Move the Rust RON support to my own package (please read the description, the title may need context)

---

layers/+emacs/org/packages.el

Setting this variable to 'time is equivalent, while setting to t is
deprecated.

Set org-log-done to 'time instead of t

---

.travis.yml

[travis-ci] exclude elpa/gnupg from cache

---

layers/+lang/perl6/packages.el

In the *perl6 layer* exists a package called `perl6-mode` which no longer exists. This PR replaces it with `raku-mode` as recommended by the authors of `perl6-mode`
---
This PR should probably be merged ASAP, as the *perl6 layer* is **non-functional** without it.

Replace Depreciated Package in Perl6 Layer

---

layers/+lang/python/README.org
layers/+lang/python/config.el
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

Microsoft has released pyright language server for python. It boasts better
performance than the old Microsoft language server for python. This commit adds
supports for pyright language server in python layer

Support pyright language server for python layer

---

layers/+spacemacs/spacemacs-defaults/funcs.el

<SPC f e i> should work with Emacs profile switcher plexus/chemacs
--- 
Hey folks, I recently tried using https://github.com/plexus/chemacs and noticed that `<SPC f e i>` opens chemacs's init.el instead of Spacemacs' init.el.
This tiny change fixes the problem for me, but maybe I'm not alone who wants this behavior, what do you think?

Make find-init-file compatible with profile switcher

---

layers/+lang/haskell/README.org
layers/LAYERS.org

Improved Haskell README as discussed here https://github.com/syl20bnr/spacemacs/issues/13869 @smile13241324 .
There are a few things I was wondering about:
1. groovy layer README does not mention that user should enable auto-complete or syntax-checking layer. I wonder why is that so?
2. Syntax-checking is still a standalone section. I was considering if I can make it part of Configuration, but it really goes beyond just configuration, it explains how things work, so I decided to leave it as it is for now.
3. I wanted to make it very obvious what the minimal setup is. I am not sure if I managed to do that. Right now, I think new user needs to read Description, which is short, Install, which is straight forward, and then Configuration, and they are ready to go. Key bindings and especially …

Improved Haskell language layer README.

---

layers/+lang/php/packages.el

This conflicts with `company-capf` and you don't get any company completions
from the lsp-mode
Fix issue #13524

Disable php-extras when the php layer backend is lsp

---

layers/+spacemacs/spacemacs-org/README.org

Hi there! This is just a small fix in the documentation.
In https://github.com/syl20bnr/spacemacs/commit/145126875731e8ee38770b2adf709805f23672f7 org-bullets has been replaced with org-superstar, but the Readme of the `spacemacs-org` layer was not updated.
This commit mentions the correct library that is used to customize bullets.

Update spacemacs-org README on bullet library

---

layers/+tools/ipython-notebook/packages.el

In the documentation, it says this performs execute cell and goto next, while
the code was just executing the cell.
This desync could be fixed in either direction, but executing and going to next
feels more ergonomic while in the transient state, since we're jumping around
running rather than editing in that mode, so I've fixed it to do that.

[ipython] Fix bindinding for RET in transient state

---

layers/+lang/c-c++/README.org
layers/+lang/c-c++/funcs.el

Introduction of <SPC/M-m> g t shortcut for rtags-symbol-type.
Replacement of previous <SPC/M-m> g t into <SPC/M-m> g u for rtags-dependency-tree

[layer/+lang/c-c++] Introduction of shortcut for rtags-symbol-type

---

layers/+lang/c-c++/README.org

Updates the `C/C++ layer` documentation to reflect removal of the `cquery` Language Server Protocol backend.

Update number of LSP backends in C/C++ layer docs

---

layers/+lang/python/README.org
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

Add the python-shell-send-line function as in the other language layer, such as ESS. And bind it also as the same key.

[Python] Add python-shell-send-line function

---

layers/+tools/fasd/packages.el

`fasd-find-file` incorrectly interprets a prefix argument of value 1
as equivalent to nil ([issue][0]).
Work around this bug by just passing another positive number instead.
We choose 2.
[0]: https://framagit.org/steckerhalter/emacs-fasd/-/issues/14

[fasd] Fix bug in fasd-find-directory-only

---

CHANGELOG.develop
layers/+lang/python/README.org
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

The pyvenv-tracking-mode changes the virtual environment on changing focus
between buffers.

Implement pyvenv-tracking-mode

---

layers/+lang/markdown/packages.el

Simplify the regexps, and make sure they are anchored.

Fix up markdown mode specifiers

---

layers/+spacemacs/spacemacs-defaults/packages.el

The links use a separate keymap bound directly to the widget, circumventing the existing evil keybindings.
This fixes the [bug](https://github.com/syl20bnr/spacemacs/pull/13949#issuecomment-694685304) found by @duianto.

[core] Fix evil keybindings when a link is selected in Custom-mode

---

CHANGELOG.develop
layers/+spacemacs/spacemacs-defaults/keybindings.el

This is to bundle it with other describe functions. The hope is to make the help -> describe menu more complete.

[core] add keybinding hdT for describe-text-properties

---

layers/+completion/ivy/packages.el

In the doc ivy-avy makes it possible to select a candidate with avy by using C-' in an ivy minibuffer.
This functionality used to come with swiper, but it was split: https://github.com/melpa/melpa/pull/6951
Copy pasta from our sister project Doom: https://github.com/hlissner/doom-emacs/pull/3414

[ivy] add ivy-avy

---

CHANGELOG.develop
layers/+emacs/org/README.org
layers/+emacs/org/packages.el

See the animation in the package's [README](https://github.com/unhammer/org-rich-yank/blob/master/README.org). If necessary, I can put this package behind a switch like others are. However it's a small package (133 sloc) which integrates well with what's there so I didn't default to that.
I like that Spacemacs provides a very rich, full-featured experience via layers and I think this fills a niche. I use this package myself regularly when I am studying and analyzing a problem, and want to snip pieces of code out of various files in a code base and put them into one place with commentary, TODOs, &c.

[org] support rich insert of code from other buffers (org-rich-yank)

---

layers/+frameworks/react/funcs.el
layers/+frameworks/vue/funcs.el
layers/+lang/go/funcs.el
layers/+lang/javascript/funcs.el
layers/+lang/typescript/funcs.el

`lsp-diagnostic-package` was renamed to `lsp-diagnostics-provider` in
[LSP version 7.0.1](https://github.com/emacs-lsp/lsp-mode/blob/f23159a85f4be5c148ca204cd5935552fa577aaa/CHANGELOG.org#release-701).
Source: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-diagnostics.el#L30-L41

[lsp] Fix lsp-diagnostics-provider name

---

layers/+os/osx/README.org

Fix these problems:
- unbalanced parens
- misspelled name of function `setq-default`

[osx] Fix broken code in instructions for setting config variables

---

CHANGELOG.develop
layers/+lang/python/README.org
layers/+lang/python/funcs.el
layers/+lang/python/packages.el

Hi @smile13241324 ,
The Emacs-27 had a new function `python-shell-send-statement` for sending statement under cursor to python shell, I add it to Spacemacs and compatible with Emacs < 27. Please review it. Thanks.
B.R.
Lin

Add `spacemacs/python-shell-send-statement' for sending statement

---

layers/+source-control/version-control/funcs.el
layers/+source-control/version-control/packages.el

Fixed `git-gutter+` refresh when a buffer is staged or unstaged in Magit.

Fix git-gutter+ refresh on Magit refresh

---

CHANGELOG.develop
layers/+source-control/git/packages.el

In `*magit*` buffer, minor mode `magit-flow` overwrites key `C-f` from `forward-char` to `magit-gitflow-popup`.
It may be confusing that `C-a` `C-e` `C-b` are all cursor motion except `C-f`.
This PR makes `magit-gitflow-popup` only bound to `%`.
Ref:
https://github.com/jtatarik/magit-gitflow/issues/11
https://github.com/jtatarik/magit-gitflow/blob/cc41b561ec6eea947fe9a176349fb4f771ed865b/magit-gitflow.el#L43-L48

Don't let magit-gitflow mode overwrite `C-f` key binding.

---

CHANGELOG.develop
layers/+misc/multiple-cursors/packages.el

Resolves #13948
problem:
The p key tries to paste in the read-only magit buffer,
instead of calling magit-push.
After toggling text-mode on and off (C-t or \),
because evil-mc-mode becomes enabled when text-mode is enabled.

[multiple-cursors] Disable evil-mc-mode in magit-mode

---

layers/+lang/haskell/packages.el

See https://github.com/haskell/haskell-mode/commit/7ccb1ab0cc460bbc84e0e4b35719839f2a9dd598.
We should keep the old assignment around for a bit to support people on
old versions of `haskell-mode`.

literate-haskell-mode has been renamed to haskell-literate-mode

---

CHANGELOG.develop
layers/+tools/ranger/README.org

The ranger layer does not describe yet how to actually use ranger by default, while also the [instructions for the original ranger package](https://github.com/ralesi/ranger.el#setting-as-default-directory-handler) don't work (i.e. setting `ranger-override-dired` via customize does not work in Spacemacs).
I created a feature branch but forgot to check it out (still need to get used to magit). I hope it is fine that I create this PR now directly (and be more careful/wiser next time).

Add instruction how to use ranger by default

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

New command added to CIDER in version 0.26 to evaluate the list around the
current point, different to evaluate sexp around point which also evaluates
symbols.
This command is useful for evaluating nested expressions without having to jump to the end of the expression.  It will evaluate function calls as well as evaluate collections as functions (lists, maps, vectors, sets).
https://github.com/clojure-emacs/cider/pull/2881
Thank you <3

[clojure] key binding for cider eval list around point

---

layers/+emacs/tabs/config.el

Fix a typo in the tabs layer `config.el` file

[tabs] Fix typo

---

CHANGELOG.develop
layers/+completion/ivy/funcs.el
layers/+completion/ivy/packages.el

Spacemacs uses spacemacs/swiper functions that use the less sophisticated
spacemacs//counsel-current-region-or-symbol instead of ivy's native
ivy-thing-at-point function. This commit removes those spacemacs functions and
rebinds the shortcuts to their better native equivalents.
Again forgot to make a fix branch because I forgot because I am always fighting
with git. Anyway, again I will try to be more alert next time.

Replace spacemacs/swiper with better native swiper functions

---

layers/+lang/mercury/packages.el

`mercury-mode` had been replaced by `metal-mercury-mode`. Now `mercury-mode` can't be found from all sources so it needs to be removed.

remove package `mercury-mode` which no more exist

---

layers/+frameworks/vue/funcs.el

@thanhvg Vue web-mode-script-padding is 0, and web-mode-style-padding should also be 0?

Add web-mode-style-padding 0 to vue layer

---

CHANGELOG.develop
layers/+distributions/spacemacs-bootstrap/packages.el
layers/+spacemacs/spacemacs-editing/packages.el

https://github.com/emacs-evil/evil made `undo-tree` optional:
Make undo-tree an optional dependency https://github.com/emacs-evil/evil/pull/1360
Issue:
This doesn't work in the `spacemacs-base` distribution:
>evil-undo: Symbol’s function definition is void: undo-tree-undo
evil-redo: Symbol’s function definition is void: undo-tree-redo
Because `undo-tree` is loaded in the `spacemacs-editing` layer,
but it isn't used by default in `spacemacs-base`.
The variable `configuration-layer--used-layers` only lists these spacemacs layers:
```
spacemacs-bootstrap
spacemacs-defaults
spacemacs-base
spacemacs-org
```

Set evil-undo-system to undo-tree

---

layers/+frameworks/vue/layers.el

without this, spacemacs//javascript-setup-checkers in package.el:45 will not be
found unless user has the layer installed already

Add missing dependency on javascript layer

---

layers/+spacemacs/spacemacs-defaults/packages.el

Before:
After - new prefix:
After - content of the new prefix:

line-number funcs under SPC t n

---

CHANGELOG.develop
layers/+completion/ivy/funcs.el
layers/+completion/ivy/packages.el

By default Ivy uses `find-file` which uses Emacs `abort-if-file-too-large`
function to check/warn before opening large files. That function however does
not take into account Spacemacs its `spacemacs-large-file-modes-list`. Instead
ivy should use `find-file-noselect` to skip Emacs it large file warning and let
it to Spacemacs its `spacemacs/check-large-file` function. Additionally [Emacs
tips on
comments](https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html)
recommends to use 3 semicolons for comments that function as headings.

Fix counsel find-file functions to use Spacemacs large file check

---

CHANGELOG.develop
layers/+completion/ivy/README.org
layers/+completion/ivy/packages.el
layers/+spacemacs/spacemacs-completion/funcs.el

This enables navigating up in the `ivy-reverse-i-search` list with `C-k`.
The same rebinding from `C-k` to `C-M-k` to kill a list entry,
is also done in the `ivy-switch-buffer`.

[ivy] Rebind C-k to C-M-k in ivy-reverse-i-search

---

layers/+tools/languagetool/README.org
layers/+tools/languagetool/funcs.el

The `langtool` package can also work against a running server instead of a LanguageTool binary/classpath. Accordingly, the `spacemacs//languagetool-detect` function should check whether the server variables are set. I added a check and a description in the `README.md`.

[layers/+tools/languagetool] Allow HTTP server instead of binary

---

CHANGELOG.org
core/core-dotspacemacs.el
core/templates/.spacemacs.template
layers/+spacemacs/spacemacs-editing/README.org
layers/+spacemacs/spacemacs-editing/packages.el
layers/LAYERS.org

Not confident that I have plugged this in everywhere that I should have. However
I tested locally and it seems to be working. Feedback coveted.

[editing] Integrate evil-vimish-fold via dotspacemacs-folding-method

---

core/core-configuration-layer.el
core/core-dotspacemacs.el
core/core-env.el
core/core-funcs.el

This PR makes minor changes to `core/` Elisp code in order to remove some compilation warnings (e.g. missing arguments, an implicit `cl.el` usage, etc.).

Fix misc. compilation warnings in core

---

layers/+lang/typescript/README.org
layers/+lang/typescript/packages.el

This fixes a problem when using 'lsp backend: the lsp layer binds its own
formatting functions under "=" as a prefix. The spacemacs/typescript-format
function which the typescript layer defines has advantages over these, mainly
it respects the typescript-fmt-tool variable (uses the formatting tool that
theuser specified).
This patch solves this by keybinding leader+"==" to the function when
typescript-backend is set to 'lsp and binding to leader+"=" in any other case.
fixes #13719
N.B. the considerations at the end of that thread
(see https://hacktoberfest.digitalocean.com/hacktoberfest-update)

Bind typescript-format to "==" or "=" depending on backend

---

layers/+lang/c-c++/README.org

Noticed a typo [here](https://develop.spacemacs.org/layers/+lang/c-c++/README.html#enable-google-set-c-style) and wanted to fix it.

[c-c++] Fixed typo in README.org

---

layers/+spacemacs/spacemacs-defaults/keybindings.el

"SPC d" was used for documentation related keybindings, such as in `dash`
layer.
But it's now used for `dap` layer exclusively.
Removing this won't cause any issue as `dap` layer would correctly set
the keybindings once it's loaded.

remove "SPC d" binding

---

.gitignore

* meghanada is an LSP client for Java
* eln-cache (gccemacs) is for the native-comp branch of Emacs 28.0
* vimish-fold is there because said package has persistent folds

Add meghanada, eln-cache and vimish-fold to .gitignore

---

layers/+lang/python/packages.el

Reduces clutter. We do this also for other language specific minor modes.

Hide sphinx-doc-mode lighter

---

doc/DOCUMENTATION.org

Pull request #10297 made the Emacs server optional, so that it does
not start up unless the init file is modified to enable it. The
documentation, however, indicates that the opposite is true. This
fix updates the documentation to be consistent with the actual
behavior.
Thank you <3

Modify documentation to reflect that Emacs server is off by default

---

CHANGELOG.develop
layers/+emacs/org/README.org
layers/+emacs/org/packages.el

I chose to go this way rather than the other way because:
* Whenever you can avoid holding down a modifier key, great!
* It seems like the more specific should yield to the more general
This may be a controversial change, because it could break some folks' finger
memory. However I consider this a very unpleasant inconsistency that inhibits
the development of finger memory, so I thought I would at least suggest it as
the default for Spacemacs.

[org] SPC m s N -> SPC m s w to match mnemonics of SPC n w

---

layers/+lang/ocaml/README.org
layers/+lang/ocaml/config.el
layers/+lang/ocaml/packages.el

This change adds support for automatically formatting OCaml code on save, using the [`ocamlformat`](https://github.com/ocaml-ppx/ocamlformat) tool.  I left it disabled by default, since ocamlformat isn't as universally adopted as, say, gofmt.

[ocaml] Add ocamlformat package and configure format-on-save

---

layers/+completion/helm/funcs.el
layers/+completion/helm/packages.el

It's been advised by the upstream of `helm-ag` to set
`helm-ag-success-exit-status` to `'(0 2)`.
This PR adopted this suggestion.
ref: https://github.com/emacsorphanage/helm-ag#helm-agel-with-other-searching-tools
---
For `helm-ls-git` package, it's advised to set use `magit`as a bette alternative to
`vcr-dir` as the underlying command for getting `git status`.
This PR adopted this suggestion when `magit` package is in use.
Ref: https://github.com/emacs-helm/helm-ls-git/blob/4da1a53f2f0a078ee2e896a914a1b19c0bf1d5ed/helm-ls-git.el#L184-L189
Signed-off-by: Lucius Hu <lebensterben@users.noreply.github.com>

Minor changes on `helm` layer

---

layers/+lang/erlang/README.org
layers/+lang/erlang/config.el
layers/+lang/erlang/funcs.el
layers/+lang/erlang/layers.el
layers/+lang/erlang/packages.el

Basic changes to add LSP support for erlang layer using [erlang_ls](https://erlang-ls.github.io/) backend.
Supported [features](https://erlang-ls.github.io/features/) 
Example of my `dotspacemacs-configuration-layers`
```
(erlang :variables
erlang-backend 'lsp
erlang-root-dir "/home/carlosrendon/.otp_builds/otp_22_kred/lib/erlang"
erlang-man-root-dir "/home/carlosrendon/.otp_builds/otp_22_kred/lib/erlang/man"
erlang-ls-path "/home/carlosrendon/.erlang_ls/_build/default/bin/"
erlang-fill-column 100
company-minimum-prefix-length 1
lsp-ui-doc-position 'bottom
projectile-enable-caching t)
```
Thank you <3

[erlang] add LSP support through erlang_ls

---

CHANGELOG.develop
layers/+tools/ranger/README.org
layers/+tools/ranger/config.el
layers/+tools/ranger/packages.el

Added `'ranger` as an option to the variable: `ranger-enter-with-minus`
Changed the default value from: `t` to: `'deer`.
Bound the key to `evil-motion-state-map` instead of `evil-normal-state-map`
so that `-` also works from the Spacemacs home buffer.
Fixes:
Spacemacs ranger layer: use ranger with ranger-enter-with-minus option
#14086

[ranger] Add 'ranger as an option to ranger-enter-with-minus

---

layers/+lang/latex/README.org
layers/+lang/latex/config.el
layers/+lang/latex/funcs.el
layers/+lang/latex/layers.el
layers/+lang/latex/packages.el

This commit adds LSP support to the latex layer. As part of this it resolves some of the key conflicts however only if LSP is activated.

Add lsp support to latex layer

---

layers/+tools/shell/README.org
layers/+tools/shell/config.el
layers/+tools/shell/funcs.el
layers/+tools/shell/packages.el

Based on http://xenodium.com/search-bash-history-with-emacs-helm/
<del>
Add new helm/ivy functions `spacemacs/helm-shell-search-history`,
spacemacs/counsel-shell-search-history to search bash history and insert to
vterm/shell
Bind this function to M-r for vterm and shell mode.
New layer variable spacemacs-bash-history-file-locatition to customize bash file
Other thoughts:
- probaly should be opt-in
</del>
Add new helm/ivy functions `spacemacs/helm-vterm-search-history`,
`spacemacs/counsel-vterm-search-history` to search bash history and insert to
vterm/shell
Bind this function to M-r for vterm
New layer variable `spacemacs-vterm-history-file-locatition` to customize bash file
Default is nil.
Also bind add counsel-shell-history to `, H` for shell-mode in the same
convention as helm …

[shell] new helm/ivy functions to search history and bind it to M-r

---

CHANGELOG.develop
layers/+emacs/org/funcs.el
layers/+emacs/org/packages.el

Having to manually press i after using any of these commands is annoying to say
the least. This commit affects the following commands:
- org-insert-drawer
- org-insert-heading
- org-insert-item
- org-insert-structure-template
Change to org-insert-heading also affects other commands that use it
internally (e.g. org-insert-subheading).

[org] Activate insert state after some org-insert-* commands

---

layers/+tools/shell/packages.el

`eshell-buffer-shorthand` was removed in Emacs 25, see https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.25#L1078-L1082

Remove eshell obsolete variable

---

CHANGELOG.develop
layers/+readers/pdf/funcs.el
layers/+readers/pdf/packages.el

Backwards compatible by showing the docs by default. Allows to reclaim the precious display space for viewing the actual PDF.

[pdf] ~?~ toggles transient sate documentation hint (shown by default)

---

layers/+emacs/org/README.org
layers/+emacs/org/packages.el

Add tR hotkey for org-table-recalculate-buffer-tables. Without this
hotkey, there isn't an easy way to recalculate all of the calculated
fields within a table at once.
The tr hotkey for org-table-recalculate is only for recalculating a
single field within the table.
I used this page from the manual as a reference:
https://orgmode.org/manual/Updating-the-table.html#Updating-the-table

Add tR hotkey for org-table-recalculate-buffer-tables

---

CHANGELOG.develop
layers/+source-control/github/README.org
layers/+source-control/github/packages.el

Grip-mode renders a preview of github README files locally, so you can check how they look before pushing to github.
I figured that more people would like it, and that it would be great to have this as standard functionality in the github layer.
I've added it under keybindings `SPC g h p` (toggle grip mode)

Add grip-mode to github layer

---

CHANGELOG.develop
core/core-dotspacemacs.el
core/templates/.spacemacs.template
doc/DOCUMENTATION.org
layers/+spacemacs/spacemacs-editing/README.org
layers/+spacemacs/spacemacs-editing/packages.el
layers/LAYERS.org

Add [persistent-scratch](https://github.com/Fanael/persistent-scratch) and [unkillable-scratch](https://github.com/EricCrosson/unkillable-scratch) packages into `core/spacemacs-editing` layer.
It will make sense if you want to save your drafts in `*scratch*` buffer temporarily.
Things you write down in `*scratch*` buffer will be automatically saved and restored.
This feature requests `spacemacs-scratch-mode-hook` introduced in PR #13968

Add persistent-scratch and unkillable-scratch into core/spacemacs-editing layer

---

doc/DOCUMENTATION.org

The documentation for setting a prefix for major-mode keybinding is wrong.
Although it would be logical when using `spacemacs/declare-prefix-for-mode` to omit the "m" (for `SPC m` or `,`) in the keybinding definition, it currently does not work that way. Omitting the "m" results in a prefix named "prefix" instead of the desired prefix name. Because all (correct functioning) layers (e.g. org and pdf layer) define the prefix including the "m", it is probably best to just correct the documentation (instead of correcting the `spacemacs/declare-prefix-for-mode` function definition)

Fix major-mode set key prefix documentation

---

CHANGELOG.develop
layers/+distributions/spacemacs-bootstrap/funcs.el
layers/+distributions/spacemacs-bootstrap/packages.el

This is a feature whose equivalent I had looked for previously and not found. I bumped into it in [this excellent article](https://karthinks.com/software/batteries-included-with-emacs/) which is a survey of "batteries included" parts of Emacs. He mentions Spacemacs (in a positive light) in the article, but the article is about what you can do _without_ distributions like Spacemacs, Doom, or Prelude. As such, this seems like an opportunity to make Spacemacs even better---i.e. by making these relatively unknown batteries that are already present in Emacs more discoverable in Spacemacs.
I put it in the folding menu `z` because that fits its usecase. I used `$` because:
* the out-of-the-box Emacs keybindings is `C-x $`.
* the menu is already fairly saturated
* I didn't know what else to base …

[core] add z$ as Evil keybinding for set-selective-display

---

core/core-keybindings.el
layers/+frameworks/react/packages.el
layers/+lang/javascript/packages.el
layers/+lang/typescript/packages.el
layers/+tools/lsp/config.el
layers/+tools/lsp/funcs.el
layers/+tools/lsp/packages.el
layers/+tools/tide/config.el
layers/+tools/tide/funcs.el
layers/+tools/tide/packages.el

There are three commits in this PR. The first one is the most important, the other two are demonstration of the improvement.
This commit added add a new function defun `spacemacs/declare-prefix-for-minor-mode` and improved `spacemacs/set-leader-keys-for-minor-mode`.
`which-key` package recently introduced a new api `which-key-add-keymap-based-replacements` which improves performance and allows prefix and namings to be stored directly in keymap. This is a great improvement.
With this new api we now make change to `spacemacs/declare-prefix-for-minor-mode` to manage prefix also. For example:
``` elisp
(spacemacs/set-leader-keys-for-minor-mode 'lsp-mode
"=" "format"
"=b" #'lsp-format-buffer)
````
Before we had to use another api to bind prefix `spacemacs/declare-prefix-for-mode` which only …

[core][tide][lsp] improve spacemacs/set-leader-keys-for-minor-mode and apply it to tide and lsp layers

---

CHANGELOG.develop
layers/+frameworks/react/README.org
layers/+frameworks/react/packages.el

Declared key binding prefixes.
And updated the react layer documentation:
- Mentioned the additional key bindings in the javascript layer
- Added a link to the javascript layer
Fixes: 
React layer does not inherit keybindings from javascript layer #14103
Before:
After:

[react] Set layer keymaps: javascript as parent to react

---

CHANGELOG.develop
layers/+lang/clojure/README.org
layers/+lang/clojure/packages.el

Add key binding to evaluate the current namespace form (very useful when
starting CIDER as it loads in clojure.core to enable the cider-clojure-docs
functions to work)
Add keybinding to reload all namespaces into the REPL process
Adjusted key bindings to be lower case under `en` sub-menu.

[clojure] add namespace eval and reload key bindings

---

layers/+spacemacs/spacemacs-editing/README.org
layers/+spacemacs/spacemacs-editing/packages.el

This layer helps quickly sorting Dired buffers in various ways, such as
time, size, etc.
I think the underlying package is useful and worth a place in spacemacs.
It has also been promoted by Pragmatic Emacs before (albeit long time
ago): http://pragmaticemacs.com/emacs/speedy-sorting-in-dired-with-dired-quick-sort/
Disclaimer: I'm the author of dired-quick-sort package

Add dired-quick-sort layer

---

layers/+completion/helm/packages.el

Currently 'helm-ag-mode-jump-other-window is bound both to RET and to C-o (its
original default binding), while 'helm-ag-mode-jump isn't bound at all (its
original default binding is RET).  This commit removes our customization so that
both 'helm-ag-mode-jump-other-window and 'helm-ag-mode-jump have bindings in the
mode.

Revert helm-ag and helm-grep search results window binding of RET to default

---

core/core-keybindings.el

Seems like it collides with Evil insert somehow. Have to investigate.

Do not store major mode replacements in keymap [bugged]

---

layers/+lang/fsharp/funcs.el

First off I want to thank @smile13241324 for taking the time to make lsp
working with the fsharp layer!
Unfortunately the eglot configuration for automatically starting a server instance when
opening a file is not quite right. It tries to start the server twice which leads
to more problems down the line. Also the company-backend is not properly setup
so auto-completion does not work reliably when using lsp or eglot.
I also found an upstream issue in fsharp-mode which causes problems with
company-mode. I already created a [pull request](https://github.com/fsharp/emacs-fsharp-mode/pull/255) to fix that and hope that it will be
merged soon.

Fix fsharp-mode auto-completion unreliable

---

core/templates/.spacemacs.template

Add a comment about the font :size difference between:
integer (pixel size)
floating-point (point size)
Point size is recommended, because it's device independent.
source:
https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/XLFD/xlfd.html
Thanks libensterben for the info about point size being device independent.
#14142 (comment)
The font size comment was requested in:
ui/font is too small in default .spacemacs even with all prerequisites #14142

[core] Update dotfile, font :size comment: int vs float

---

core/core-configuration-layer.el

When the restart-emacs package is being updated.
The update packages restart message, still shows the (SPC q r) key binding even
though it doesn't work.
The member function compared a string against a list of symbols.
Explain that the key binding won't work this time.
Emacs has to be restarted to actually install the new version of the packages (SPC q r).
Emacs has to be restarted to actually install the new version of the packages
(SPC q r) won't work this time, because the restart-emacs package is being updated.

[core] Fix package update restart message

---

CHANGELOG.develop
layers/+lang/latex/README.org
layers/+lang/latex/config.el
layers/+lang/latex/packages.el

- Added a new layer config variable `latex-build-engine`, a thin wrapper of
`TeX-engine` (This addresses #14192) :
- For better support of non-european character set rendering, `xetex` is
chosen when it's found on PATH, and when eithe `chinese` or `japanese`
layer is enabled
- Added a new layer config variable `latex-enable-preview`:
- When non-nil, `auto-revert-mode` is added to `doc-view-mode-hook`
- Previously this is described in documentation but requires users to set it
manually
- Documentation:
- Added a section that lists are layer config variables
- Improved all documentation examples, s.t. they are valid elisp forms to be
evaluated directly
- Improved the section on backend:
- Emphsized that LSP layer is always preferred
- Provided information on installing the language server
- …

LaTeX: improved i18n support and documentation

---

layers/+completion/ivy/packages.el

bind `C-SPC` to  `ivy-call-and-recenter`
this is the closest thing to helm follow mode in ivy world
unbind `g` key and map `U` for
`for ivy-occur-mode-map` and `ivy-occur-grep-mode-map`

[ivy] improve key bindings

---

CHANGELOG.develop
doc/DOCUMENTATION.org
layers/+spacemacs/spacemacs-navigation/local/info+/info+.el

Spacemacs lacks a keybinding alternative to the most natural way of scrolling
Info pages (i.e. SPC) in vanilla Emacs.
This commit adds J/K to scroll most naturally through info pages.
Currently, in Info-mode, a keybinding for J is not defined while K is bound to
evil-lookup.
Issue #2828 already addresses the inconsistent experience, and in my opinion this
can and should be improved as navigating Info pages is a very crucial part of
using Emacs.
Personally I have bound J/K to scroll page up/down in buffers/pdf/djvu/doc-view,
which I inherited from using the zathura pdf reader, and I think this is a better
default than the default vim alternatives.

In navigation layer, Bind J/K to scroll up/down in Info-mode
